import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'

/**
 * Generates the virtual:cer-components module code.
 * Scans app/components/ and produces side-effect imports for registration.
 */
export async function generateComponentsCode(componentsDir: string): Promise<string> {
  if (!existsSync(componentsDir)) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\n// No components directory found\n`
  }

  const files = await scanDirectory('**/*.ts', componentsDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\n// No components found\n`
  }

  const lines: string[] = ['// AUTO-GENERATED by vite-plugin-cer-app', '']

  for (const file of files) {
    lines.push(`import ${JSON.stringify(file)}`)
  }

  lines.push('')

  return lines.join('\n')
}
