import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'

/**
 * Generates the virtual:cer-composables module code.
 * Scans app/composables/ and re-exports all composable functions.
 */
export async function generateComposablesCode(composablesDir: string): Promise<string> {
  if (!existsSync(composablesDir)) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\n// No composables directory found\n`
  }

  const files = await scanDirectory('**/*.ts', composablesDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\n// No composables found\n`
  }

  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  for (const file of files) {
    lines.push(`export * from ${JSON.stringify(file)}`)
  }

  lines.push('')

  return lines.join('\n')
}
