import { extractComponentRegistrations } from '@jasonshimmy/custom-elements-runtime/vite-plugin'
import { existsSync, readFileSync } from 'node:fs'
import { parseContentFileAsync } from '../content/parser.js'
import { scanContentFiles } from '../content/scanner.js'
import { scanDirectory } from '../scanner.js'

function emptyModule(): string {
  return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport {}\n`
}

export async function buildComponentManifest(componentsDir: string): Promise<Map<string, string>> {
  const manifest = new Map<string, string>()
  if (!existsSync(componentsDir)) return manifest

  const files = await scanDirectory(componentsDir)
  for (const file of files) {
    try {
      const source = readFileSync(file, 'utf-8')
      for (const tag of extractComponentRegistrations(source)) {
        manifest.set(tag, file)
      }
    } catch {
      // Skip unreadable files.
    }
  }

  return manifest
}

export async function collectMarkdownTags(contentDir: string): Promise<Map<string, Set<string>>> {
  const tags = new Map<string, Set<string>>()
  if (!existsSync(contentDir)) return tags

  const files = await scanContentFiles(contentDir)
  const markdownFiles = files.filter((file) => file.ext === 'md')

  await Promise.all(
    markdownFiles.map(async (file) => {
      try {
        const item = await parseContentFileAsync(file, contentDir)
        tags.set(item._path, new Set([...item.body.replace(/<!--[\s\S]*?-->/g, '').matchAll(/<([a-z][a-z0-9]*(?:-[a-z0-9]+)+)(?:\s|\/?>)/g)].map((match) => match[1])))
      } catch (err) {
        console.warn(
          `[cer-app] Skipping content file (parse error): ${file.filePath}\n  ${(err as Error).message}`,
        )
      }
    }),
  )

  // Reads complete concurrently; stable ordering keeps generated entry hashes
  // and compressed startup budgets reproducible across identical builds.
  return new Map([...tags].sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0))
}

/**
 * Generates a side-effect virtual module that registers app components used
 * inside rendered markdown bodies.
 */
export async function generateContentComponentsCode(
  componentsDir: string,
  contentDir: string,
  ssr = true,
  integrations: import('../../types/config.js').CerAppIntegration[] = [],
  policies: Record<string, 'load' | 'visible' | 'none'> = {},
): Promise<string> {
  const [manifest, markdownTags] = await Promise.all([
    buildComponentManifest(componentsDir),
    collectMarkdownTags(contentDir),
  ])

  const resolveTag = (tag: string) => manifest.get(tag) ?? integrations.map((i) => i.componentResolver?.(tag)).find(Boolean)
  const entries = [...markdownTags].map(([path, tags]) => [path, [...tags].filter((tag) => resolveTag(tag))] as const)
  const tags = [...new Set(entries.flatMap(([, tags]) => tags))].sort()
  if (ssr && !tags.length) return emptyModule()
  if (ssr) return tags.map((tag) => `import ${JSON.stringify(resolveTag(tag))}`).join('\n') + '\nexport {}\n'
  const modules = tags.map((tag) => `${JSON.stringify(tag)}: () => import(${JSON.stringify(resolveTag(tag))})`).join(',\n')
  return `// AUTO-GENERATED: each document imports only its content components.
const modules = { ${modules} }
const paths = ${JSON.stringify(Object.fromEntries(entries))}
const policies = ${JSON.stringify(policies)}
const pending = new Map()
let cleanups = []
function load(tag) {
  if (!pending.has(tag)) pending.set(tag, modules[tag]().catch((error) => { pending.delete(tag); throw error }))
  return pending.get(tag)
}
function hosts(tag) {
  const found = []
  function scan(root) { for (const element of root.querySelectorAll('*')) { if (element.localName === tag) found.push(element); if (element.shadowRoot) scan(element.shadowRoot) } }
  scan(document)
  return found
}
export async function loadContentComponents(path, deferVisible = false, data) {
  if (!deferVisible) { cleanups.forEach((cleanup) => cleanup()); cleanups = [] }
  const selected = new Set(paths[new URL(path, 'http://cer.local').pathname.replace(/\\/+$/, '') || '/'] ?? [])
  const visited = new WeakSet()
  function visit(value) {
    if (!value || typeof value !== 'object' || visited.has(value)) return
    visited.add(value)
    if (typeof value._path === 'string') (paths[value._path] ?? []).forEach((tag) => selected.add(tag))
    for (const child of Object.values(value)) if (typeof child === 'object') visit(child)
  }
  visit(data)
  // A hydrate-none page omits its full loader payload. Discover rendered hosts
  // as well, so islands in a loader-selected document still get their imports.
  if (deferVisible) {
    function scan(root) {
      for (const element of root.querySelectorAll('*')) {
        if (modules[element.localName]) selected.add(element.localName)
        if (element.shadowRoot) scan(element.shadowRoot)
      }
    }
    scan(document)
  }
  const tags = [...selected]
  await Promise.all(tags.map(async (tag) => {
    if (deferVisible && policies[tag] === 'none') return
    if (deferVisible && policies[tag] === 'visible' && typeof IntersectionObserver === 'function') {
      const elements = hosts(tag)
      if (!elements.length) return
      const cleanup = () => {
        observer.disconnect()
        document.removeEventListener('click', activate, true)
        document.removeEventListener('keydown', activate, true)
      }
      const begin = () => load(tag).then(() => {
        elements.forEach((element) => element.dispatchEvent(new Event('pointerdown', { bubbles: true, composed: true })))
      })
      const observer = new IntersectionObserver((entries) => {
        if (entries.some((entry) => entry.isIntersecting && entry.target.isConnected)) {
          void begin().then(() => observer.disconnect()).catch((error) => console.error('[cer-app] Content module failed:', error))
        }
      }, { rootMargin: '160px' })
      elements.forEach((element) => observer.observe(element))
      const activate = (event) => {
        if (event.__cerContentReplay || (event.type === 'keydown' && (event.altKey || event.ctrlKey || event.metaKey || event.isComposing))) return
        const path = event.composedPath(), host = path.find((node) => elements.includes(node))
        if (!host || host.hasAttribute('data-cer-hydrated') || path.some((node) => node?.localName === 'a' && node.hasAttribute('href'))) return
        if (event.type === 'keydown' && !['ArrowLeft', 'ArrowRight', 'Home', 'End', 'Enter', ' '].includes(event.key)) return
        event.preventDefault(); event.stopImmediatePropagation()
        const target = path[0]
        const replay = (finished = true) => {
          if (finished) cleanup()
          if (!target?.isConnected) return
          const init = { bubbles: true, composed: true, cancelable: true }
          const clone = event.type === 'keydown' ? new KeyboardEvent(event.type, { ...init, key: event.key, code: event.code }) : new MouseEvent(event.type, init)
          Object.defineProperty(clone, '__cerContentReplay', { value: true })
          target.dispatchEvent(clone)
        }
        void begin().then(() => new Promise((resolve) => {
          if (host.hasAttribute('data-cer-hydrated')) { resolve(); return }
          const ready = new MutationObserver(() => { if (host.hasAttribute('data-cer-hydrated')) { ready.disconnect(); resolve() } })
          ready.observe(host, { attributes: true, attributeFilter: ['data-cer-hydrated'] })
          setTimeout(() => { ready.disconnect(); resolve() }, 1500)
        })).then(() => replay(), (error) => { console.error('[cer-app] Content activation failed:', error); replay(false) })
      }
      document.addEventListener('click', activate, true)
      document.addEventListener('keydown', activate, true)
      cleanups.push(cleanup)
      return
    }
    await load(tag)
  }))
}
`
}
