import { extractComponentRegistrations, extractTemplateTagNames } from '@jasonshimmy/custom-elements-runtime/vite-plugin'
import { existsSync, readFileSync } from 'node:fs'
import { parseContentFileAsync } from '../content/parser.js'
import { scanContentFiles } from '../content/scanner.js'
import { scanDirectory } from '../scanner.js'

function emptyModule(): string {
  return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport {}\n`
}

async function buildComponentManifest(componentsDir: string): Promise<Map<string, string>> {
  const manifest = new Map<string, string>()
  if (!existsSync(componentsDir)) return manifest

  const files = await scanDirectory('**/*.ts', componentsDir)
  for (const file of files) {
    try {
      const source = readFileSync(file, 'utf-8')
      for (const tag of extractComponentRegistrations(source)) {
        manifest.set(tag, file)
      }
    } catch {
      // Skip unreadable files.
    }
  }

  return manifest
}

async function collectMarkdownTags(contentDir: string): Promise<Set<string>> {
  const tags = new Set<string>()
  if (!existsSync(contentDir)) return tags

  const files = await scanContentFiles(contentDir)
  const markdownFiles = files.filter((file) => file.ext === 'md')

  await Promise.all(
    markdownFiles.map(async (file) => {
      try {
        const item = await parseContentFileAsync(file, contentDir)
        for (const tag of extractTemplateTagNames(item.body)) {
          tags.add(tag)
        }
      } catch (err) {
        console.warn(
          `[cer-app] Skipping content file (parse error): ${file.filePath}\n  ${(err as Error).message}`,
        )
      }
    }),
  )

  return tags
}

/**
 * Generates a side-effect virtual module that registers app components used
 * inside rendered markdown bodies.
 */
export async function generateContentComponentsCode(
  componentsDir: string,
  contentDir: string,
): Promise<string> {
  const [manifest, markdownTags] = await Promise.all([
    buildComponentManifest(componentsDir),
    collectMarkdownTags(contentDir),
  ])

  const imports = [...markdownTags]
    .sort()
    .map((tag) => manifest.get(tag))
    .filter((file): file is string => typeof file === 'string')

  if (imports.length === 0) return emptyModule()

  const lines = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']
  for (const file of imports) {
    lines.push(`import ${JSON.stringify(file)}`)
  }
  lines.push('')
  lines.push('export {}')
  lines.push('')
  return lines.join('\n')
}