import { existsSync } from 'node:fs'
import { join } from 'pathe'

/**
 * Generates the virtual:cer-error module code.
 *
 * If app/error.ts exists the module exports:
 *   hasError = true
 *   errorTag  = 'page-error'
 *
 * The page-error component receives an `error` attribute (stringified message)
 * and a `reset` attribute (set to "true" to signal the reset handler).
 * The bootstrap wires `resetError()` as a global so the component can call it.
 */
export async function generateErrorCode(srcDir: string): Promise<string> {
  const errorFile = join(srcDir, 'error.ts')

  if (!existsSync(errorFile)) {
    return [
      '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
      'export const hasError = false',
      'export const errorTag = null',
      '',
    ].join('\n')
  }

  return [
    '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
    `import ${JSON.stringify(errorFile)}`,
    'export const hasError = true',
    "export const errorTag = 'page-error'",
    '',
  ].join('\n')
}
