import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'
import { fileToLayoutName, fileToLayoutTagName } from '../path-utils.js'

/**
 * Generates the virtual:cer-layouts module code.
 * Scans app/layouts/ and produces a layouts map.
 */
export async function generateLayoutsCode(layoutsDir: string): Promise<string> {
  if (!existsSync(layoutsDir)) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const layouts = {}\nexport default layouts\n`
  }

  const files = await scanDirectory('**/*.ts', layoutsDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const layouts = {}\nexport default layouts\n`
  }

  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  // Side-effect imports to register the layout custom elements
  for (const file of files) {
    lines.push(`import ${JSON.stringify(file)}`)
  }

  lines.push('')
  lines.push('export const layouts = {')

  for (const file of files) {
    const name = fileToLayoutName(file, layoutsDir)
    const tagName = fileToLayoutTagName(file, layoutsDir)
    lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(tagName)},`)
  }

  lines.push('}')
  lines.push('export default layouts')
  lines.push('')

  return lines.join('\n')
}
