import { existsSync } from 'node:fs'
import { join } from 'pathe'
import { scanDirectory } from '../scanner.js'

/**
 * Generates the virtual:cer-loading module code.
 *
 * If app/loading.ts exists the module exports:
 *   hasLoading = true
 *   loadingTag  = 'page-loading'
 *
 * Otherwise both are falsy so the bootstrap skips the loading indicator.
 */
export async function generateLoadingCode(srcDir: string): Promise<string> {
  const loadingFile = join(srcDir, 'loading.ts')

  if (!existsSync(loadingFile)) {
    return [
      '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
      'export const hasLoading = false',
      'export const loadingTag = null',
      '',
    ].join('\n')
  }

  return [
    '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
    `import ${JSON.stringify(loadingFile)}`,
    'export const hasLoading = true',
    "export const loadingTag = 'page-loading'",
    '',
  ].join('\n')
}
