import { existsSync } from 'node:fs'
import { basename } from 'pathe'
import { scanDirectory } from '../scanner.js'

/**
 * Generates the virtual:cer-middleware module code.
 * Scans app/middleware/ and produces a named map of middleware functions.
 */
export async function generateMiddlewareCode(middlewareDir: string): Promise<string> {
  if (!existsSync(middlewareDir)) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const middleware = {}\nexport default middleware\n`
  }

  const files = await scanDirectory('**/*.ts', middlewareDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const middleware = {}\nexport default middleware\n`
  }

  const lines: string[] = ['// AUTO-GENERATED by vite-plugin-cer-app', '']

  const entries: Array<{ alias: string; name: string }> = []

  for (const file of files) {
    // Key is the filename without extension
    const name = basename(file).replace(/\.[jt]s$/, '')
    // Create a safe JS identifier
    const alias = `_m_${name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1')}`
    entries.push({ alias, name })
    lines.push(`import ${alias} from ${JSON.stringify(file)}`)
  }

  lines.push('')
  lines.push('export const middleware = {')

  for (const { alias, name } of entries) {
    lines.push(`  ${JSON.stringify(name)}: ${alias},`)
  }

  lines.push('}')
  lines.push('export default middleware')
  lines.push('')

  return lines.join('\n')
}
