import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'
import { sortPluginFiles } from '../path-utils.js'

/**
 * Generates the virtual:cer-plugins module code.
 * Scans app/plugins/ and produces an ordered array of plugin imports.
 */
export async function generatePluginsCode(pluginsDir: string): Promise<string> {
  if (!existsSync(pluginsDir)) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const plugins = []\nexport default plugins\n`
  }

  const files = await scanDirectory('**/*.ts', pluginsDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const plugins = []\nexport default plugins\n`
  }

  const sorted = sortPluginFiles(files)
  const lines: string[] = ['// AUTO-GENERATED by vite-plugin-cer-app', '']

  const aliases: string[] = []
  sorted.forEach((file, i) => {
    const alias = `_p${i}`
    aliases.push(alias)
    lines.push(`import ${alias} from ${JSON.stringify(file)}`)
  })

  lines.push('')
  lines.push(`export const plugins = [${aliases.join(', ')}]`)
  lines.push('export default plugins')
  lines.push('')

  return lines.join('\n')
}
