import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'
import { sortPluginFiles } from '../path-utils.js'

/**
 * Generates the virtual:cer-plugins module code.
 * Scans app/plugins/ and produces an ordered array of plugin imports.
 *
 * @param pluginsDir - Absolute path to app/plugins/
 * @param serverSafeOnly - When true, excludes files ending in `.client.ts`.
 *   These are client-only plugins (CSS injections, browser component libraries,
 *   etc.) that must not be imported in the SSR server entry. Naming convention:
 *   `app/plugins/my-plugin.client.ts` → excluded from the server bundle.
 */
export async function generatePluginsCode(pluginsDir: string, serverSafeOnly = false): Promise<string> {
  if (!existsSync(pluginsDir)) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const plugins = []\nexport default plugins\n`
  }

  const files = await scanDirectory('**/*.ts', pluginsDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const plugins = []\nexport default plugins\n`
  }

  const sorted = sortPluginFiles(files)
  // In server-safe mode, exclude `.client.ts` plugins — they are browser-only
  // (CSS imports, client component libraries, etc.) and must not be loaded
  // server-side. Rename the file to `*.client.ts` to mark it as client-only.
  const filtered = serverSafeOnly ? sorted.filter(f => !f.endsWith('.client.ts')) : sorted
  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  const aliases: string[] = []
  filtered.forEach((file, i) => {
    const alias = `_p${i}`
    aliases.push(alias)
    lines.push(`import ${alias} from ${JSON.stringify(file)}`)
  })

  lines.push('')
  lines.push(`export const plugins = [${aliases.join(', ')}]`)
  lines.push('export default plugins')
  lines.push('')

  return lines.join('\n')
}
