import { existsSync } from 'node:fs'
import { basename } from 'node:path'
import { readFile } from 'node:fs/promises'
import { scanDirectory } from '../scanner.js'
import { buildRouteEntry, sortRoutes } from '../path-utils.js'

/**
 * Extracts the middleware array from a page file's source code without
 * importing the module. Handles both single-quoted and double-quoted strings.
 *
 * Matches patterns like:
 *   middleware: ['auth', 'admin']
 *   middleware: ["auth"]
 */
function extractMiddleware(source: string): string[] {
  const match = source.match(/middleware\s*:\s*\[([^\]]*)\]/)
  if (!match) return []
  const inner = match[1]
  const names = inner.match(/['"]([^'"]+)['"]/g)
  if (!names) return []
  return names.map((s) => s.replace(/['"]/g, ''))
}

/**
 * Extracts the layout name from a page file's source code without importing
 * the module. Returns null when no layout is declared (caller defaults to
 * 'default').
 *
 * Matches patterns like:
 *   layout: 'minimal'
 *   layout: "admin"
 */
function extractLayout(source: string): string | null {
  const match = source.match(/layout\s*:\s*['"]([^'"]+)['"]/)
  return match ? match[1] : null
}

/**
 * Generates the virtual:cer-routes module code.
 *
 * Each page module is loaded lazily via a `load()` function — a dynamic
 * import that both registers the custom element (side-effect of component())
 * and returns the tag name as `default`.  This lets Vite split each page into
 * its own chunk so only the routes the user actually visits are downloaded.
 *
 * Middleware names and layout names are extracted at build time with a
 * lightweight regex so no eager import is needed.
 *
 * Special conventions:
 *   app/pages/404.ts  →  path "/:all*"  (catch-all not-found page)
 */
export async function generateRoutesCode(pagesDir: string): Promise<string> {
  if (!existsSync(pagesDir)) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nconst routes = []\nexport default routes\n`
  }

  const files = await scanDirectory('**/*.ts', pagesDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nconst routes = []\nexport default routes\n`
  }

  const rawEntries = files.map((f) => {
    const entry = buildRouteEntry(f, pagesDir)
    // 404.ts convention: treat as catch-all not-found route
    if (basename(f) === '404.ts') {
      return { ...entry, routePath: '/:all*', tagName: 'page-404', isDynamic: true, isCatchAll: true }
    }
    return entry
  })

  // Deduplicate by routePath — keep the first occurrence after sorting to
  // avoid "Duplicate route path detected" warnings (e.g. when both 404.ts
  // and [...all].ts resolve to the same /:all* catch-all route).
  const seen = new Set<string>()
  const entries = rawEntries.filter((e) => {
    if (seen.has(e.routePath)) return false
    seen.add(e.routePath)
    return true
  })

  const sorted = sortRoutes(entries)

  // Read each file's source once to extract static metadata (middleware + layout)
  // without eagerly importing the module.
  const metaPerEntry: Array<{ middleware: string[]; layout: string | null }> = await Promise.all(
    sorted.map(async (entry) => {
      try {
        const src = await readFile(entry.filePath, 'utf-8')
        return { middleware: extractMiddleware(src), layout: extractLayout(src) }
      } catch {
        return { middleware: [], layout: null }
      }
    }),
  )

  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  // Build routes array with lazy load() functions for code splitting.
  const routeItems = sorted.map((entry, i) => {
    const { middleware: mw, layout } = metaPerEntry[i]
    const filePath = JSON.stringify(entry.filePath)
    const tagName = JSON.stringify(entry.tagName)
    const routePath = JSON.stringify(entry.routePath)

    // The load() function dynamically imports the page module which:
    //   1. Runs component() as a side effect, registering the custom element
    //   2. Returns the tag name string as `default` so the router knows what to render
    //   3. Forwards the optional `loader` export for SSR data hydration
    const loadFn = `() => import(${filePath}).then(mod => ({ default: ${tagName}, loader: mod.loader ?? null }))`

    // Build meta object — only emit fields that are set
    const metaFields: string[] = []
    if (layout !== null) metaFields.push(`layout: ${JSON.stringify(layout)}`)
    const metaStr = metaFields.length > 0 ? `    meta: { ${metaFields.join(', ')} },\n` : ''

    if (mw.length === 0) {
      return (
        `  {\n` +
        `    path: ${routePath},\n` +
        `    load: ${loadFn},\n` +
        metaStr +
        `  }`
      )
    }

    // Inline the middleware names as a literal array (extracted at build time)
    // so we never need to eagerly import the page module just to read meta.
    const mwLiteral = JSON.stringify(mw)
    return (
      `  {\n` +
      `    path: ${routePath},\n` +
      `    load: ${loadFn},\n` +
      metaStr +
      `    beforeEnter: async (to, from) => {\n` +
      `      const { middleware } = await import('virtual:cer-middleware')\n` +
      `      for (const name of ${mwLiteral}) {\n` +
      `        const handler = middleware[name]\n` +
      `        if (typeof handler !== 'function') continue\n` +
      `        const result = await new Promise((resolve) => handler(to, from, resolve))\n` +
      `        if (typeof result === 'string') return result\n` +
      `        if (result === false) return false\n` +
      `      }\n` +
      `      return true\n` +
      `    },\n` +
      `  }`
    )
  })

  lines.push('const routes = [')
  lines.push(routeItems.join(',\n'))
  lines.push(']')
  lines.push('')
  lines.push('export default routes')
  lines.push('')

  return lines.join('\n')
}
