import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'
import { fileToRoutePath } from '../path-utils.js'

/**
 * Generates the virtual:cer-server-api module code.
 * Scans server/api/ and produces an apiRoutes array with path and handlers.
 */
export async function generateServerApiCode(serverApiDir: string): Promise<string> {
  if (!existsSync(serverApiDir)) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const apiRoutes = []\nexport default apiRoutes\n`
  }

  const files = await scanDirectory('**/*.ts', serverApiDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by vite-plugin-cer-app\nexport const apiRoutes = []\nexport default apiRoutes\n`
  }

  const lines: string[] = ['// AUTO-GENERATED by vite-plugin-cer-app', '']

  const entries: Array<{ alias: string; apiPath: string }> = []

  for (const file of files) {
    // Compute route path using same rules, prefixed with /api/
    const routeSuffix = fileToRoutePath(file, serverApiDir)
    const apiPath = '/api' + (routeSuffix === '/' ? '' : routeSuffix)

    // Create a safe JS identifier from the path
    const safeAlias = '_route' + apiPath
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '')
    const alias = `_route_${safeAlias.replace(/^_route_/, '')}`

    entries.push({ alias, apiPath })
    lines.push(`import * as ${alias} from ${JSON.stringify(file)}`)
  }

  lines.push('')
  lines.push('export const apiRoutes = [')

  for (const { alias, apiPath } of entries) {
    lines.push(`  { path: ${JSON.stringify(apiPath)}, handlers: ${alias} },`)
  }

  lines.push(']')
  lines.push('export default apiRoutes')
  lines.push('')

  return lines.join('\n')
}
