import { existsSync } from 'node:fs'
import { scanDirectory } from '../scanner.js'
import { fileToRoutePath } from '../path-utils.js'
import type { AuthConfig } from '../../types/config.js'

/**
 * Generates the virtual:cer-server-api module code.
 * Scans server/api/ and produces an apiRoutes array with path and handlers.
 * When `authConfig` is provided, prepends OAuth initiate / callback / logout routes.
 */
export async function generateServerApiCode(serverApiDir: string, authConfig?: AuthConfig | null): Promise<string> {
  const hasOAuth = !!(authConfig?.providers && Object.keys(authConfig.providers).length > 0)
  const files = existsSync(serverApiDir) ? await scanDirectory('**/*.ts', serverApiDir) : []

  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  // ── OAuth routes ────────────────────────────────────────────────────────────
  // Injected ahead of user routes so auth paths are never shadowed.
  if (hasOAuth) {
    // Serialise only the fields the handler needs at runtime.
    // clientSecret is server-only (this module is never in the client bundle).
    const serialisedCfg = JSON.stringify({
      providers: Object.fromEntries(
        Object.entries(authConfig!.providers!).map(([name, cfg]) => [
          name,
          cfg
            ? {
                clientId: cfg.clientId,
                clientSecret: cfg.clientSecret,
                scope: cfg.scope,
                authorizationUrl: cfg.authorizationUrl,
                tokenUrl: cfg.tokenUrl,
                userInfoUrl: cfg.userInfoUrl,
              }
            : undefined,
        ]),
      ),
      redirectAfterLogin: authConfig!.redirectAfterLogin ?? '/',
      redirectAfterLogout: authConfig!.redirectAfterLogout ?? '/',
      sessionKey: authConfig!.sessionKey ?? 'auth',
    })

    lines.push(`import { handleOAuthInitiate, handleOAuthCallback, handleOAuthLogout } from '@jasonshimmy/vite-plugin-cer-app/oauth'`)
    lines.push(`const _authCfg = ${serialisedCfg}`)
    lines.push('')
  }

  // ── User API routes ─────────────────────────────────────────────────────────
  const entries: Array<{ alias: string; apiPath: string }> = []

  for (const file of files) {
    const routeSuffix = fileToRoutePath(file, serverApiDir)
    const apiPath = '/api' + (routeSuffix === '/' ? '' : routeSuffix)

    const safeAlias = '_route' + apiPath
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '')
    const alias = `_route_${safeAlias.replace(/^_route_/, '')}`

    entries.push({ alias, apiPath })
    lines.push(`import * as ${alias} from ${JSON.stringify(file)}`)
  }

  if (entries.length > 0) lines.push('')

  lines.push('export const apiRoutes = [')

  // OAuth routes come first
  if (hasOAuth) {
    lines.push(`  { path: '/api/auth/:provider', handlers: { get: (req, res) => handleOAuthInitiate(req, res, req.params?.provider ?? '', _authCfg) } },`)
    lines.push(`  { path: '/api/auth/callback/:provider', handlers: { get: (req, res) => handleOAuthCallback(req, res, req.params?.provider ?? '', _authCfg) } },`)
    lines.push(`  { path: '/api/auth/logout', handlers: { get: (req, res) => handleOAuthLogout(req, res, _authCfg) } },`)
  }

  for (const { alias, apiPath } of entries) {
    lines.push(`  { path: ${JSON.stringify(apiPath)}, handlers: ${alias} },`)
  }

  lines.push(']')
  lines.push('export default apiRoutes')
  lines.push('')

  return lines.join('\n')
}
