import { existsSync } from 'node:fs'
import { basename } from 'pathe'
import { scanDirectory } from '../scanner.js'

/**
 * Generates the virtual:cer-server-middleware module code.
 * Scans server/middleware/ and produces an array of server middleware handlers.
 */
export async function generateServerMiddlewareCode(serverMiddlewareDir: string): Promise<string> {
  if (!existsSync(serverMiddlewareDir)) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const serverMiddleware = []\nexport default serverMiddleware\n`
  }

  const files = await scanDirectory('**/*.ts', serverMiddlewareDir)

  if (files.length === 0) {
    return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport const serverMiddleware = []\nexport default serverMiddleware\n`
  }

  // Sort alphabetically so middleware runs in a deterministic order
  const sorted = [...files].sort()

  const lines: string[] = ['// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app', '']

  const entries: Array<{ alias: string; name: string }> = []

  for (const file of sorted) {
    const name = basename(file).replace(/\.[jt]s$/, '')
    const alias = `_sm_${name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1')}`
    entries.push({ alias, name })
    lines.push(`import ${alias} from ${JSON.stringify(file)}`)
  }

  lines.push('')
  lines.push('export const serverMiddleware = [')
  for (const { alias, name } of entries) {
    lines.push(`  { name: ${JSON.stringify(name)}, handler: ${alias}?.default ?? ${alias} },`)
  }
  lines.push(']')
  lines.push('export default serverMiddleware')
  lines.push('')

  return lines.join('\n')
}
