/**
 * Template string for `.cer/app.ts` — the framework client entry point.
 *
 * Always written to `.cer/app.ts` on every dev/build so consumers
 * automatically receive the latest bootstrap code on plugin update.
 * This file is gitignored and should never be edited directly.
 */
export const APP_ENTRY_TEMPLATE = `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app — do not edit.
// Regenerated automatically on every dev server start and build.

import '@jasonshimmy/custom-elements-runtime/css'
import 'virtual:cer-jit-css'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import { hasLoading, loadingTag } from 'virtual:cer-loading'
import { hasError, errorTag } from 'virtual:cer-error'
import { runtimeConfig } from 'virtual:cer-app-config'
import {
  component,
  ref,
  provide,
  useOnConnected,
  useOnDisconnected,
  registerBuiltinComponents,
} from '@jasonshimmy/custom-elements-runtime'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { enableJITCSS } from '@jasonshimmy/custom-elements-runtime/jit-css'
import { initRuntimeConfig } from '@jasonshimmy/vite-plugin-cer-app/composables'

registerBuiltinComponents()
enableJITCSS()
initRuntimeConfig(runtimeConfig)

const router = initRouter({ routes })

// Expose the router globally so useRoute() and navigateTo() can access it
// from any composable without circular imports.
;(globalThis).__cerRouter = router

// ─── Page loader state ───────────────────────────────────────────────────────

// Holds the pre-loaded page tag and loader-derived attrs for the current route.
// Set by _loadPageForPath before every navigation so cer-layout-view can render
// the page element directly with the correct attributes (enabling useProps()).
let _currentPageTag = null
let _currentPageAttrs = {}
// The pathname this tag was loaded for — used to detect router-internal
// redirects (e.g. middleware returning '/login') so cer-layout-view falls
// back to <router-view> when the current route differs from what was pre-loaded.
let _currentPagePath = null

// Pre-loads the page module for \`path\`, calls its loader if present, and
// stores the results so cer-layout-view can pass them as element attributes.
async function _loadPageForPath(path) {
  try {
    const url = new URL(path, 'http://x')
    const query = Object.fromEntries(url.searchParams)
    const matched = router.matchRoute(url.pathname)
    const route = matched?.route
    if (!route?.load) {
      _currentPageTag = null
      _currentPageAttrs = {}
      _currentPagePath = url.pathname
      return
    }
    const mod = await route.load()
    _currentPageTag = mod.default ?? null
    _currentPagePath = url.pathname
    const params = matched.params ?? {}
    let loaderAttrs = { ...params }
    if (typeof mod.loader === 'function') {
      try {
        const data = await mod.loader({ params, query })
        if (data !== undefined && data !== null) {
          // Make loader data available via usePageData() for this navigation.
          ;(globalThis).__CER_DATA__ = data
          // Merge primitive values as element attributes so useProps() works.
          const primitives = Object.fromEntries(
            Object.entries(data).filter(([, v]) => v !== null && v !== undefined && typeof v !== 'object' && typeof v !== 'function')
          )
          loaderAttrs = { ...loaderAttrs, ...primitives }
        }
      } catch (err) {
        // Loader errors are surfaced through currentError so the error boundary
        // (app/error.ts) can display a meaningful message — consistent with how
        // the server-side handler behaves when a loader throws.
        currentError.value = err instanceof Error ? err.message : String(err)
      }
    }
    _currentPageAttrs = loaderAttrs
  } catch {
    _currentPageTag = null
    _currentPageAttrs = {}
    _currentPagePath = null
  }
}

// ─── Navigation state ────────────────────────────────────────────────────────

const isNavigating = ref(false)
const currentError = ref(null)

const resetError = () => {
  currentError.value = null
  void router.replace(router.getCurrent().path)
}
;(globalThis).resetError = resetError

const _push = router.push.bind(router)
const _replace = router.replace.bind(router)

router.push = async (path) => {
  isNavigating.value = true
  currentError.value = null
  try {
    // Clear stale loader data from the previous route before loading the new one.
    // If the new route has no loader, __CER_DATA__ stays undefined so usePageData()
    // correctly returns null instead of leaking the previous page's data.
    delete (globalThis).__CER_DATA__
    await _loadPageForPath(path)
    await _push(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    isNavigating.value = false
  }
}

router.replace = async (path) => {
  isNavigating.value = true
  currentError.value = null
  try {
    // Clear stale loader data from the previous route before loading the new one.
    delete (globalThis).__CER_DATA__
    await _loadPageForPath(path)
    await _replace(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    isNavigating.value = false
  }
}

// ─── Plugins ─────────────────────────────────────────────────────────────────

// Collect plugin-provided values so cer-layout-view can forward them into
// the component context tree via the real provide() hook (which inject() walks).
// Declared BEFORE component('cer-layout-view') to avoid a temporal dead zone
// ReferenceError: customElements.define() upgrades existing DOM elements
// synchronously, calling the render function immediately.
const _pluginProvides = new Map()
// Expose plugin provides globally so page components can read them synchronously
// regardless of render order.
;(globalThis).__cerPluginProvides = _pluginProvides

// ─── <cer-layout-view> ───────────────────────────────────────────────────────

// True until the initial page module has loaded and _replace has been called.
// While true, cer-layout-view renders a <slot> so the SSR/SSG pre-rendered
// light-DOM content stays visible and no FOUC occurs during the hydration gap.
// Declared here (before component()) because customElements.define() upgrades
// existing DOM elements synchronously, so the render function reads this ref
// on the very first call — before _doHydrate has a chance to run.
const _cerHydrating = ref(true)

component('cer-layout-view', () => {
  // Forward plugin-provided values into the component context so inject() in
  // any descendant component can resolve them by walking up the DOM tree.
  for (const [key, value] of _pluginProvides) {
    provide(key, value)
  }

  const current = ref(router.getCurrent())
  let unsub

  useOnConnected(() => {
    // Any router navigation (including the initial _replace in _doHydrate) will
    // arrive here. If we are still in the hydration gap when a navigation fires
    // (e.g. a redirect or user interaction before _doHydrate finishes), drop the
    // slot immediately so the live render takes over.
    unsub = router.subscribe((s) => {
      if (_cerHydrating.value) _cerHydrating.value = false
      current.value = s
    })
  })
  useOnDisconnected(() => { unsub?.(); unsub = undefined })

  // While the initial page module is being loaded, keep the SSR/SSG
  // pre-rendered light-DOM content visible by forwarding it through a <slot>.
  // This prevents the intermediate blank state that occurs when the shadow DOM
  // renders layout-default with an empty <router-view> before the page chunk
  // has arrived. In SPA mode (no pre-rendered content) the slot is empty, which
  // is no worse than the current router-view behaviour.
  if (_cerHydrating.value) {
    return { tag: 'slot', props: {}, children: [] }
  }

  const matched = router.matchRoute(current.value.path)
  const routeMeta = matched?.route?.meta

  if (currentError.value !== null) {
    const routeErrorTag = routeMeta?.errorTag ?? null
    const effectiveErrorTag = routeErrorTag ?? (hasError ? errorTag : null)
    if (effectiveErrorTag) {
      return { tag: effectiveErrorTag, props: { attrs: { error: String(currentError.value) } }, children: [] }
    }
    return { tag: 'div', props: { attrs: { style: 'padding:2rem;font-family:monospace' } }, children: String(currentError.value) }
  }

  if (isNavigating.value && hasLoading && loadingTag) {
    return { tag: loadingTag, props: {}, children: [] }
  }

  // Render the page component directly when a pre-loaded tag is available AND
  // the loaded path matches the current route.  The path guard detects
  // router-internal redirects (e.g. middleware returning '/login'): when the
  // router redirects to a different path, _currentPagePath won't match
  // current.value.path and we fall back to <router-view> so the correct page
  // is rendered without stale pre-loaded state.
  const _useDirectRender = _currentPageTag && _currentPagePath === current.value.path
  const pageVnode = _useDirectRender
    ? { tag: _currentPageTag, props: { attrs: _currentPageAttrs }, children: [] }
    : { tag: 'router-view', props: {}, children: [] }

  // Support nested layout chains: meta.layoutChain = ['default', 'admin']
  // renders <layout-default><layout-admin><page/></layout-admin></layout-default>
  const chain = routeMeta?.layoutChain
    ? routeMeta.layoutChain
    : [routeMeta?.layout ?? 'default']

  // Build nested vnodes from innermost to outermost.
  let vnode = pageVnode
  for (let i = chain.length - 1; i >= 0; i--) {
    const tag = layouts[chain[i]]
    if (tag) vnode = { tag, props: {}, children: [vnode] }
  }
  return vnode
})

for (const plugin of plugins) {
  if (plugin && typeof plugin.setup === 'function') {
    await plugin.setup({
      router,
      provide: (key, value) => { _pluginProvides.set(key, value) },
      config: {},
    })
  }
}

// ─── Pre-load initial route + hydration strategy ─────────────────────────────
// Download the current page's route chunk AFTER plugins run so that
// cer-layout-view's first render (which calls provide()) completes before
// page components are defined and their renders are scheduled. This ensures
// inject() in child components can find values stored by provide().
//
// meta.hydrate controls WHEN the initial page activates:
//   'load'    — immediately (default)
//   'idle'    — deferred until requestIdleCallback (browser idle)
//   'visible' — deferred until cer-layout-view enters the viewport
//   'none'    — never: SSR HTML stays as-is, no JS activation

if (typeof window !== 'undefined') {
  const _initMatch = router.matchRoute(window.location.pathname)
  const _hydrateStrategy = _initMatch?.route?.meta?.hydrate ?? 'load'

  if (_hydrateStrategy === 'none') {
    // Static HTML only — leave SSR output untouched, clean up data immediately.
    delete (globalThis).__CER_DATA__
  } else {
    const _doHydrate = async () => {
      const _initPath = window.location.pathname + window.location.search + window.location.hash
      // Pre-load the page module and run the loader so cer-layout-view renders
      // the page tag directly with loader attrs (enables useProps() on hydration).
      await _loadPageForPath(_initPath)
      // Only activate the initial route if the URL hasn't changed while we were
      // loading the module asynchronously (e.g. a test or plugin navigated away
      // before _doHydrate finished).  Calling _replace with a stale path would
      // override any navigation that happened during the async gap.
      const _currentPath = window.location.pathname + window.location.search + window.location.hash
      // Drop the hydration slot cover unconditionally: the page module is loaded
      // and cer-layout-view must switch from the <slot> to live rendering whether
      // or not a redirect changed the path during loading.
      _cerHydrating.value = false
      if (_currentPath === _initPath) {
        // Use the original (unwrapped) replace so isNavigating stays false during
        // the initial paint — the loading component must not flash over pre-rendered content.
        await _replace(_initPath)
      }
      // Clear SSR loader data after initial navigation so subsequent client-side
      // navigations don't accidentally reuse stale server data.
      delete (globalThis).__CER_DATA__
    }

    if (_hydrateStrategy === 'idle') {
      // Defer until the browser has finished higher-priority work.
      if (typeof requestIdleCallback !== 'undefined') {
        requestIdleCallback(() => { void _doHydrate() })
      } else {
        // Safari / older environments fallback.
        setTimeout(() => { void _doHydrate() }, 1)
      }
    } else if (_hydrateStrategy === 'visible') {
      // Defer until cer-layout-view (or body as fallback) enters the viewport.
      const _el = document.querySelector('cer-layout-view') ?? document.body
      const _io = new IntersectionObserver(([entry]) => {
        if (entry.isIntersecting) { _io.disconnect(); void _doHydrate() }
      })
      _io.observe(_el)
    } else {
      // 'load' — hydrate immediately (default behaviour).
      await _doHydrate()
    }
  }
}

export { router }
`
