/**
 * Generates the `.cer/app.ts` framework client entry point.
 *
 * Always written to `.cer/app.ts` on every dev/build so consumers
 * automatically receive the latest bootstrap code on plugin update.
 * This file is gitignored and should never be edited directly.
 */
export function generateAppEntryTemplate(globalImports: readonly string[] = []): string {
  const integrationImports = [...new Set(globalImports)]
    .map((specifier) => `import '${specifier.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`)
    .join('\n')
  return `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app — do not edit.
// Regenerated automatically on every dev server start and build.

import '@jasonshimmy/custom-elements-runtime/css'
${integrationImports}${integrationImports ? '\n' : ''}import 'virtual:cer-jit-css'
// virtual:cer-jit-init must run before virtual:cer-layouts and virtual:cer-plugins
// so JIT CSS is enabled before those modules upgrade custom elements via
// customElements.define(). Static imports execute depth-first in module order,
// so placing this import here guarantees enableJITCSS() fires first.
import 'virtual:cer-jit-init'
import 'virtual:cer-content-components'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import { hasLoading, loadingTag } from 'virtual:cer-loading'
import { hasError, errorTag } from 'virtual:cer-error'
import { runtimeConfig, appConfig } from 'virtual:cer-app-config'
import {
  component,
  ref,
  provide,
  setDevMode,
  useOnConnected,
  useOnDisconnected,
  registerBuiltinComponents,
} from '@jasonshimmy/custom-elements-runtime'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { initRuntimeConfig } from '@jasonshimmy/vite-plugin-cer-app/composables'

const _cerProcess = (globalThis).process
const _cerNodeEnv = _cerProcess?.env?.NODE_ENV ?? _cerProcess?.env?.MODE
const _cerRuntimeDev =
  typeof _cerNodeEnv === 'string'
    ? _cerNodeEnv !== 'production'
    : typeof import.meta.env?.DEV === 'boolean'
      ? import.meta.env.DEV
      : typeof import.meta.env?.PROD === 'boolean'
        ? !import.meta.env.PROD
        : typeof import.meta.env?.MODE === 'string'
          ? import.meta.env.MODE !== 'production'
          : false
;(globalThis).__CE_RUNTIME_DEV__ = _cerRuntimeDev

registerBuiltinComponents()
setDevMode(_cerRuntimeDev)
initRuntimeConfig(runtimeConfig)

const router = initRouter({ ...appConfig.router, routes })

// Expose the router globally so useRoute() and navigateTo() can access it
// from any composable without circular imports.
;(globalThis).__cerRouter = router

// ─── Page loader state ───────────────────────────────────────────────────────

// Holds the pre-loaded page tag and loader-derived attrs for the current route.
// Set by _loadPageForPath before every navigation so cer-layout-view can render
// the page element directly with the correct attributes (enabling useProps()).
let _currentPageTag = null
let _currentPageAttrs = {}
// Changes only when a page load successfully publishes. Keying the rendered
// page with this value prevents dynamic/catch-all routes that share one custom
// element tag from retaining loader-backed state from the previous URL.
let _currentPageKey = null
// The pathname this tag was loaded for — used to detect router-internal
// redirects (e.g. middleware returning '/login') so cer-layout-view falls
// back to <router-view> when the current route differs from what was pre-loaded.
let _currentPagePath = null
// The pathname + query whose page data is currently loaded. Browser history
// traversals that change only the fragment must stay on the runtime router's
// lightweight scroll path instead of needlessly re-running the page loader.
let _currentPageLocation = typeof window !== 'undefined'
  ? window.location.pathname + window.location.search
  : null
// Route chunks and loaders may resolve out of order during rapid navigation or
// initial hydration. Only the newest request is allowed to publish page state.
let _pageLoadVersion = 0

function _toLoaderAttrs(data) {
  if (data === undefined || data === null || typeof data !== 'object') return {}
  return Object.fromEntries(
    Object.entries(data).filter(([, v]) => v !== null && v !== undefined && typeof v !== 'object' && typeof v !== 'function')
  )
}

// Pre-loads the page module for \`path\`, calls its loader if present, and
// stores the results so cer-layout-view can pass them as element attributes.
async function _loadPageForPath(path, options = {}) {
  const loadVersion = ++_pageLoadVersion
  try {
    const url = new URL(path, 'http://x')
    const query = Object.fromEntries(url.searchParams)
    const { runLoader = true, initialData } = options ?? {}
    const matched = router.matchRoute(url.pathname)
    const route = matched?.route
    if (!route?.load) {
      if (loadVersion !== _pageLoadVersion) return
      _currentPageTag = null
      _currentPageAttrs = {}
      _currentPageKey = null
      _currentPagePath = url.pathname
      _currentPageLocation = url.pathname + url.search
      return
    }
    const mod = await route.load()
    if (loadVersion !== _pageLoadVersion) return
    const params = matched.params ?? {}
    let loaderAttrs = { ...params }
    let loaderData = initialData
    let hasFreshLoaderData = false
    if (typeof mod.loader === 'function' && runLoader) {
      try {
        const data = await mod.loader({ params, query })
        if (loadVersion !== _pageLoadVersion) return
        if (data !== undefined && data !== null) {
          loaderData = data
          hasFreshLoaderData = true
        }
      } catch (err) {
        if (loadVersion !== _pageLoadVersion) return
        // Loader errors are surfaced through currentError so the error boundary
        // (app/error.ts) can display a meaningful message — consistent with how
        // the server-side handler behaves when a loader throws.
        currentError.value = err instanceof Error ? err.message : String(err)
      }
    }
    // For the very first hydration pass in SSR/SSG we already have the server's
    // loader payload in globalThis.__CER_DATA__ / window.__CER_DATA__. Reuse it
    // instead of re-running the loader on the client, then derive primitive attrs
    // from that payload so useProps() stays consistent with usePageData().
    if (loadVersion !== _pageLoadVersion) return
    loaderAttrs = { ...loaderAttrs, ..._toLoaderAttrs(loaderData) }
    if (hasFreshLoaderData) {
      // Publish loader data only after confirming this is still the newest route.
      ;(globalThis).__CER_DATA__ = loaderData
    }
    _currentPageTag = mod.default ?? null
    _currentPagePath = url.pathname
    _currentPageLocation = url.pathname + url.search
    _currentPageAttrs = loaderAttrs
    _currentPageKey = loadVersion
  } catch {
    if (loadVersion !== _pageLoadVersion) return
    _currentPageTag = null
    _currentPageAttrs = {}
    _currentPageKey = null
    _currentPagePath = null
  }
}

// ─── Navigation state ────────────────────────────────────────────────────────

const isNavigating = ref(false)
const currentError = ref(null)

const resetError = () => {
  currentError.value = null
  void router.replace(router.getCurrent().path)
}
;(globalThis).resetError = resetError

const _push = router.push.bind(router)
const _replace = router.replace.bind(router)
// Captures navigation intent synchronously, before route imports resolve or the
// History API changes the visible URL. Hydration uses this to avoid restoring a
// stale entry page over an already-requested navigation.
let _navigationIntent = 0

router.push = async (path) => {
  const navigationIntent = ++_navigationIntent
  isNavigating.value = true
  currentError.value = null
  // A loading component is an explicit request to replace the current tree
  // while the destination is prepared. Without one, retain an initial
  // SSR/SSG tree until both the loader and router commit are complete. This
  // prevents loader-backed catch-all pages from rendering their not-found
  // state during the temporary gap where __CER_DATA__ is intentionally empty.
  if (hasLoading && loadingTag) _activateClientRouteRendering()
  try {
    // Clear stale loader data from the previous route before loading the new one.
    // If the new route has no loader, __CER_DATA__ stays undefined so usePageData()
    // correctly returns null instead of leaking the previous page's data.
    delete (globalThis).__CER_DATA__
    await _loadPageForPath(path)
    if (navigationIntent !== _navigationIntent) return
    await _push(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    if (navigationIntent === _navigationIntent) {
      _activateClientRouteRendering()
      isNavigating.value = false
    }
  }
}

router.replace = async (path) => {
  const navigationIntent = ++_navigationIntent
  isNavigating.value = true
  currentError.value = null
  if (hasLoading && loadingTag) _activateClientRouteRendering()
  try {
    // Clear stale loader data from the previous route before loading the new one.
    delete (globalThis).__CER_DATA__
    await _loadPageForPath(path)
    if (navigationIntent !== _navigationIntent) return
    await _replace(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    if (navigationIntent === _navigationIntent) {
      _activateClientRouteRendering()
      isNavigating.value = false
    }
  }
}

// The runtime router owns the History API and commits route state on popstate.
// push/replace above can prepare the destination before that commit because the
// app initiated those navigations. Browser Back/Forward bypass those methods,
// so mirror their page-module/data preparation here. The runtime registered its
// popstate listener during initRouter(); its async guard pipeline and this async
// page load can safely proceed together, while isNavigating guarantees a final
// render after the page load publishes its non-reactive tag/attrs bookkeeping.
window.addEventListener('popstate', () => {
  const path = window.location.pathname + window.location.search + window.location.hash
  const pageLocation = window.location.pathname + window.location.search

  // Fragment-only traversal needs no new component or loader data. The runtime
  // still receives the event and synchronizes the route fragment/scroll state.
  if (pageLocation === _currentPageLocation) return

  const navigationIntent = ++_navigationIntent
  isNavigating.value = true
  currentError.value = null
  if (hasLoading && loadingTag) _activateClientRouteRendering()

  void (async () => {
    try {
      delete (globalThis).__CER_DATA__
      await _loadPageForPath(path)
    } catch (err) {
      if (navigationIntent === _navigationIntent) {
        currentError.value = err instanceof Error ? err.message : String(err)
      }
    } finally {
      if (navigationIntent === _navigationIntent) {
        _activateClientRouteRendering()
        isNavigating.value = false
      }
    }
  })()
})

// Make ordinary internal links participate in client-side routing even when
// their owning custom element has not hydrated yet. The listener runs in the
// bubble phase so an upgraded component gets first refusal: handlers such as
// breadcrumbs can call preventDefault() and perform their own navigation.
// composedPath() is required because document-level delegation cannot otherwise
// discover an anchor rendered inside a shadow root.
document.addEventListener('click', (event) => {
  if (
    event.defaultPrevented ||
    event.button !== 0 ||
    event.metaKey ||
    event.ctrlKey ||
    event.shiftKey ||
    event.altKey
  ) return

  const anchor = event.composedPath().find(
    (target) => target instanceof HTMLAnchorElement,
  )
  if (!anchor || anchor.hasAttribute('download')) return
  if (anchor.getAttribute('aria-disabled') === 'true') return

  const target = anchor.getAttribute('target')
  if (target && target.toLowerCase() !== '_self') return

  const href = anchor.getAttribute('href')
  if (!href) return

  let url
  try {
    url = new URL(href, window.location.href)
  } catch {
    return
  }

  if (
    (url.protocol !== 'http:' && url.protocol !== 'https:') ||
    url.origin !== window.location.origin
  ) return

  const navigationPath = url.pathname + url.search + url.hash

  // Same-page anchors do not need a loader or page-tree replacement. Use the
  // underlying runtime router so its configured offset, retries, cancellation,
  // and history state remain consistent with cross-route fragment navigation.
  if (
    url.pathname === window.location.pathname &&
    url.search === window.location.search &&
    url.hash
  ) {
    event.preventDefault()
    void _push(url.pathname + url.search + url.hash)
    return
  }

  event.preventDefault()
  void router.push(navigationPath)
})

// ─── Plugins ─────────────────────────────────────────────────────────────────

// Collect plugin-provided values so cer-layout-view can forward them into
// the component context tree via the real provide() hook (which inject() walks).
// Declared BEFORE component('cer-layout-view') to avoid a temporal dead zone
// ReferenceError: customElements.define() upgrades existing DOM elements
// synchronously, calling the render function immediately.
const _pluginProvides = new Map()
// Expose plugin provides globally so page components can read them synchronously
// regardless of render order.
;(globalThis).__cerPluginProvides = _pluginProvides

// ─── <cer-layout-view> ───────────────────────────────────────────────────────

// True while the upgraded SSR/SSG light DOM is the live application. The slot
// stays active after initial route setup so the framework does not construct a
// second, duplicate component tree. The first real navigation switches to the
// client-rendered route tree and releases the server DOM.
// Declared here (before component()) because customElements.define() upgrades
// existing DOM elements synchronously, so the render function reads this ref
// on the very first call — before _doHydrate has a chance to run.
const _cerHydrating = ref(true)

function _activateClientRouteRendering() {
  if (!_cerHydrating.value) return
  _cerHydrating.value = false

  // The initial SSR tree lives in cer-layout-view's light DOM. Once its slot is
  // no longer used, disconnect it so hidden components, listeners, and reactive
  // state do not remain retained for the lifetime of the application. Queue the
  // cleanup after the reactive render requested above so navigation never
  // exposes a momentarily empty view.
  const host = document.querySelector('cer-layout-view')
  if (host?.childNodes.length) {
    queueMicrotask(() => host.replaceChildren())
  }
}

component('cer-layout-view', () => {
  // Forward plugin-provided values into the component context so inject() in
  // any descendant component can resolve them by walking up the DOM tree.
  for (const [key, value] of _pluginProvides) {
    provide(key, value)
  }

  const current = ref(router.getCurrent())
  let unsub
  let _sawInitialRouteState = false

  useOnConnected(() => {
    // store.subscribe() synchronously pushes the current route once on
    // subscription. That initial callback is not a real navigation and must not
    // tear down the SSR slot before _doHydrate has pre-loaded the page.
    // Later state pushes update the stored route, but the SSR slot is released
    // only by the wrapped push/replace methods on a real client navigation.
    // initRouter's startup guard replay therefore cannot duplicate the tree.
    unsub = router.subscribe((s) => {
      const _isInitialSubscribePush = !_sawInitialRouteState
      _sawInitialRouteState = true
      if (_isInitialSubscribePush) {
        current.value = s
        return
      }
      current.value = s
    })
  })
  useOnDisconnected(() => { unsub?.(); unsub = undefined })

  // While the initial page module is being loaded, keep the SSR/SSG
  // pre-rendered light-DOM content visible by forwarding it through a <slot>.
  // This prevents the intermediate blank state that occurs when the shadow DOM
  // renders layout-default with an empty <router-view> before the page chunk
  // has arrived. In SPA mode (no pre-rendered content) the slot is empty, which
  // is no worse than the current router-view behaviour.
  if (_cerHydrating.value) {
    return { tag: 'slot', props: {}, children: [] }
  }

  const matched = router.matchRoute(current.value.path)
  const routeMeta = matched?.route?.meta

  if (currentError.value !== null) {
    const routeErrorTag = routeMeta?.errorTag ?? null
    const effectiveErrorTag = routeErrorTag ?? (hasError ? errorTag : null)
    if (effectiveErrorTag) {
      return { tag: effectiveErrorTag, props: { attrs: { error: String(currentError.value) } }, children: [] }
    }
    return { tag: 'div', props: { attrs: { style: 'padding:2rem;font-family:monospace' } }, children: String(currentError.value) }
  }

  if (isNavigating.value && hasLoading && loadingTag) {
    return { tag: loadingTag, props: {}, children: [] }
  }

  // Render the page component directly when a pre-loaded tag is available AND
  // the loaded path matches the current route.  The path guard detects
  // router-internal redirects (e.g. middleware returning '/login'): when the
  // router redirects to a different path, _currentPagePath won't match
  // current.value.path and we fall back to <router-view> so the correct page
  // is rendered without stale pre-loaded state.
  const _useDirectRender = _currentPageTag && _currentPagePath === current.value.path
  const pageVnode = _useDirectRender
    ? { tag: _currentPageTag, key: _currentPageKey, props: { attrs: _currentPageAttrs }, children: [] }
    : { tag: 'router-view', props: {}, children: [] }

  // Support nested layout chains: meta.layoutChain = ['default', 'admin']
  // renders <layout-default><layout-admin><page/></layout-admin></layout-default>
  const chain = routeMeta?.layoutChain
    ? routeMeta.layoutChain
    : [routeMeta?.layout ?? 'default']

  // Build nested vnodes from innermost to outermost.
  let vnode = pageVnode
  for (let i = chain.length - 1; i >= 0; i--) {
    const tag = layouts[chain[i]]
    if (tag) vnode = { tag, props: {}, children: [vnode] }
  }
  return vnode
})

for (const plugin of plugins) {
  if (plugin && typeof plugin.setup === 'function') {
    await plugin.setup({
      router,
      provide: (key, value) => { _pluginProvides.set(key, value) },
      config: {},
    })
  }
}

// ─── Pre-load initial route + hydration strategy ─────────────────────────────
// Download the current page's route chunk AFTER plugins run so that
// cer-layout-view's first render (which calls provide()) completes before
// page components are defined and their renders are scheduled. This ensures
// inject() in child components can find values stored by provide().
//
// meta.hydrate controls WHEN the initial page activates:
//   'load'    — immediately (default)
//   'idle'    — deferred until requestIdleCallback (browser idle)
//   'visible' — deferred until cer-layout-view enters the viewport
//   'none'    — never: SSR HTML stays as-is, no JS activation

if (typeof window !== 'undefined') {
  const _initMatch = router.matchRoute(window.location.pathname)
  const _hydrateStrategy = _initMatch?.route?.meta?.hydrate ?? 'load'
  const _entryHost = document.querySelector('cer-layout-view')
  const _entryHasServerTree = Boolean(_entryHost && Array.from(_entryHost.childNodes).some(
    (node) => node.nodeType === 1 || Boolean(node.textContent?.trim()),
  ))
  const _entryServerTreePath = _entryHost?.getAttribute('data-cer-route')
  const _entryServerTreeMatches = !_entryServerTreePath ||
    decodeURIComponent(_entryServerTreePath) === window.location.pathname
  const _canKeepStaticEntry = _entryHasServerTree && _entryServerTreeMatches

  if (_hydrateStrategy === 'none' && _canKeepStaticEntry) {
    // Matching static HTML only — leave the page output and loader data
    // untouched. Load its module after the first paint so explicitly
    // interactive descendants (breadcrumbs, TOCs, menus, etc.) can upgrade
    // without putting the static page chunk on the critical rendering path.
    const _loadStaticRouteModule = () => {
      const _load = _initMatch?.route?.load
      if (typeof _load === 'function') {
        void _load().catch((error) => {
          console.error('[cer-app] Failed to activate static route islands:', error)
        })
      }
    }
    if (typeof requestAnimationFrame === 'function') {
      requestAnimationFrame(() => setTimeout(_loadStaticRouteModule, 0))
    } else {
      setTimeout(_loadStaticRouteModule, 0)
    }

    // The server marks the page host with data-cer-hydrate="none", so upgrading
    // its custom element cannot trigger a second render.  Keep __CER_DATA__
    // available for nested static components as they upgrade; the first
    // real client navigation clears it before rendering the destination route.
    // A static host may serve another entry's HTML as its history fallback;
    // that mismatched tree must go through normal client route activation.
  } else {
    const _doHydrate = async () => {
      const _hydrationIntent = _navigationIntent
      const _initPath = window.location.pathname + window.location.search + window.location.hash
      const _hasInitialServerTree = _entryHasServerTree
      const _serverTreePath = _entryServerTreePath
      const _serverTreeMatchesEntry = !_serverTreePath ||
        decodeURIComponent(_serverTreePath) === new URL(_initPath, window.location.origin).pathname
      const _hasInitialLoaderData = Object.prototype.hasOwnProperty.call(globalThis, '__CER_DATA__')
      // Pre-load the page module and run the loader so cer-layout-view renders
      // the page tag directly with loader attrs (enables useProps() on hydration).
      if (_hydrationIntent === 0) {
        await _loadPageForPath(
          _initPath,
          _hasInitialLoaderData && _serverTreeMatchesEntry
            ? { runLoader: false, initialData: (globalThis).__CER_DATA__ }
            : undefined,
        )
      }
      // Only activate the initial route if the URL hasn't changed while we were
      // loading the module asynchronously (e.g. a test or plugin navigated away
      // before _doHydrate finished).  Calling _replace with a stale path would
      // override any navigation that happened during the async gap.
      const _currentPath = window.location.pathname + window.location.search + window.location.hash
      if (
        _navigationIntent === _hydrationIntent &&
        _currentPath === _initPath
      ) {
        // Use the original (unwrapped) replace so isNavigating stays false during
        // the initial paint — the loading component must not flash over pre-rendered content.
        await _replace(_initPath)
      }

      // An empty SPA shell has no server tree to retain. Middleware may also
      // redirect either while the initial chunk loads or while _replace runs,
      // making the SSR tree stale. This decision deliberately lives outside
      // the URL-stability guard above: a newer URL must not be overwritten, but
      // its resolved route still needs to replace the old server-rendered tree.
      const _requestedInitialPath = new URL(_initPath, window.location.origin).pathname
      const _resolvedInitialPath = router.getCurrent().path
      const _urlLeftInitialEntry = _currentPath !== _initPath
      if (
        !_hasInitialServerTree ||
        !_serverTreeMatchesEntry ||
        _urlLeftInitialEntry ||
        _resolvedInitialPath !== _requestedInitialPath
      ) {
        if (
          !_serverTreeMatchesEntry ||
          _urlLeftInitialEntry ||
          _resolvedInitialPath !== _requestedInitialPath
        ) {
          delete (globalThis).__CER_DATA__
        }
        if (
          _navigationIntent === _hydrationIntent &&
          _currentPagePath !== _resolvedInitialPath
        ) {
          await _loadPageForPath(_resolvedInitialPath)
        }
        _activateClientRouteRendering()
      }
      // The client entry marks the already-rendered entry URL so generated
      // route middleware can skip the browser router's startup replay once.
      // Clear any leftover flag after the first hydrated route commits so later
      // navigations always run middleware normally.
      queueMicrotask(() => { delete (globalThis).__CER_HYDRATION_ENTRY__ })
      // Keep the initial route's SSR data available after hydration.
      // Browser engines do not all upgrade and re-render custom elements with
      // identical timing, so deleting __CER_DATA__ here can cause a later
      // hydration render to fall back to the client-only path. The next real
      // router.push/router.replace clears __CER_DATA__ before loading the new
      // route, so stale page data still does not leak across navigations.
    }

    if (_hydrateStrategy === 'idle') {
      // Defer until the browser has finished higher-priority work.
      if (typeof requestIdleCallback !== 'undefined') {
        requestIdleCallback(() => { void _doHydrate() })
      } else {
        // Safari / older environments fallback.
        setTimeout(() => { void _doHydrate() }, 1)
      }
    } else if (_hydrateStrategy === 'visible') {
      // Defer until cer-layout-view (or body as fallback) enters the viewport.
      const _el = document.querySelector('cer-layout-view') ?? document.body
      const _io = new IntersectionObserver(([entry]) => {
        if (entry.isIntersecting) { _io.disconnect(); void _doHydrate() }
      })
      _io.observe(_el)
    } else {
      // 'load' — hydrate immediately (default behaviour).
      await _doHydrate()
    }
  }
}

export { router }
`
}
