/**
 * Template string for `.cer/app.ts` — the framework client entry point.
 *
 * Always written to `.cer/app.ts` on every dev/build so consumers
 * automatically receive the latest bootstrap code on plugin update.
 * This file is gitignored and should never be edited directly.
 */
export const APP_ENTRY_TEMPLATE = `// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app — do not edit.
// Regenerated automatically on every dev server start and build.

import '@jasonshimmy/custom-elements-runtime/css'
import 'virtual:cer-jit-css'
import 'virtual:cer-components'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import { hasLoading, loadingTag } from 'virtual:cer-loading'
import { hasError, errorTag } from 'virtual:cer-error'
import {
  component,
  ref,
  provide,
  useOnConnected,
  useOnDisconnected,
  registerBuiltinComponents,
} from '@jasonshimmy/custom-elements-runtime'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { enableJITCSS } from '@jasonshimmy/custom-elements-runtime/jit-css'

registerBuiltinComponents()
enableJITCSS()

const router = initRouter({ routes })

// ─── Navigation state ────────────────────────────────────────────────────────

const isNavigating = ref(false)
const currentError = ref(null)

const resetError = () => {
  currentError.value = null
  void router.replace(router.getCurrent().path)
}
;(globalThis).resetError = resetError

const _push = router.push.bind(router)
const _replace = router.replace.bind(router)

router.push = async (path) => {
  isNavigating.value = true
  currentError.value = null
  try {
    await _push(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    isNavigating.value = false
  }
}

router.replace = async (path) => {
  isNavigating.value = true
  currentError.value = null
  try {
    await _replace(path)
  } catch (err) {
    currentError.value = err instanceof Error ? err.message : String(err)
  } finally {
    isNavigating.value = false
  }
}

// ─── Plugins ─────────────────────────────────────────────────────────────────

// Collect plugin-provided values so cer-layout-view can forward them into
// the component context tree via the real provide() hook (which inject() walks).
// Declared BEFORE component('cer-layout-view') to avoid a temporal dead zone
// ReferenceError: customElements.define() upgrades existing DOM elements
// synchronously, calling the render function immediately.
const _pluginProvides = new Map()
// Expose plugin provides globally so page components can read them synchronously
// regardless of render order.
;(globalThis).__cerPluginProvides = _pluginProvides

// ─── <cer-layout-view> ───────────────────────────────────────────────────────

component('cer-layout-view', () => {
  // Forward plugin-provided values into the component context so inject() in
  // any descendant component can resolve them by walking up the DOM tree.
  for (const [key, value] of _pluginProvides) {
    provide(key, value)
  }

  const current = ref(router.getCurrent())
  let unsub

  useOnConnected(() => {
    unsub = router.subscribe((s) => { current.value = s })
  })
  useOnDisconnected(() => { unsub?.(); unsub = undefined })

  if (currentError.value !== null) {
    if (hasError && errorTag) {
      return { tag: errorTag, props: { attrs: { error: String(currentError.value) } }, children: [] }
    }
    return { tag: 'div', props: { attrs: { style: 'padding:2rem;font-family:monospace' } }, children: String(currentError.value) }
  }

  if (isNavigating.value && hasLoading && loadingTag) {
    return { tag: loadingTag, props: {}, children: [] }
  }

  const matched = router.matchRoute(current.value.path)
  const routeMeta = matched?.route?.meta
  const layoutName = routeMeta?.layout ?? 'default'
  const layoutTag = layouts[layoutName]
  const routerView = { tag: 'router-view', props: {}, children: [] }

  if (layoutTag) return { tag: layoutTag, props: {}, children: [routerView] }
  return routerView
})

for (const plugin of plugins) {
  if (plugin && typeof plugin.setup === 'function') {
    await plugin.setup({
      router,
      provide: (key, value) => { _pluginProvides.set(key, value) },
      config: {},
    })
  }
}

// ─── Pre-load initial route ───────────────────────────────────────────────────
// Download the current page's route chunk AFTER plugins run so that
// cer-layout-view's first render (which calls provide()) completes before
// page components are defined and their renders are scheduled. This ensures
// inject() in child components can find values stored by provide().

if (typeof window !== 'undefined') {
  const _initMatch = router.matchRoute(window.location.pathname)
  if (_initMatch?.route?.load) {
    try { await _initMatch.route.load() } catch { /* non-fatal */ }
  }
}

// ─── Initial navigation ──────────────────────────────────────────────────────

if (typeof window !== 'undefined') {
  // Use the original (unwrapped) replace so isNavigating stays false during
  // the initial paint — the loading component must not flash over pre-rendered content.
  await _replace(window.location.pathname + window.location.search + window.location.hash)
  // Clear SSR loader data after initial navigation so subsequent client-side
  // navigations don't accidentally reuse stale server data.
  delete (globalThis).__CER_DATA__
}

export { router }
`
