/**
 * Template string for `entry-server.ts`.
 *
 * This is the Node.js SSR entry point used for both development and production
 * builds. It imports all virtual modules, wires up the routing, and exports a
 * request handler compatible with Express/Fastify/Node http.
 *
 * Key features:
 * - AsyncLocalStorage for race-condition-free concurrent renders (SSG concurrency > 1)
 * - Declarative Shadow DOM via renderToStreamWithJITCSSDSD (always on, streamed)
 * - useHead() support via beginHeadCollection / endHeadCollection
 * - DSD polyfill injected at end of <body> after client-template merge
 */
export const ENTRY_SERVER_TEMPLATE = `// Server-side entry — AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app
import { readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AsyncLocalStorage } from 'node:async_hooks'
import 'virtual:cer-components'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import apiRoutes from 'virtual:cer-server-api'
import { runtimeConfig, _runtimePrivateDefaults } from 'virtual:cer-app-config'
import { registerBuiltinComponents } from '@jasonshimmy/custom-elements-runtime'
import { registerEntityMap, renderToStreamWithJITCSSDSD, DSD_POLYFILL_SCRIPT } from '@jasonshimmy/custom-elements-runtime/ssr'
import entitiesJson from '@jasonshimmy/custom-elements-runtime/entities.json'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { beginHeadCollection, endHeadCollection, serializeHeadTags, initRuntimeConfig, resolvePrivateConfig } from '@jasonshimmy/vite-plugin-cer-app/composables'
import { errorTag } from 'virtual:cer-error'
import { createIsrHandler } from '@jasonshimmy/vite-plugin-cer-app/isr'

registerBuiltinComponents()

// Resolve private config from environment variables at server startup.
// Each key declared in runtimeConfig.private is looked up in process.env,
// first as-is, then as ALL_CAPS. The declared default is used as fallback.
initRuntimeConfig({ ...runtimeConfig, private: resolvePrivateConfig(_runtimePrivateDefaults ?? {}) })

// Pre-load the full HTML entity map so named entities like &mdash; decode
// correctly during SSR. Without this the bundled runtime falls back to a
// minimal set (&lt;, &gt;, &amp; …) and re-escapes everything else.
registerEntityMap(entitiesJson)

// Run plugins once at server startup so their provide() values are available
// to useInject() during every SSR/SSG render pass. Stored on globalThis so all
// dynamically-imported page chunks share the same reference.
const _pluginProvides = new Map()
;(globalThis).__cerPluginProvides = _pluginProvides
const _pluginsReady = (async () => {
  const _bootstrapRouter = initRouter({ routes })
  for (const plugin of plugins) {
    if (plugin && typeof plugin.setup === 'function') {
      await plugin.setup({
        router: _bootstrapRouter,
        provide: (key, value) => _pluginProvides.set(key, value),
        config: {},
      })
    }
  }
})()

// Async-local storage for request-scoped SSR loader data.
// Using AsyncLocalStorage ensures concurrent SSR renders (e.g. SSG with
// concurrency > 1) never see each other's data — each request's async chain
// carries its own store value, so usePageData() is always race-condition-free.
const _cerDataStore = new AsyncLocalStorage()
// Expose the store so the usePageData() composable can read it server-side.
;(globalThis).__CER_DATA_STORE__ = _cerDataStore

// Async-local storage for request-scoped req/res access.
// Allows isomorphic composables (e.g. useCookie) to read/write HTTP headers
// without prop-drilling the request context through the component tree.
const _cerReqStore = new AsyncLocalStorage()
;(globalThis).__CER_REQ_STORE__ = _cerReqStore

// Load the Vite-built client index.html (dist/client/index.html) so every SSR
// response includes the client-side scripts needed for hydration and routing.
// The server bundle lives at dist/server/server.js, so ../client resolves correctly.
const _clientTemplatePath = join(dirname(fileURLToPath(import.meta.url)), '../client/index.html')
const _clientTemplate = existsSync(_clientTemplatePath)
  ? readFileSync(_clientTemplatePath, 'utf-8')
  : null

// Merge the SSR rendered body with the Vite client shell so the final page
// contains both pre-rendered DSD content and the client bundle scripts.
function _mergeWithClientTemplate(ssrHtml, clientTemplate) {
  const headTag = '<head>', headCloseTag = '</head>'
  const bodyTag = '<body>', bodyCloseTag = '</body>'
  const headStart = ssrHtml.indexOf(headTag)
  const headEnd   = ssrHtml.indexOf(headCloseTag)
  const bodyStart = ssrHtml.indexOf(bodyTag)
  const bodyEnd   = ssrHtml.lastIndexOf(bodyCloseTag)
  const ssrHead = headStart >= 0 && headEnd > headStart
    ? ssrHtml.slice(headStart + headTag.length, headEnd).trim() : ''
  const ssrBody = bodyStart >= 0 && bodyEnd > bodyStart
    ? ssrHtml.slice(bodyStart + bodyTag.length, bodyEnd).trim() : ssrHtml
  // Hoist only top-level <style id=...> elements (cer-ssr-jit, cer-ssr-global)
  // from the SSR body into the document <head>. Plain <style> blocks without
  // an id attribute belong to shadow DOM templates and must stay in place —
  // hoisting them to <head> breaks shadow DOM style encapsulation (document
  // styles do not pierce shadow roots), which is the root cause of FOUC.
  const headParts = ssrHead ? [ssrHead] : []
  let ssrBodyContent = ssrBody
  let pos = 0
  while (pos < ssrBodyContent.length) {
    const styleOpen  = ssrBodyContent.indexOf('<style id=', pos)
    if (styleOpen < 0) break
    const styleClose = ssrBodyContent.indexOf('</style>', styleOpen)
    if (styleClose < 0) break
    headParts.push(ssrBodyContent.slice(styleOpen, styleClose + 8))
    ssrBodyContent = ssrBodyContent.slice(0, styleOpen) + ssrBodyContent.slice(styleClose + 8)
    pos = styleOpen
  }
  ssrBodyContent = ssrBodyContent.trim()
  // Inject the pre-rendered layout+page as light DOM of the app mount element
  // so it is visible before JS boots, then the client router takes over.
  let merged = clientTemplate
  if (merged.includes('<cer-layout-view></cer-layout-view>')) {
    merged = merged.replace('<cer-layout-view></cer-layout-view>',
      '<cer-layout-view>' + ssrBodyContent + '</cer-layout-view>')
  } else if (merged.includes('<div id="app"></div>')) {
    merged = merged.replace('<div id="app"></div>',
      '<div id="app">' + ssrBodyContent + '</div>')
  }
  const headAdditions = headParts.filter(Boolean).join('\\n')
  if (headAdditions) {
    // If SSR provides a <title>, replace the client template's <title> so the
    // SSR title wins (client template title is the fallback default).
    if (headAdditions.includes('<title>')) {
      merged = merged.replace(/<title>[^<]*<\\/title>/, '')
    }
    merged = merged.replace('</head>', headAdditions + '\\n</head>')
  }
  return merged
}

// Per-request async setup: initialize a fresh router, resolve the matched
// route and layout, pre-load the page module, and call the data loader.
// Loader data is scoped to the current AsyncLocalStorage context via enterWith()
// so concurrent renders never share state.
const _prepareRequest = async (req) => {
  await _pluginsReady
  const router = initRouter({ routes, initialUrl: req.url ?? '/' })
  const current = router.getCurrent()
  const { route, params } = router.matchRoute(current.path)

  // Pre-load the page module so we can embed the component tag directly.
  // This avoids the async router-view (which injects content via script tags
  // and breaks Declarative Shadow DOM on initial parse).
  let pageVnode = { tag: 'div', props: {}, children: [] }
  let head
  if (route?.load) {
    try {
      const mod = await route.load()
      const pageTag = mod.default
      if (pageTag) {
        pageVnode = { tag: pageTag, props: { attrs: { ...params } }, children: [] }
      }
      if (typeof mod.loader === 'function') {
        const query = current.query ?? {}
        const data = await mod.loader({ params, query, req })
        if (data !== undefined && data !== null) {
          // enterWith() scopes the value to the current async context so
          // concurrent renders (SSG concurrency > 1) never share data.
          _cerDataStore.enterWith(data)
          head = \`<script>window.__CER_DATA__ = \${JSON.stringify(data)}</script>\`
        }
      }
    } catch (err) {
      // Loader threw — render the error page server-side if app/error.ts exists.
      const status = (err && typeof err === 'object' && 'status' in err && typeof err.status === 'number')
        ? err.status : 500
      const message = (err instanceof Error) ? err.message : String(err)
      if (!errorTag) {
        console.error('[cer-app] Loader error (no app/error.ts defined):', err)
      }
      const errVnode = errorTag
        ? { tag: errorTag, props: { attrs: { error: message, status: String(status) } }, children: [] }
        : { tag: 'div', props: {}, children: [] }
      return { vnode: errVnode, router, head: undefined, status }
    }
  }

  // Resolve layout chain: nested layouts (meta.layoutChain) or single layout.
  const chain = route?.meta?.layoutChain
    ? route.meta.layoutChain
    : [route?.meta?.layout ?? 'default']

  // Wrap pageVnode in the layout chain from innermost to outermost.
  let vnode = pageVnode
  for (let i = chain.length - 1; i >= 0; i--) {
    const tag = layouts[chain[i]]
    if (tag) vnode = { tag, props: {}, children: [vnode] }
  }

  return { vnode, router, head, status: null }
}

export const handler = async (req, res) => {
  await _cerReqStore.run({ req, res }, async () => {
  await _cerDataStore.run(null, async () => {
    const { vnode, router, head, status } = await _prepareRequest(req)
    if (status != null) res.statusCode = status

    // Begin collecting useHead() calls made during the synchronous render pass.
    // IMPORTANT: the stream's start() function runs synchronously on construction,
    // so ALL useHead() calls happen before the stream object is returned. We must
    // call endHeadCollection() immediately — before any await — to avoid a race
    // window where a concurrent request (e.g. SSG concurrency > 1) resets the
    // shared globalThis collector while this handler is suspended at an await.
    beginHeadCollection()

    // dsdPolyfill: false — we inject the polyfill manually after merging so it
    // lands at the end of <body>, not inside <cer-layout-view> light DOM where
    // scripts may not execute.
    // The first chunk from the stream is the full synchronous render. Subsequent
    // chunks are async component swap scripts streamed as they resolve.
    const stream = renderToStreamWithJITCSSDSD(vnode, { dsdPolyfill: false, router })

    // Collect head tags synchronously — all useHead() calls have already fired
    // inside the stream constructor's start() before it returned.
    const headTags = serializeHeadTags(endHeadCollection())

    const reader = stream.getReader()

    // Read the first (synchronous) chunk.
    const { value: firstChunk = '' } = await reader.read()

    // Merge loader data script + useHead() tags into the document head.
    const headContent = [head, headTags].filter(Boolean).join('\\n')

    // Wrap the rendered body in a full HTML document and inject the head additions
    // (loader data script, useHead() tags, JIT styles). No polyfill in body yet.
    const ssrHtml = \`<!DOCTYPE html><html><head>\${headContent}</head><body>\${firstChunk}</body></html>\`

    const merged = _clientTemplate
      ? _mergeWithClientTemplate(ssrHtml, _clientTemplate)
      : ssrHtml

    // Split at </body> so async swap scripts and the DSD polyfill can be streamed
    // in before the document is closed.
    const bodyCloseIdx = merged.lastIndexOf('</body>')
    const beforeBodyClose = bodyCloseIdx >= 0 ? merged.slice(0, bodyCloseIdx) : merged
    const fromBodyClose  = bodyCloseIdx >= 0 ? merged.slice(bodyCloseIdx) : ''

    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    res.setHeader('Transfer-Encoding', 'chunked')
    res.write(beforeBodyClose)

    // Stream async component swap scripts through as-is.
    while (true) {
      const { value, done } = await reader.read()
      if (done) break
      res.write(value)
    }

    // Inject DSD polyfill immediately before </body>, then close the document.
    res.end(DSD_POLYFILL_SCRIPT + fromBodyClose)
  })
  })
}

// ISR-wrapped handler for production integrations (Express, Hono, Fastify).
// Routes with meta.ssg.revalidate are served stale-while-revalidate.
export const isrHandler = createIsrHandler(routes, handler)

export { apiRoutes, plugins, layouts, routes }
export default handler
`
