/**
 * Template string for `entry-server.ts`.
 *
 * This is the Node.js SSR entry point. It imports all virtual modules,
 * wires up the routing, and exports a handler compatible with
 * Express/Fastify/Node http.
 */
export const ENTRY_SERVER_TEMPLATE = `// Server-side entry — AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app
import { readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { AsyncLocalStorage } from 'node:async_hooks'
import 'virtual:cer-components'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import apiRoutes from 'virtual:cer-server-api'
import { registerBuiltinComponents } from '@jasonshimmy/custom-elements-runtime'
import { registerEntityMap, DSD_POLYFILL_SCRIPT } from '@jasonshimmy/custom-elements-runtime/ssr'
import entitiesJson from '@jasonshimmy/custom-elements-runtime/entities.json'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { createSSRHandler } from '@jasonshimmy/custom-elements-runtime/ssr-middleware'

registerBuiltinComponents()

// Pre-load the full HTML entity map so named entities like &mdash; decode
// correctly during SSR. Without this the bundled runtime falls back to a
// minimal set (&lt;, &gt;, &amp; …) and re-escapes everything else.
registerEntityMap(entitiesJson)

// Async-local storage for request-scoped SSR loader data.
// Using AsyncLocalStorage ensures concurrent SSR renders (e.g. SSG with
// concurrency > 1) never see each other's data — each request's async chain
// carries its own store value, so usePageData() is always race-condition-free.
const _cerDataStore = new AsyncLocalStorage()
// Expose the store so the usePageData() composable can read it server-side.
;(globalThis).__CER_DATA_STORE__ = _cerDataStore

// Load the Vite-built client index.html (dist/client/index.html) so every SSR
// response includes the client-side scripts needed for hydration and routing.
// The server bundle lives at dist/server/server.js, so ../client resolves correctly.
const _clientTemplatePath = join(dirname(fileURLToPath(import.meta.url)), '../client/index.html')
const _clientTemplate = existsSync(_clientTemplatePath)
  ? readFileSync(_clientTemplatePath, 'utf-8')
  : null

// Merge the SSR handler's full HTML document with the Vite client shell so the
// final page contains both pre-rendered DSD content and the client bundle scripts.
function _mergeWithClientTemplate(ssrHtml, clientTemplate) {
  const headTag = '<head>', headCloseTag = '</head>'
  const bodyTag = '<body>', bodyCloseTag = '</body>'
  const headStart = ssrHtml.indexOf(headTag)
  const headEnd   = ssrHtml.indexOf(headCloseTag)
  const bodyStart = ssrHtml.indexOf(bodyTag)
  const bodyEnd   = ssrHtml.lastIndexOf(bodyCloseTag)
  const ssrHead = headStart >= 0 && headEnd > headStart
    ? ssrHtml.slice(headStart + headTag.length, headEnd).trim() : ''
  const ssrBody = bodyStart >= 0 && bodyEnd > bodyStart
    ? ssrHtml.slice(bodyStart + bodyTag.length, bodyEnd).trim() : ssrHtml
  // Hoist only top-level <style id=...> elements (cer-ssr-jit, cer-ssr-global)
  // from the SSR body into the document <head>. Plain <style> blocks without
  // an id attribute belong to shadow DOM templates and must stay in place —
  // hoisting them to <head> breaks shadow DOM style encapsulation (document
  // styles do not pierce shadow roots), which is the root cause of FOUC.
  const headParts = ssrHead ? [ssrHead] : []
  let ssrBodyContent = ssrBody
  let pos = 0
  while (pos < ssrBodyContent.length) {
    const styleOpen  = ssrBodyContent.indexOf('<style id=', pos)
    if (styleOpen < 0) break
    const styleClose = ssrBodyContent.indexOf('</style>', styleOpen)
    if (styleClose < 0) break
    headParts.push(ssrBodyContent.slice(styleOpen, styleClose + 8))
    ssrBodyContent = ssrBodyContent.slice(0, styleOpen) + ssrBodyContent.slice(styleClose + 8)
    pos = styleOpen
  }
  ssrBodyContent = ssrBodyContent.trim()
  // Inject the pre-rendered layout+page as light DOM of the app mount element
  // so it is visible before JS boots, then the client router takes over.
  let merged = clientTemplate
  if (merged.includes('<cer-layout-view></cer-layout-view>')) {
    merged = merged.replace('<cer-layout-view></cer-layout-view>',
      '<cer-layout-view>' + ssrBodyContent + '</cer-layout-view>')
  } else if (merged.includes('<div id="app"></div>')) {
    merged = merged.replace('<div id="app"></div>',
      '<div id="app">' + ssrBodyContent + '</div>')
  }
  const headAdditions = headParts.filter(Boolean).join('\\n')
  if (headAdditions) {
    // If SSR provides a <title>, replace the client template's <title> so the
    // SSR title wins (client template title is the fallback default).
    if (headAdditions.includes('<title>')) {
      merged = merged.replace(/<title>[^<]*<\\/title>/, '')
    }
    merged = merged.replace('</head>', headAdditions + '\\n</head>')
  }
  return merged
}

/**
 * Per-request VNode factory — initializes a fresh router at the request URL,
 * resolves the active layout from the matched route's meta, pre-loads the
 * matched page component (bypassing the async router-view so DSD renders
 * synchronously), calls the route's data loader (if any), and injects the
 * serialized result into the document head as window.__CER_DATA__ for
 * client-side hydration.
 *
 * createStreamingSSRHandler threads the router through each component's SSR
 * context so concurrent renders never share state.
 */
const vnodeFactory = async (req) => {
  const router = initRouter({ routes, initialUrl: req.url ?? '/' })
  const current = router.getCurrent()
  const { route, params } = router.matchRoute(current.path)
  const layoutName = route?.meta?.layout ?? 'default'
  const layoutTag = layouts[layoutName]

  // Pre-load the page module so we can embed the component tag directly.
  // This avoids the async router-view (which injects content via script tags
  // and breaks Declarative Shadow DOM on initial parse).
  let pageVnode = { tag: 'div', props: {}, children: [] }
  let head
  if (route?.load) {
    try {
      const mod = await route.load()
      const pageTag = mod.default
      if (pageTag) {
        pageVnode = { tag: pageTag, props: { attrs: { ...params } }, children: [] }
      }
      if (typeof mod.loader === 'function') {
        const query = current.query ?? {}
        const data = await mod.loader({ params, query, req })
        if (data !== undefined && data !== null) {
          // Make data available to usePageData() during the SSR render pass.
          // enterWith() scopes the value to the current async context so
          // concurrent renders (SSG concurrency > 1) never share data.
          _cerDataStore.enterWith(data)
          head = \`<script>window.__CER_DATA__ = \${JSON.stringify(data)}</script>\`
        }
      }
    } catch {
      // Non-fatal: loader errors fall back to an empty page; client will refetch.
    }
  }

  const vnode = layoutTag
    ? { tag: layoutTag, props: {}, children: [pageVnode] }
    : pageVnode

  return { vnode, router, head }
}

// Capture the raw SSR handler and wrap it to merge the response with the
// Vite client template before sending — this injects the JS/CSS asset bundles
// so the browser can hydrate and enable client-side routing.
const _rawHandler = createSSRHandler(vnodeFactory, {
  render: { dsd: true, dsdPolyfill: false },
})

/**
 * The main request handler.
 * Compatible with Express, Fastify, and Node's raw http.createServer.
 *
 * Each request is run inside a fresh _cerDataStore.run() context so that
 * concurrent renders (e.g. SSG with concurrency > 1) get isolated stores.
 * vnodeFactory calls _cerDataStore.enterWith(loaderData) from within this
 * context, making the data visible to usePageData() during SSR rendering
 * without any global-state races.
 */
export const handler = async (req, res) => {
  if (!_clientTemplate) {
    // No client template — run handler normally, then inject DSD polyfill.
    let _html = ''
    await _cerDataStore.run(null, async () => {
      await _rawHandler(req, { setHeader: () => {}, end: (body) => { _html = body } })
    })
    // Inject DSD polyfill at end of <body>, outside any custom element light DOM.
    const _final = _html.includes('</body>')
      ? _html.replace('</body>', DSD_POLYFILL_SCRIPT + '</body>')
      : _html + DSD_POLYFILL_SCRIPT
    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    return res.end(_final)
  }
  let _capturedHtml = ''
  // Wrap _rawHandler in an isolated async-local-storage context so that
  // vnodeFactory's enterWith() call is scoped to this request only.
  await _cerDataStore.run(null, async () => {
    // Omit write() to force the non-streaming collect-then-end code path.
    await _rawHandler(req, { setHeader: () => {}, end: (body) => { _capturedHtml = body } })
  })
  let _merged = _mergeWithClientTemplate(_capturedHtml, _clientTemplate)
  // Inject DSD polyfill at end of <body>, outside <cer-layout-view> light DOM.
  _merged = _merged.includes('</body>')
    ? _merged.replace('</body>', DSD_POLYFILL_SCRIPT + '</body>')
    : _merged + DSD_POLYFILL_SCRIPT
  res.setHeader('Content-Type', 'text/html; charset=utf-8')
  res.end(_merged)
}

export { apiRoutes, plugins, layouts, routes }
export default handler
`
