/**
 * Template string for `entry-server.ts`.
 *
 * This is the Node.js SSR entry point. It imports all virtual modules,
 * wires up the routing, and exports a handler compatible with
 * Express/Fastify/Node http.
 */
export const ENTRY_SERVER_TEMPLATE = `// Server-side entry — AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app
import 'virtual:cer-components'
import routes from 'virtual:cer-routes'
import layouts from 'virtual:cer-layouts'
import plugins from 'virtual:cer-plugins'
import apiRoutes from 'virtual:cer-server-api'
import { html, registerBuiltinComponents } from '@jasonshimmy/custom-elements-runtime'
import { initRouter } from '@jasonshimmy/custom-elements-runtime/router'
import { createStreamingSSRHandler } from '@jasonshimmy/custom-elements-runtime/ssr-middleware'

registerBuiltinComponents()

/**
 * Per-request VNode factory — initializes a fresh router at the request URL,
 * resolves the active layout from the matched route's meta, calls the matched
 * route's data loader (if any), and injects the serialized result into the
 * document head as window.__CER_DATA__ for client-side hydration.
 *
 * createStreamingSSRHandler threads the router through each component's SSR
 * context so router-view reads from the per-request instance instead of the
 * shared activeRouterProxy singleton. This makes concurrent SSR requests safe.
 */
const vnodeFactory = async (req) => {
  const router = initRouter({ routes, initialUrl: req.url ?? '/' })
  const current = router.getCurrent()
  const { route, params } = router.matchRoute(current.path)
  const layoutName = route?.meta?.layout ?? 'default'
  const layoutTag = layouts[layoutName]
  const inner = html\`<router-view></router-view>\`
  const vnode = layoutTag
    ? { tag: layoutTag, props: {}, children: [inner] }
    : inner

  // Call the route's data loader (if present) and serialize for client hydration.
  let head
  if (route?.load) {
    try {
      const mod = await route.load()
      if (typeof mod.loader === 'function') {
        const query = current.query ?? {}
        const data = await mod.loader({ params, query, req })
        if (data !== undefined && data !== null) {
          head = \`<script>window.__CER_DATA__ = \${JSON.stringify(data)}</script>\`
        }
      }
    } catch {
      // Loader errors are non-fatal during SSR; the client will refetch.
    }
  }

  return { vnode, router, head }
}

/**
 * The main request handler.
 * Compatible with Express, Fastify, and Node's raw http.createServer.
 */
export const handler = createStreamingSSRHandler(vnodeFactory, {
  render: { dsd: true },
})

export { apiRoutes, plugins, layouts, routes }
export default handler
`
