import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { readFileSync } from 'node:fs'
import { join, relative } from 'pathe'
import { scanDirectory } from './scanner.js'
import { GENERATED_DIR_NAME } from './generated-dir.js'

/**
 * Writes `.cer/tsconfig.json` containing path aliases for the `~/` prefix
 * plus include/exclude entries so the consumer's `tsconfig.json` only needs:
 *   { "extends": "./.cer/tsconfig.json" }
 */
export function writeTsconfigPaths(root: string, srcDir: string): void {
  const cerDir = join(root, GENERATED_DIR_NAME)
  if (!existsSync(cerDir)) {
    mkdirSync(cerDir, { recursive: true })
  }

  // Paths are relative to .cer/ inside the project root, so prefix with ../
  const srcRel = '../' + relative(root, srcDir).replace(/\\/g, '/')
  const paths: Record<string, string[]> = {
    '~/*': [`${srcRel}/*`],
    '~/pages/*': [`${srcRel}/pages/*`],
    '~/layouts/*': [`${srcRel}/layouts/*`],
    '~/components/*': [`${srcRel}/components/*`],
    '~/composables/*': [`${srcRel}/composables/*`],
    '~/plugins/*': [`${srcRel}/plugins/*`],
    '~/middleware/*': [`${srcRel}/middleware/*`],
    '~/assets/*': [`${srcRel}/assets/*`],
  }

  const tsconfig = {
    compilerOptions: { paths },
    include: [
      '../app/**/*.ts',
      '../server/**/*.ts',
      './**/*.ts',
      './**/*.d.ts',
    ],
    exclude: ['../node_modules', '../dist'],
  }

  const content = JSON.stringify(tsconfig, null, 2) + '\n'
  writeFileSync(join(cerDir, 'tsconfig.json'), content, 'utf-8')
}

const RUNTIME_GLOBALS = [
  'component',
  'html',
  'css',
  'ref',
  'computed',
  'watch',
  'watchEffect',
  'useProps',
  'useEmit',
  'useOnConnected',
  'useOnDisconnected',
  'useOnAttributeChanged',
  'useOnError',
  'useStyle',
  'useDesignTokens',
  'useGlobalStyle',
  'useExpose',
  'useSlots',
  'provide',
  'inject',
  'createComposable',
  'nextTick',
  'defineModel',
  'getCurrentComponentContext',
  'isReactiveState',
  'unsafeHTML',
  'decodeEntities',
  'useTeleport',
]

const DIRECTIVE_GLOBALS = ['when', 'each', 'match', 'anchorBlock']

const FRAMEWORK_GLOBALS = ['useHead', 'usePageData', 'useInject', 'useRuntimeConfig', 'defineMiddleware', 'defineServerMiddleware', 'useSeoMeta', 'useCookie', 'useSession', 'useAuth', 'useFetch', 'useRoute', 'navigateTo', 'useState', 'useLocale', 'queryContent', 'useContentSearch']

/**
 * Scans a composables directory and returns a map of export name → file path.
 * Uses a simple regex to find exported identifiers.
 */
export async function scanComposableExports(composablesDir: string): Promise<Map<string, string>> {
  const result = new Map<string, string>()
  if (!existsSync(composablesDir)) return result

  const files = await scanDirectory('**/*.ts', composablesDir)
  const exportPattern = /export\s+(?:async\s+)?(?:function|const|let|var|class)\s+(\w+)/g

  for (const file of files) {
    const code = readFileSync(file, 'utf-8')
    exportPattern.lastIndex = 0
    let match
    while ((match = exportPattern.exec(code)) !== null) {
      result.set(match[1], file)
    }
  }

  return result
}

/**
 * Generates the content of `cer-auto-imports.d.ts`.
 * @param root - project root (where the .d.ts file will be written)
 */
export async function generateAutoImportDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<string> {
  const exports = composableExports ?? await scanComposableExports(composablesDir)

  const lines: string[] = [
    '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
    '// Do not edit — regenerated automatically on dev server start and build.',
    '',
    'export {}',
    '',
    'declare global {',
  ]

  for (const name of RUNTIME_GLOBALS) {
    lines.push(`  const ${name}: typeof import('@jasonshimmy/custom-elements-runtime')['${name}']`)
  }

  lines.push('')

  for (const name of DIRECTIVE_GLOBALS) {
    lines.push(`  const ${name}: typeof import('@jasonshimmy/custom-elements-runtime/directives')['${name}']`)
  }

  lines.push('')

  for (const name of FRAMEWORK_GLOBALS) {
    lines.push(`  const ${name}: typeof import('@jasonshimmy/vite-plugin-cer-app/composables')['${name}']`)
  }

  if (exports.size > 0) {
    lines.push('')
    for (const [name, filePath] of exports) {
      // Use a path relative to the project root so the .d.ts is portable
      const rel = './' + relative(root, filePath).replace(/\.ts$/, '')
      lines.push(`  const ${name}: typeof import('${rel}')['${name}']`)
    }
  }

  lines.push('')
  lines.push('  // Content layer types')
  lines.push(`  type ContentMeta = import('@jasonshimmy/vite-plugin-cer-app')['ContentMeta']`)
  lines.push(`  type ContentItem = import('@jasonshimmy/vite-plugin-cer-app')['ContentItem']`)
  lines.push(`  type ContentHeading = import('@jasonshimmy/vite-plugin-cer-app')['ContentHeading']`)
  lines.push(`  type ContentSearchResult = import('@jasonshimmy/vite-plugin-cer-app')['ContentSearchResult']`)
  lines.push('')
  lines.push('  // SSR loader data injected as window.__CER_DATA__ by the server.')
  lines.push('  // Consumed once by usePageData() during client hydration.')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  var __CER_DATA__: any')
  lines.push('  // SSR useState() values injected as window.__CER_STATE_INIT__ by the server.')
  lines.push('  // Pre-populates the client useState() Map on first use.')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  var __CER_STATE_INIT__: any')
  lines.push('  // App config injected by virtual:cer-app-config at app bootstrap.')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  var __CER_APP_CONFIG__: any')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generates the content of `cer-env.d.ts` — a script (non-module) file
 * containing ambient `declare module` declarations for all virtual modules.
 * Must NOT contain `export {}` or any top-level imports/exports.
 */
export async function generateVirtualModuleDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<string> {
  const exports = composableExports ?? await scanComposableExports(composablesDir)

  const lines: string[] = [
    '// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app',
    '// Do not edit — regenerated automatically on dev server start and build.',
    '',
    `declare module 'virtual:cer-routes' {`,
    `  import type { Route } from '@jasonshimmy/custom-elements-runtime/router'`,
    `  const routes: Route[]`,
    `  export default routes`,
    `}`,
    '',
    `declare module 'virtual:cer-layouts' {}`,
    '',
    `declare module 'virtual:cer-plugins' {`,
    `  import type { AppPlugin } from '@jasonshimmy/vite-plugin-cer-app/types'`,
    `  const plugins: AppPlugin[]`,
    `  export default plugins`,
    `}`,
    '',
    `declare module 'virtual:cer-composables' {`,
  ]

  for (const [name, filePath] of exports) {
    const rel = './' + relative(root, filePath).replace(/\.ts$/, '')
    lines.push(`  export { ${name} } from '${rel}'`)
  }

  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-middleware' {`)
  lines.push(`  const middleware: Record<string, Function>`)
  lines.push(`  export { middleware }`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-server-middleware' {`)
  lines.push(`  import type { ServerMiddleware } from '@jasonshimmy/vite-plugin-cer-app/types'`)
  lines.push(`  export const serverMiddleware: Array<{ name: string; handler: ServerMiddleware }>`)
  lines.push(`  export default serverMiddleware`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-loading' {`)
  lines.push(`  export const hasLoading: boolean`)
  lines.push(`  export const loadingTag: string | null`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-error' {`)
  lines.push(`  export const hasError: boolean`)
  lines.push(`  export const errorTag: string | null`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-app-config' {`)
  lines.push(`  import type { RuntimePublicConfig, RuntimePrivateConfig } from '@jasonshimmy/vite-plugin-cer-app/types'`)
  lines.push(`  export const appConfig: { mode: string; router: Record<string, unknown>; ssg: Record<string, unknown> }`)
  lines.push(`  export const runtimeConfig: { public: RuntimePublicConfig }`)
  lines.push(`  /** Server-only — present only in the SSR bundle. Always \`undefined\` in the client bundle. */`)
  lines.push(`  export const _runtimePrivateDefaults: RuntimePrivateConfig | undefined`)
  lines.push(`  /** Cookie/session key for the auth session. Derived from the app name. */`)
  lines.push(`  export const _authSessionKey: string`)
  lines.push(`  export default appConfig`)
  lines.push(`}`)
  lines.push('')

  return lines.join('\n')
}

/**
 * Writes `auto-imports.d.ts` and `env.d.ts` to `.cer/` inside the project root.
 */
export async function writeAutoImportDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<void> {
  const cerDir = join(root, GENERATED_DIR_NAME)
  if (!existsSync(cerDir)) {
    mkdirSync(cerDir, { recursive: true })
  }

  const scanned = composableExports ?? await scanComposableExports(composablesDir)
  const autoImportsContent = await generateAutoImportDts(root, composablesDir, scanned)
  const envContent = await generateVirtualModuleDts(root, composablesDir, scanned)
  writeFileSync(join(cerDir, 'auto-imports.d.ts'), autoImportsContent, 'utf-8')
  writeFileSync(join(cerDir, 'env.d.ts'), envContent, 'utf-8')
}
