import { writeFileSync } from 'node:fs'
import { readFileSync, existsSync } from 'node:fs'
import { join, relative } from 'pathe'
import { scanDirectory } from './scanner.js'

/**
 * Writes `cer-tsconfig.json` to the project root containing path aliases for
 * the `~/` prefix. Users extend it from their `tsconfig.json`:
 *   { "extends": "./cer-tsconfig.json" }
 */
export function writeTsconfigPaths(root: string, srcDir: string): void {
  const rel = './' + relative(root, srcDir).replace(/\\/g, '/')
  const paths: Record<string, string[]> = {
    '~/*': [`${rel}/*`],
    '~/pages/*': [`${rel}/pages/*`],
    '~/layouts/*': [`${rel}/layouts/*`],
    '~/components/*': [`${rel}/components/*`],
    '~/composables/*': [`${rel}/composables/*`],
    '~/plugins/*': [`${rel}/plugins/*`],
    '~/middleware/*': [`${rel}/middleware/*`],
    '~/assets/*': [`${rel}/assets/*`],
  }
  const content = JSON.stringify({ compilerOptions: { paths } }, null, 2) + '\n'
  writeFileSync(join(root, 'cer-tsconfig.json'), content, 'utf-8')
}

const RUNTIME_GLOBALS = [
  'component',
  'html',
  'css',
  'ref',
  'computed',
  'watch',
  'watchEffect',
  'useProps',
  'useEmit',
  'useOnConnected',
  'useOnDisconnected',
  'useOnAttributeChanged',
  'useOnError',
  'useStyle',
  'useDesignTokens',
  'useGlobalStyle',
  'useExpose',
  'useSlots',
  'provide',
  'inject',
  'createComposable',
  'nextTick',
  'defineModel',
  'getCurrentComponentContext',
  'isReactiveState',
  'unsafeHTML',
  'decodeEntities',
  'useTeleport',
]

const DIRECTIVE_GLOBALS = ['when', 'each', 'match', 'anchorBlock']

const FRAMEWORK_GLOBALS = ['useHead', 'usePageData']

/**
 * Scans a composables directory and returns a map of export name → file path.
 * Uses a simple regex to find exported identifiers.
 */
export async function scanComposableExports(composablesDir: string): Promise<Map<string, string>> {
  const result = new Map<string, string>()
  if (!existsSync(composablesDir)) return result

  const files = await scanDirectory('**/*.ts', composablesDir)
  const exportPattern = /export\s+(?:async\s+)?(?:function|const|let|var|class)\s+(\w+)/g

  for (const file of files) {
    const code = readFileSync(file, 'utf-8')
    exportPattern.lastIndex = 0
    let match
    while ((match = exportPattern.exec(code)) !== null) {
      result.set(match[1], file)
    }
  }

  return result
}

/**
 * Generates the content of `cer-auto-imports.d.ts`.
 * @param root - project root (where the .d.ts file will be written)
 */
export async function generateAutoImportDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<string> {
  const exports = composableExports ?? await scanComposableExports(composablesDir)

  const lines: string[] = [
    '// AUTO-GENERATED by vite-plugin-cer-app',
    '// Do not edit — regenerated automatically on dev server start and build.',
    '',
    'export {}',
    '',
    'declare global {',
  ]

  for (const name of RUNTIME_GLOBALS) {
    lines.push(`  const ${name}: typeof import('@jasonshimmy/custom-elements-runtime')['${name}']`)
  }

  lines.push('')

  for (const name of DIRECTIVE_GLOBALS) {
    lines.push(`  const ${name}: typeof import('@jasonshimmy/custom-elements-runtime/directives')['${name}']`)
  }

  lines.push('')

  for (const name of FRAMEWORK_GLOBALS) {
    lines.push(`  const ${name}: typeof import('vite-plugin-cer-app/composables')['${name}']`)
  }

  if (exports.size > 0) {
    lines.push('')
    for (const [name, filePath] of exports) {
      // Use a path relative to the project root so the .d.ts is portable
      const rel = './' + relative(root, filePath).replace(/\.ts$/, '')
      lines.push(`  const ${name}: typeof import('${rel}')['${name}']`)
    }
  }

  lines.push('')
  lines.push('  // SSR loader data injected as window.__CER_DATA__ by the server.')
  lines.push('  // Consumed once by usePageData() during client hydration.')
  lines.push('  // eslint-disable-next-line @typescript-eslint/no-explicit-any')
  lines.push('  var __CER_DATA__: any')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generates the content of `cer-env.d.ts` — a script (non-module) file
 * containing ambient `declare module` declarations for all virtual modules.
 * Must NOT contain `export {}` or any top-level imports/exports.
 */
export async function generateVirtualModuleDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<string> {
  const exports = composableExports ?? await scanComposableExports(composablesDir)

  const lines: string[] = [
    '// AUTO-GENERATED by vite-plugin-cer-app',
    '// Do not edit — regenerated automatically on dev server start and build.',
    '',
    `declare module 'virtual:cer-routes' {`,
    `  import type { Route } from '@jasonshimmy/custom-elements-runtime/router'`,
    `  const routes: Route[]`,
    `  export default routes`,
    `}`,
    '',
    `declare module 'virtual:cer-layouts' {}`,
    `declare module 'virtual:cer-components' {}`,
    '',
    `declare module 'virtual:cer-plugins' {`,
    `  import type { AppPlugin } from 'vite-plugin-cer-app/types'`,
    `  const plugins: AppPlugin[]`,
    `  export default plugins`,
    `}`,
    '',
    `declare module 'virtual:cer-composables' {`,
  ]

  for (const [name, filePath] of exports) {
    const rel = './' + relative(root, filePath).replace(/\.ts$/, '')
    lines.push(`  export { ${name} } from '${rel}'`)
  }

  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-middleware' {`)
  lines.push(`  const middleware: Record<string, Function>`)
  lines.push(`  export { middleware }`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-loading' {`)
  lines.push(`  export const hasLoading: boolean`)
  lines.push(`  export const loadingTag: string | null`)
  lines.push(`}`)
  lines.push('')
  lines.push(`declare module 'virtual:cer-error' {`)
  lines.push(`  export const hasError: boolean`)
  lines.push(`  export const errorTag: string | null`)
  lines.push(`}`)
  lines.push('')

  return lines.join('\n')
}

/**
 * Writes both `cer-auto-imports.d.ts` and `cer-env.d.ts` to the project root.
 */
export async function writeAutoImportDts(
  root: string,
  composablesDir: string,
  composableExports?: Map<string, string>,
): Promise<void> {
  const scanned = composableExports ?? await scanComposableExports(composablesDir)
  const autoImportsContent = await generateAutoImportDts(root, composablesDir, scanned)
  const envContent = await generateVirtualModuleDts(root, composablesDir, scanned)
  writeFileSync(join(root, 'cer-auto-imports.d.ts'), autoImportsContent, 'utf-8')
  writeFileSync(join(root, 'cer-env.d.ts'), envContent, 'utf-8')
}
