import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateComponentsCode } from '../../../plugin/virtual/components.js'

const COMPONENTS = '/project/app/components'

describe('generateComponentsCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns no-directory comment when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).toContain('No components directory found')
  })

  it('returns no-components comment when no files found', async () => {
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).toContain('No components found')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPONENTS}/my-button.ts`])
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).toContain('AUTO-GENERATED by vite-plugin-cer-app')
  })

  it('generates side-effect imports for each component file', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPONENTS}/my-button.ts`])
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).toContain(`import "${COMPONENTS}/my-button.ts"`)
  })

  it('generates side-effect imports for multiple components', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${COMPONENTS}/my-button.ts`,
      `${COMPONENTS}/ui/card.ts`,
    ])
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).toContain(`import "${COMPONENTS}/my-button.ts"`)
    expect(code).toContain(`import "${COMPONENTS}/ui/card.ts"`)
  })

  it('does not include named exports (side-effect only)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPONENTS}/my-button.ts`])
    const code = await generateComponentsCode(COMPONENTS)
    expect(code).not.toContain('export')
  })
})
