import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateComposablesCode } from '../../../plugin/virtual/composables.js'

const COMPOSABLES = '/project/app/composables'

describe('generateComposablesCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns no-directory comment when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateComposablesCode(COMPOSABLES)
    expect(code).toContain('No composables directory found')
  })

  it('returns no-composables comment when no files found', async () => {
    const code = await generateComposablesCode(COMPOSABLES)
    expect(code).toContain('No composables found')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPOSABLES}/useTheme.ts`])
    const code = await generateComposablesCode(COMPOSABLES)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates export * from for each composable file', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPOSABLES}/useTheme.ts`])
    const code = await generateComposablesCode(COMPOSABLES)
    expect(code).toContain(`export * from "${COMPOSABLES}/useTheme.ts"`)
  })

  it('generates export * from for multiple composables', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${COMPOSABLES}/useTheme.ts`,
      `${COMPOSABLES}/useAuth.ts`,
    ])
    const code = await generateComposablesCode(COMPOSABLES)
    expect(code).toContain(`export * from "${COMPOSABLES}/useTheme.ts"`)
    expect(code).toContain(`export * from "${COMPOSABLES}/useAuth.ts"`)
  })

  it('does not generate side-effect imports (re-exports only)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${COMPOSABLES}/useTheme.ts`])
    const code = await generateComposablesCode(COMPOSABLES)
    // Should NOT have plain `import "..."` side-effect imports
    expect(code).not.toMatch(/^import "/)
  })
})
