// @vitest-environment happy-dom
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'pathe'
import { generateContentComponentsCode } from '../../../plugin/virtual/content-components.js'
import * as parser from '../../../plugin/content/parser.js'

let tmpRoot: string
let componentsDir: string
let contentDir: string

beforeAll(() => {
  tmpRoot = mkdtempSync(join(tmpdir(), 'cer-content-components-'))
  componentsDir = join(tmpRoot, 'app', 'components')
  contentDir = join(tmpRoot, 'content')

  mkdirSync(componentsDir, { recursive: true })
  mkdirSync(contentDir, { recursive: true })

  writeFileSync(
    join(componentsDir, 'site-callout.ts'),
    "component('site-callout', () => html`<div>Callout</div>`)",
  )
  writeFileSync(
    join(componentsDir, 'site-alert.ts'),
    "component('site-alert', () => html`<div>Alert</div>`)",
  )

  writeFileSync(
    join(contentDir, 'guide.md'),
    [
      '# Guide',
      '',
      '<site-callout>Docs</site-callout>',
      '',
      '```html',
      '<site-alert>Example only</site-alert>',
      '```',
      '',
      '<unknown-widget>Ignored</unknown-widget>',
    ].join('\n'),
  )
})

afterAll(() => {
  rmSync(tmpRoot, { recursive: true, force: true })
})

describe('generateContentComponentsCode', () => {
  it('produces identical client manifests when content reads complete in different orders', async () => {
    const directory = join(tmpRoot, 'ordered-content')
    mkdirSync(directory, { recursive: true })
    for (const name of ['alpha', 'zeta']) writeFileSync(join(directory, `${name}.md`), '# Document\n<site-callout>Content</site-callout>')
    const parse = parser.parseContentFileAsync
    let reverse = false
    const spy = vi.spyOn(parser, 'parseContentFileAsync').mockImplementation(async (...args) => {
      if (args[0].filePath.endsWith(reverse ? 'zeta.md' : 'alpha.md')) await new Promise((done) => setTimeout(done, 20))
      return parse(...args)
    })
    try {
      const first = await generateContentComponentsCode(componentsDir, directory, false)
      reverse = true
      const second = await generateContentComponentsCode(componentsDir, directory, false)
      expect(first).toBe(second)
    } finally { spy.mockRestore() }
  })
  it('imports only registered components referenced by rendered markdown', async () => {
    const code = await generateContentComponentsCode(componentsDir, contentDir)

    expect(code).toContain(JSON.stringify(join(componentsDir, 'site-callout.ts')))
    expect(code).not.toContain(JSON.stringify(join(componentsDir, 'site-alert.ts')))
    expect(code).not.toContain('unknown-widget')
    expect(code).toContain('export {}')
  })

  it('returns an empty module when no markdown-backed components are found', async () => {
    const emptyContentDir = join(tmpRoot, 'empty-content')
    mkdirSync(emptyContentDir, { recursive: true })
    writeFileSync(join(emptyContentDir, 'plain.md'), '# Plain\n\nNo custom elements here.')

    const code = await generateContentComponentsCode(componentsDir, emptyContentDir)
    expect(code).toBe('// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport {}\n')
  })

  it('loads a content island from rendered shadow DOM when a hydrate-none page omits its loader data', async () => {
    const code = await generateContentComponentsCode(componentsDir, contentDir, false)
    const imported: string[] = []
    const source = code.replace(/import\(([^)]+)\)/g, 'importModule($1)').replace('export async function', 'async function')
    const load = new Function('importModule', `${source}\nreturn loadContentComponents`)(async (path: string) => { imported.push(path) })
    const host = document.createElement('div')
    host.attachShadow({ mode: 'open' }).innerHTML = '<site-callout>Server content</site-callout>'
    document.body.append(host)
    try {
      await load('/reader', true)
      expect(imported).toEqual([join(componentsDir, 'site-callout.ts')])
    } finally { host.remove() }
  })
})
