import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'pathe'
import { generateContentComponentsCode } from '../../../plugin/virtual/content-components.js'

let tmpRoot: string
let componentsDir: string
let contentDir: string

beforeAll(() => {
  tmpRoot = mkdtempSync(join(tmpdir(), 'cer-content-components-'))
  componentsDir = join(tmpRoot, 'app', 'components')
  contentDir = join(tmpRoot, 'content')

  mkdirSync(componentsDir, { recursive: true })
  mkdirSync(contentDir, { recursive: true })

  writeFileSync(
    join(componentsDir, 'site-callout.ts'),
    "component('site-callout', () => html`<div>Callout</div>`)",
  )
  writeFileSync(
    join(componentsDir, 'site-alert.ts'),
    "component('site-alert', () => html`<div>Alert</div>`)",
  )

  writeFileSync(
    join(contentDir, 'guide.md'),
    [
      '# Guide',
      '',
      '<site-callout>Docs</site-callout>',
      '',
      '```html',
      '<site-alert>Example only</site-alert>',
      '```',
      '',
      '<unknown-widget>Ignored</unknown-widget>',
    ].join('\n'),
  )
})

afterAll(() => {
  rmSync(tmpRoot, { recursive: true, force: true })
})

describe('generateContentComponentsCode', () => {
  it('imports only registered components referenced by rendered markdown', async () => {
    const code = await generateContentComponentsCode(componentsDir, contentDir)

    expect(code).toContain(JSON.stringify(join(componentsDir, 'site-callout.ts')))
    expect(code).not.toContain(JSON.stringify(join(componentsDir, 'site-alert.ts')))
    expect(code).not.toContain('unknown-widget')
    expect(code).toContain('export {}')
  })

  it('returns an empty module when no markdown-backed components are found', async () => {
    const emptyContentDir = join(tmpRoot, 'empty-content')
    mkdirSync(emptyContentDir, { recursive: true })
    writeFileSync(join(emptyContentDir, 'plain.md'), '# Plain\n\nNo custom elements here.')

    const code = await generateContentComponentsCode(componentsDir, emptyContentDir)
    expect(code).toBe('// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app\nexport {}\n')
  })
})