import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))

import { existsSync } from 'node:fs'
import { generateErrorCode } from '../../../plugin/virtual/error.js'

const SRC_DIR = '/project/app'

describe('generateErrorCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(false)
  })

  it('returns falsy exports when error.ts does not exist', async () => {
    const code = await generateErrorCode(SRC_DIR)
    expect(code).toContain('export const hasError = false')
    expect(code).toContain('export const errorTag = null')
  })

  it('includes AUTO-GENERATED comment when no error file', async () => {
    const code = await generateErrorCode(SRC_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('returns truthy exports when error.ts exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateErrorCode(SRC_DIR)
    expect(code).toContain('export const hasError = true')
    expect(code).toContain("export const errorTag = 'page-error'")
  })

  it('imports the error file when it exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateErrorCode(SRC_DIR)
    expect(code).toContain(`${SRC_DIR}/error.ts`)
  })

  it('includes AUTO-GENERATED comment when error file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateErrorCode(SRC_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('checks for error.ts specifically (not error.js)', async () => {
    await generateErrorCode(SRC_DIR)
    expect(existsSync).toHaveBeenCalledWith(`${SRC_DIR}/error.ts`)
  })

  it('does not include hasError=true when file is missing', async () => {
    const code = await generateErrorCode(SRC_DIR)
    expect(code).not.toContain('hasError = true')
  })

  it('does not include hasError=false when file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateErrorCode(SRC_DIR)
    expect(code).not.toContain('hasError = false')
  })

  it('ends with a newline', async () => {
    const code = await generateErrorCode(SRC_DIR)
    expect(code.endsWith('\n')).toBe(true)
  })

  it('ends with a newline when file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateErrorCode(SRC_DIR)
    expect(code.endsWith('\n')).toBe(true)
  })
})
