import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateLayoutsCode } from '../../../plugin/virtual/layouts.js'

const LAYOUTS = '/project/app/layouts'

describe('generateLayoutsCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns empty layouts when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('export const layouts = {}')
    expect(code).toContain('export default layouts')
  })

  it('returns empty layouts when no layout files found', async () => {
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('export const layouts = {}')
    expect(code).toContain('export default layouts')
  })

  it('includes AUTO-GENERATED comment', async () => {
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates a side-effect import for each layout file', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${LAYOUTS}/default.ts`])
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain(`import "${LAYOUTS}/default.ts"`)
  })

  it('generates layouts map with layout name and tag name', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${LAYOUTS}/default.ts`])
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('"default": "layout-default"')
  })

  it('handles multiple layouts', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${LAYOUTS}/default.ts`,
      `${LAYOUTS}/minimal.ts`,
    ])
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('"default": "layout-default"')
    expect(code).toContain('"minimal": "layout-minimal"')
  })

  it('handles nested layout files', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${LAYOUTS}/blog/post.ts`])
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('"blog-post": "layout-blog-post"')
  })

  it('exports layouts both as named and default export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${LAYOUTS}/default.ts`])
    const code = await generateLayoutsCode(LAYOUTS)
    expect(code).toContain('export const layouts')
    expect(code).toContain('export default layouts')
  })
})
