import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { generateLoadingCode } from '../../../plugin/virtual/loading.js'

const SRC_DIR = '/project/app'

describe('generateLoadingCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(false)
  })

  it('returns falsy exports when loading.ts does not exist', async () => {
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).toContain('export const hasLoading = false')
    expect(code).toContain('export const loadingTag = null')
  })

  it('includes AUTO-GENERATED comment when no loading file', async () => {
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('returns truthy exports when loading.ts exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).toContain('export const hasLoading = true')
    expect(code).toContain("export const loadingTag = 'page-loading'")
  })

  it('imports the loading file when it exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).toContain(`${SRC_DIR}/loading.ts`)
  })

  it('includes AUTO-GENERATED comment when loading file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('checks for loading.ts specifically', async () => {
    await generateLoadingCode(SRC_DIR)
    expect(existsSync).toHaveBeenCalledWith(`${SRC_DIR}/loading.ts`)
  })

  it('does not include hasLoading=true when file is missing', async () => {
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).not.toContain('hasLoading = true')
  })

  it('does not include hasLoading=false when file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateLoadingCode(SRC_DIR)
    expect(code).not.toContain('hasLoading = false')
  })

  it('ends with a newline when file is missing', async () => {
    const code = await generateLoadingCode(SRC_DIR)
    expect(code.endsWith('\n')).toBe(true)
  })

  it('ends with a newline when file exists', async () => {
    vi.mocked(existsSync).mockReturnValue(true)
    const code = await generateLoadingCode(SRC_DIR)
    expect(code.endsWith('\n')).toBe(true)
  })
})
