import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateMiddlewareCode } from '../../../plugin/virtual/middleware.js'

const MIDDLEWARE = '/project/app/middleware'

describe('generateMiddlewareCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns empty middleware when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain('export const middleware = {}')
    expect(code).toContain('export default middleware')
  })

  it('returns empty middleware when no files found', async () => {
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain('export const middleware = {}')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE}/auth.ts`])
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates default import and registers under filename key', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE}/auth.ts`])
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain(`import _m_auth from "${MIDDLEWARE}/auth.ts"`)
    expect(code).toContain('"auth": _m_auth')
  })

  it('creates a safe JS identifier for middleware names with dashes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE}/check-auth.ts`])
    const code = await generateMiddlewareCode(MIDDLEWARE)
    // Dashes replaced with underscores in the identifier
    expect(code).toContain('_m_check_auth')
    // Key in the map is the original name (without extension)
    expect(code).toContain('"check-auth"')
  })

  it('handles multiple middleware files', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${MIDDLEWARE}/auth.ts`,
      `${MIDDLEWARE}/logger.ts`,
    ])
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain('"auth": _m_auth')
    expect(code).toContain('"logger": _m_logger')
  })

  it('exports middleware as both named and default export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE}/auth.ts`])
    const code = await generateMiddlewareCode(MIDDLEWARE)
    expect(code).toContain('export const middleware')
    expect(code).toContain('export default middleware')
  })
})
