import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generatePluginsCode } from '../../../plugin/virtual/plugins.js'

const PLUGINS = '/project/app/plugins'

describe('generatePluginsCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns empty plugins when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('export const plugins = []')
    expect(code).toContain('export default plugins')
  })

  it('returns empty plugins when no files found', async () => {
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('export const plugins = []')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PLUGINS}/store.ts`])
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates default import with alias _p0 for first plugin', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PLUGINS}/01.store.ts`])
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain(`import _p0 from "${PLUGINS}/01.store.ts"`)
    expect(code).toContain('export const plugins = [_p0]')
  })

  it('generates aliased imports _p0, _p1 for two plugins', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/01.store.ts`,
      `${PLUGINS}/02.auth.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('import _p0 from')
    expect(code).toContain('import _p1 from')
    expect(code).toContain('export const plugins = [_p0, _p1]')
  })

  it('sorts plugins by numeric prefix before generating imports', async () => {
    // scanDirectory returns files unsorted — sortPluginFiles should sort them
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/02.auth.ts`,
      `${PLUGINS}/01.store.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS)
    // 01.store should appear first (_p0), 02.auth second (_p1)
    const storeIdx = code.indexOf(`"${PLUGINS}/01.store.ts"`)
    const authIdx = code.indexOf(`"${PLUGINS}/02.auth.ts"`)
    expect(storeIdx).toBeLessThan(authIdx)
  })

  it('unnumbered plugins come after numbered ones', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/zzz.ts`,
      `${PLUGINS}/01.first.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS)
    const firstIdx = code.indexOf(`"${PLUGINS}/01.first.ts"`)
    const zzzIdx = code.indexOf(`"${PLUGINS}/zzz.ts"`)
    expect(firstIdx).toBeLessThan(zzzIdx)
  })

  it('exports plugins as both named and default export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PLUGINS}/01.store.ts`])
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('export const plugins')
    expect(code).toContain('export default plugins')
  })

  // ─── .client.ts convention ────────────────────────────────────────────────

  it('includes .client.ts plugins by default (client-side)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/auth.ts`,
      `${PLUGINS}/cer-material.client.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS)
    expect(code).toContain('cer-material.client.ts')
    expect(code).toContain('auth.ts')
  })

  it('excludes .client.ts plugins when serverSafeOnly is true', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/auth.ts`,
      `${PLUGINS}/cer-material.client.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS, true)
    expect(code).not.toContain('cer-material.client.ts')
    expect(code).toContain('auth.ts')
  })

  it('returns empty plugins array when all plugins are .client.ts and serverSafeOnly is true', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/cer-material.client.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS, true)
    expect(code).toContain('export const plugins = []')
    expect(code).not.toContain('cer-material.client.ts')
  })

  it('preserves non-.client.ts plugins in server-safe mode', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PLUGINS}/01.analytics.ts`,
      `${PLUGINS}/02.fonts.client.ts`,
      `${PLUGINS}/03.auth.ts`,
    ])
    const code = await generatePluginsCode(PLUGINS, true)
    expect(code).toContain('01.analytics.ts')
    expect(code).toContain('03.auth.ts')
    expect(code).not.toContain('02.fonts.client.ts')
    // Two plugins remain: _p0 and _p1
    expect(code).toContain('export const plugins = [_p0, _p1]')
  })
})
