import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('node:fs/promises', () => ({ readFile: vi.fn().mockResolvedValue('') }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateRoutesCode } from '../../../plugin/virtual/routes.js'

const PAGES = '/project/app/pages'

describe('generateRoutesCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('returns empty routes when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('const routes = []')
    expect(code).toContain('export default routes')
  })

  it('returns empty routes when no files found', async () => {
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('const routes = []')
    expect(code).toContain('export default routes')
  })

  it('includes AUTO-GENERATED comment', async () => {
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates a lazy load() route for a static page', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/about\"')
    expect(code).toContain('load:')
    expect(code).toContain(`import("${PAGES}/about.ts")`)
    expect(code).toContain('"page-about"')
    // No eager static imports
    expect(code).not.toContain('import * as')
  })

  it('load() also forwards the page module loader export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('loader: mod.loader')
  })

  it('generates a lazy load() route for index.ts → /', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/index.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-index"')
  })

  it('generates a lazy load() route for a dynamic route', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/blog/[slug].ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/blog/:slug\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-blog-slug"')
  })

  it('generates a lazy load() route for a catch-all route', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/[...all].ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/:all*\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-all"')
  })

  it('sorts routes: static before dynamic before catch-all', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/[...all].ts`,
      `${PAGES}/[id].ts`,
      `${PAGES}/about.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    const aboutIdx = code.indexOf('\"/about\"')
    const idIdx = code.indexOf('\"/:id\"')
    const allIdx = code.indexOf('\"/:all*\"')
    expect(aboutIdx).toBeLessThan(idIdx)
    expect(idIdx).toBeLessThan(allIdx)
  })

  it('includes export default routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('export default routes')
  })

  it('generates multiple lazy routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/index.ts`,
      `${PAGES}/about.ts`,
      `${PAGES}/contact.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('\"/about\"')
    expect(code).toContain('\"/contact\"')
    expect(code).toContain('\"/\"')
    expect(code).not.toContain('import * as')
  })

  it('inlines middleware names and adds beforeEnter when middleware is present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div>Dashboard</div>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
    expect(code).toContain('virtual:cer-middleware')
  })

  it('omits beforeEnter when no middleware is declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)\nexport const meta = { layout: 'default' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('beforeEnter')
  })
})

// ─── meta.layout ─────────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.layout', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.layout when layout is declared in page source', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)\nexport const meta = { layout: 'minimal' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('meta: { layout: "minimal" }')
  })

  it('omits meta field when no layout is declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('meta:')
  })

  it('emits meta.layout alongside beforeEnter when both layout and middleware are present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { layout: 'admin', middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('meta: { layout: "admin" }')
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
  })
})

// ─── 404 page convention ──────────────────────────────────────────────────────

describe('generateRoutesCode — 404.ts convention', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('maps 404.ts to path /:all* (catch-all)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/404.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/:all*\"')
    expect(code).toContain('"page-404"')
  })

  it('sorts 404.ts catch-all after all other routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/404.ts`,
      `${PAGES}/about.ts`,
      `${PAGES}/[id].ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    const aboutIdx = code.indexOf('\"/about\"')
    const idIdx = code.indexOf('\"/:id\"')
    const allIdx = code.indexOf('\"/:all*\"')
    expect(aboutIdx).toBeLessThan(idIdx)
    expect(idIdx).toBeLessThan(allIdx)
  })
})
