import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('node:fs/promises', () => ({ readFile: vi.fn().mockResolvedValue('') }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateRoutesCode } from '../../../plugin/virtual/routes.js'

const PAGES = '/project/app/pages'

describe('generateRoutesCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('returns empty routes when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('const routes = []')
    expect(code).toContain('export default routes')
  })

  it('returns empty routes when no files found', async () => {
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('const routes = []')
    expect(code).toContain('export default routes')
  })

  it('includes AUTO-GENERATED comment', async () => {
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates a lazy load() route for a static page', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/about\"')
    expect(code).toContain('load:')
    expect(code).toContain(`import("${PAGES}/about.ts")`)
    expect(code).toContain('"page-about"')
    // No eager static imports
    expect(code).not.toContain('import * as')
  })

  it('load() also forwards the page module loader export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('loader: mod.loader')
  })

  it('generates a lazy load() route for index.ts → /', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/index.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-index"')
  })

  it('generates a lazy load() route for a dynamic route', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/blog/[slug].ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/blog/:slug\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-blog-slug"')
  })

  it('generates a lazy load() route for a catch-all route', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/[...all].ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/:all*\"')
    expect(code).toContain('load:')
    expect(code).toContain('"page-all"')
  })

  it('sorts routes: static before dynamic before catch-all', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/[...all].ts`,
      `${PAGES}/[id].ts`,
      `${PAGES}/about.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    const aboutIdx = code.indexOf('\"/about\"')
    const idIdx = code.indexOf('\"/:id\"')
    const allIdx = code.indexOf('\"/:all*\"')
    expect(aboutIdx).toBeLessThan(idIdx)
    expect(idIdx).toBeLessThan(allIdx)
  })

  it('includes export default routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('export default routes')
  })

  it('generates multiple lazy routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/index.ts`,
      `${PAGES}/about.ts`,
      `${PAGES}/contact.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('\"/about\"')
    expect(code).toContain('\"/contact\"')
    expect(code).toContain('\"/\"')
    expect(code).not.toContain('import * as')
  })

  it('inlines middleware names and adds beforeEnter when middleware is present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div>Dashboard</div>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
    expect(code).toContain('virtual:cer-middleware')
  })

  it('omits beforeEnter when no middleware is declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)\nexport const meta = { layout: 'default' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('beforeEnter')
  })

  it('uses return-value API (await handler) not callback-style (new Promise)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('await handler(to, from, next)')
    expect(code).not.toContain('new Promise')
  })

  it('passes a next() function as third arg to each middleware handler', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('const next = async () =>')
    expect(code).toContain('_calledNext = true')
  })

  it('runs downstream middleware when next() is called', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { middleware: ['logger', 'auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('_runNext')
    expect(code).toContain('"logger"')
    expect(code).toContain('"auth"')
  })

  it('wraps handler call in try-catch (blocks navigation on error)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('try {')
    expect(code).toContain('} catch (err) {')
    // New chain pattern: sets _guardResult = false and returns from the inner _runNext
    expect(code).toContain('_guardResult = false')
  })

  it('logs the middleware name in the error message', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('console.error')
    expect(code).toContain('Middleware')
    expect(code).toContain('err)')
  })
})

// ─── meta.layout ─────────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.layout', () => {
  beforeEach(() => {
    // Return true for directory existence checks but false for .error.ts and
    // _error.ts so resolveRouteErrorTag doesn't inject spurious errorTag fields
    // into routes that aren't testing error boundaries.
    vi.mocked(existsSync).mockImplementation((p: unknown) => {
      const path = String(p)
      if (path.endsWith('.error.ts') || path.endsWith('/_error.ts') || path.endsWith('\\_error.ts')) return false
      return true
    })
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.layout when layout is declared in page source', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)\nexport const meta = { layout: 'minimal' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('meta: { layout: "minimal" }')
  })

  it('omits meta field when no layout is declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('meta:')
  })

  it('emits meta.layout alongside beforeEnter when both layout and middleware are present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-dashboard', () => html\`<div/>\`)\nexport const meta = { layout: 'admin', middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('meta: { layout: "admin" }')
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
  })
})

// ─── 404 page convention ──────────────────────────────────────────────────────

describe('generateRoutesCode — 404.ts convention', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('maps 404.ts to path /:all* (catch-all)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/404.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('path: \"/:all*\"')
    expect(code).toContain('"page-404"')
  })

  it('sorts 404.ts catch-all after all other routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/404.ts`,
      `${PAGES}/about.ts`,
      `${PAGES}/[id].ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    const aboutIdx = code.indexOf('\"/about\"')
    const idIdx = code.indexOf('\"/:id\"')
    const allIdx = code.indexOf('\"/:all*\"')
    expect(aboutIdx).toBeLessThan(idIdx)
    expect(idIdx).toBeLessThan(allIdx)
  })
})

// ─── _layout.ts filtering ─────────────────────────────────────────────────────

describe('generateRoutesCode — _layout.ts filtering', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('excludes _layout.ts files from the generated routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/admin/index.ts`,
      `${PAGES}/admin/_layout.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('_layout')
    expect(code).toContain('/admin')
  })

  it('generates a route for non-underscore files in the same directory', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/admin/users.ts`,
      `${PAGES}/admin/_layout.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('/admin/users')
    expect(code).not.toContain('_layout')
  })
})

// ─── meta.revalidate ─────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.ssg.revalidate', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.ssg.revalidate when declared in page source', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/blog.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { ssg: { revalidate: 60 } }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('ssg: { revalidate: 60 }')
  })

  it('emits larger revalidate values correctly', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/products.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { ssg: { revalidate: 3600 } }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('ssg: { revalidate: 3600 }')
  })

  it('omits ssg meta when no revalidate is declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('revalidate')
  })

  it('can combine revalidate with layout in meta', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/blog.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { layout: 'minimal', ssg: { revalidate: 120 } }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('layout: "minimal"')
    expect(code).toContain('ssg: { revalidate: 120 }')
  })
})

// ─── meta.transition ─────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.transition', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.transition string when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { transition: 'fade' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('transition: "fade"')
  })

  it('emits meta.transition true (boolean) when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { transition: true }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('transition: true')
  })

  it('omits transition meta when not declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('transition')
  })

  it('emits meta.transition false (boolean) when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { transition: false }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('transition: false')
  })

  it('can combine transition with middleware', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { transition: 'slide', middleware: ['auth'] }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('transition: "slide"')
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
  })
})

// ─── meta.render ──────────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.render', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.render "server" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { render: 'server' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('render: "server"')
  })

  it('emits meta.render "spa" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/profile.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { render: 'spa' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('render: "spa"')
  })

  it('emits meta.render "static" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { render: 'static' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('render: "static"')
  })

  it('omits render meta when not declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('render:')
  })

  it('ignores unknown render values', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { render: 'unknown' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('render:')
  })

  it('can combine render with layout', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { render: 'server', layout: 'admin' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('render: "server"')
    expect(code).toContain('layout: "admin"')
  })
})

// ─── meta.hydrate ─────────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.hydrate', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.hydrate "idle" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'idle' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('hydrate: "idle"')
  })

  it('emits meta.hydrate "visible" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/hero.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'visible' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('hydrate: "visible"')
  })

  it('emits meta.hydrate "none" when declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/static-page.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'none' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('hydrate: "none"')
  })

  it('does NOT emit meta.hydrate when "load" (default — no-op)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'load' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('hydrate:')
  })

  it('omits hydrate meta when not declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('hydrate:')
  })

  it('ignores unknown hydrate values', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'lazy' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('hydrate:')
  })

  it('can combine hydrate with layout and render', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/dashboard.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { hydrate: 'idle', layout: 'minimal', render: 'server' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('hydrate: "idle"')
    expect(code).toContain('layout: "minimal"')
    expect(code).toContain('render: "server"')
  })
})

// ─── meta.title ───────────────────────────────────────────────────────────────

describe('generateRoutesCode — meta.title', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.title when declared in page source', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { title: 'About Us' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('title: "About Us"')
  })

  it('omits title meta when not declared', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `component('page-about', () => html\`<h1>About</h1>\`)` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('title:')
  })

  it('can combine title with layout', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { layout: 'minimal', title: 'About Us' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('layout: "minimal"')
    expect(code).toContain('title: "About Us"')
  })
})

// ─── nested layouts (layoutChain) ────────────────────────────────────────────

describe('generateRoutesCode — layoutChain (nested layouts)', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('emits meta.layoutChain when a _layout.ts exists in ancestor directory', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/admin/users.ts`])
    vi.mocked(readFile).mockImplementation(async (path: unknown) => {
      if (String(path).endsWith('_layout.ts')) return 'export default \'minimal\''
      return ''
    })
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('layoutChain:')
    expect(code).toContain('"default"')
    expect(code).toContain('"minimal"')
  })

  it('uses outerLayout from page meta when layoutChain is emitted', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/admin/users.ts`])
    vi.mocked(readFile).mockImplementation(async (path: unknown) => {
      const p = String(path)
      if (p.endsWith('_layout.ts')) return 'export default \'sidebar\''
      // page source has its own layout
      return `export const meta = { layout: 'clean' }`
    })
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('layoutChain:')
    expect(code).toContain('"clean"')
    expect(code).toContain('"sidebar"')
    // Should not emit a plain meta.layout — the chain replaces it
    expect(code).not.toContain('layout: "clean"')
  })

  it('omits layoutChain for top-level pages with no _layout.ts', async () => {
    vi.mocked(existsSync).mockImplementation((p: unknown) => {
      // Return false for any _layout.ts path so no chain is resolved
      if (String(p).endsWith('_layout.ts')) return false
      return true
    })
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    vi.mocked(readFile).mockResolvedValue(
      `export const meta = { layout: 'default' }` as never,
    )
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('layoutChain')
    expect(code).toContain('layout: "default"')
  })

  it('omits layoutChain for top-level pages even when existsSync returns true', async () => {
    // top-level page has no subdirectory segments, so resolveLayoutChain returns null immediately
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/index.ts`])
    vi.mocked(readFile).mockResolvedValue('' as never)
    const code = await generateRoutesCode(PAGES)
    expect(code).not.toContain('layoutChain')
  })
})

// ─── i18n route prefixing ─────────────────────────────────────────────────────

describe('generateRoutesCode — i18n route prefixing', () => {
  const i18nPrefix = { locales: ['en', 'fr'], defaultLocale: 'en', strategy: 'prefix' as const }
  const i18nPrefixExcept = { locales: ['en', 'fr'], defaultLocale: 'en', strategy: 'prefix_except_default' as const }
  const i18nNoPrefix = { locales: ['en', 'fr'], defaultLocale: 'en', strategy: 'no_prefix' as const }

  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('prefix strategy: generates /en/about and /fr/about for about.ts', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES, i18nPrefix)
    expect(code).toContain('"/en/about"')
    expect(code).toContain('"/fr/about"')
    expect(code).not.toContain('path: "/about"')
  })

  it('prefix_except_default strategy: generates /about and /fr/about for about.ts', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES, i18nPrefixExcept)
    expect(code).toContain('"/about"')
    expect(code).toContain('"/fr/about"')
    expect(code).not.toContain('"/en/about"')
  })

  it('no_prefix strategy: does not add locale prefixes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES, i18nNoPrefix)
    expect(code).toContain('"/about"')
    expect(code).not.toContain('"/en/about"')
    expect(code).not.toContain('"/fr/about"')
  })

  it('catch-all routes are never prefixed', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/404.ts`])
    const code = await generateRoutesCode(PAGES, i18nPrefix)
    expect(code).toContain('"/:all*"')
    expect(code).not.toContain('"/en/:all*"')
    expect(code).not.toContain('"/fr/:all*"')
  })

  it('emits meta.locale for each generated locale route', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES, i18nPrefix)
    expect(code).toContain('locale: "en"')
    expect(code).toContain('locale: "fr"')
  })

  it('without i18n config, generates a single route as before', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('"/about"')
    expect(code).not.toContain('"/en/about"')
    expect(code).not.toContain('locale:')
  })
})

// ─── P1-1: Synthetic 404 catch-all ───────────────────────────────────────────

describe('generateRoutesCode — synthetic 404 catch-all (P1-1)', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('adds a synthetic /:all* route when no user-defined catch-all exists', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    // Synthetic route uses single quotes in the generated code
    expect(code).toContain("path: '/:all*'")
    // Synthetic route returns default: null
    expect(code).toContain('default: null')
  })

  it('does NOT add a synthetic catch-all when a user 404.ts already exists', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/404.ts`, `${PAGES}/about.ts`])
    const code = await generateRoutesCode(PAGES)
    // Should have exactly one /:all* (the real 404 page, with double quotes)
    expect(code).toContain('"/:all*"')
    expect(code).not.toContain('default: null')
  })

  it('does NOT add a synthetic catch-all when a user [...all].ts already exists', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/[...all].ts`])
    const code = await generateRoutesCode(PAGES)
    // Real catch-all uses double quotes
    expect(code).toContain('"/:all*"')
    expect(code).not.toContain('default: null')
  })

  it('does not add a synthetic catch-all for an empty pages directory (no routes)', async () => {
    const code = await generateRoutesCode(PAGES)
    // Empty routes array — no synthetic catch-all needed when there are no routes
    expect(code).toContain('const routes = []')
    expect(code).not.toContain("path: '/:all*'")
  })
})

// ─── P2-1: _layout.ts group meta inheritance ─────────────────────────────────

describe('generateRoutesCode — group meta from _layout.ts (P2-1)', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('inherits middleware from ancestor _layout.ts when page has none', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/admin/dashboard.ts`])
    vi.mocked(readFile).mockImplementation(async (path: unknown) => {
      if (String(path).endsWith('_layout.ts')) {
        return `export const meta = { middleware: ['auth'] }`
      }
      return ''
    })
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('beforeEnter')
    expect(code).toContain('"auth"')
  })

  it('page-level middleware overrides group middleware from _layout.ts', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/admin/profile.ts`])
    vi.mocked(readFile).mockImplementation(async (path: unknown) => {
      if (String(path).endsWith('_layout.ts')) {
        return `export const meta = { middleware: ['auth'] }`
      }
      // page declares its own middleware
      return `export const meta = { middleware: ['verified'] }`
    })
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('"verified"')
    // Page overrides group — group middleware should NOT appear
    expect(code).not.toContain('"auth"')
  })

  it('inherits layout from ancestor _layout.ts meta.layout when page has no explicit layout', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${PAGES}/docs/intro.ts`])
    vi.mocked(readFile).mockImplementation(async (path: unknown) => {
      if (String(path).endsWith('_layout.ts')) {
        // _layout.ts exports meta.layout (group default layout)
        return `export const meta = { layout: 'docs' }`
      }
      return ''
    })
    const code = await generateRoutesCode(PAGES)
    // The layout from group meta should appear in the route
    expect(code).toContain('"docs"')
  })
})

// ─── P2-2: Per-route error tags ───────────────────────────────────────────────

describe('generateRoutesCode — per-route error tags (P2-2)', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
    vi.mocked(readFile).mockResolvedValue('' as never)
  })

  it('excludes *.error.ts files from generating their own routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/about.ts`,
      `${PAGES}/about.error.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    // The about route should exist
    expect(code).toContain('"/about"')
    // The error file must NOT produce a separate route path like /about-error or /about.error
    expect(code).not.toContain('path: "/about-error"')
    expect(code).not.toContain('path: "/about.error"')
  })

  it('excludes _error.ts files from generated routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/admin/users.ts`,
      `${PAGES}/admin/_error.ts`,
    ])
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('/admin/users')
    expect(code).not.toContain('_error')
  })

  it('load() includes co-located error file import when present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/dashboard.ts`,
      `${PAGES}/dashboard.error.ts`,
    ])
    vi.mocked(existsSync).mockImplementation((p: unknown) => {
      const path = String(p)
      // The co-located error file exists
      if (path.endsWith('dashboard.error.ts')) return true
      return true
    })
    const code = await generateRoutesCode(PAGES)
    // load() should import the error component alongside the page
    expect(code).toContain('dashboard.error.ts')
    expect(code).toContain('Promise.all')
  })

  it('emits meta.errorTag when co-located *.error.ts is present', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${PAGES}/settings.ts`,
      `${PAGES}/settings.error.ts`,
    ])
    vi.mocked(existsSync).mockImplementation((p: unknown) => {
      if (String(p).endsWith('settings.error.ts')) return true
      return true
    })
    const code = await generateRoutesCode(PAGES)
    expect(code).toContain('errorTag')
  })
})
