import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateServerMiddlewareCode } from '../../../plugin/virtual/server-middleware.js'

const MIDDLEWARE_DIR = '/project/server/middleware'

describe('generateServerMiddlewareCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns empty serverMiddleware when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('export const serverMiddleware = []')
    expect(code).toContain('export default serverMiddleware')
  })

  it('returns empty serverMiddleware when no files found', async () => {
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('export const serverMiddleware = []')
    expect(code).toContain('export default serverMiddleware')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/logger.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })

  it('generates import for a middleware file', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/logger.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain(`import _sm_logger from "${MIDDLEWARE_DIR}/logger.ts"`)
  })

  it('registers middleware with its name and handler', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/logger.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('name: "logger"')
    expect(code).toContain('handler: _sm_logger?.default ?? _sm_logger')
  })

  it('exports serverMiddleware as both named and default export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/logger.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('export const serverMiddleware = [')
    expect(code).toContain('export default serverMiddleware')
  })

  it('replaces dashes with underscores in the alias identifier', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/check-auth.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('_sm_check_auth')
    expect(code).toContain('name: "check-auth"')
  })

  it('prepends underscore to identifiers starting with a digit', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/1first.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('_sm__1first')
  })

  it('handles multiple middleware files', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${MIDDLEWARE_DIR}/logger.ts`,
      `${MIDDLEWARE_DIR}/auth.ts`,
    ])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('name: "auth"')
    expect(code).toContain('name: "logger"')
  })

  it('sorts middleware files alphabetically', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${MIDDLEWARE_DIR}/zz-last.ts`,
      `${MIDDLEWARE_DIR}/aa-first.ts`,
    ])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    const authIdx = code.indexOf('aa-first')
    const loggerIdx = code.indexOf('zz-last')
    expect(authIdx).toBeLessThan(loggerIdx)
  })

  it('ends with a newline', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${MIDDLEWARE_DIR}/logger.ts`])
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code.endsWith('\n')).toBe(true)
  })

  it('returns AUTO-GENERATED comment even when directory is missing', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateServerMiddlewareCode(MIDDLEWARE_DIR)
    expect(code).toContain('AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app')
  })
})
