import { vi, describe, it, expect, beforeEach } from 'vitest'

vi.mock('node:fs', () => ({ existsSync: vi.fn() }))
vi.mock('../../../plugin/scanner.js', () => ({ scanDirectory: vi.fn() }))

import { existsSync } from 'node:fs'
import { scanDirectory } from '../../../plugin/scanner.js'
import { generateServerApiCode } from '../../../plugin/virtual/server-api.js'

const API = '/project/server/api'

describe('generateServerApiCode', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(true)
    vi.mocked(scanDirectory).mockResolvedValue([])
  })

  it('returns empty apiRoutes when directory does not exist', async () => {
    vi.mocked(existsSync).mockReturnValue(false)
    const code = await generateServerApiCode(API)
    expect(code).toContain('export const apiRoutes = []')
    expect(code).toContain('export default apiRoutes')
  })

  it('returns empty apiRoutes when no files found', async () => {
    const code = await generateServerApiCode(API)
    expect(code).toContain('export const apiRoutes = []')
  })

  it('includes AUTO-GENERATED comment', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/health.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('AUTO-GENERATED by vite-plugin-cer-app')
  })

  it('prefixes route path with /api/', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/health.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('path: "/api/health"')
  })

  it('maps users/index.ts to /api/users', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/users/index.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('path: "/api/users"')
  })

  it('maps dynamic route [id].ts to /api/users/:id', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/users/[id].ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('path: "/api/users/:id"')
  })

  it('imports handlers as namespace (import * as)', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/health.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('import * as')
    expect(code).toContain(`"${API}/health.ts"`)
  })

  it('assigns handlers to each route entry', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/health.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('handlers:')
  })

  it('generates entries for multiple API routes', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([
      `${API}/health.ts`,
      `${API}/users/index.ts`,
      `${API}/users/[id].ts`,
    ])
    const code = await generateServerApiCode(API)
    expect(code).toContain('"/api/health"')
    expect(code).toContain('"/api/users"')
    expect(code).toContain('"/api/users/:id"')
  })

  it('exports apiRoutes as both named and default export', async () => {
    vi.mocked(scanDirectory).mockResolvedValue([`${API}/health.ts`])
    const code = await generateServerApiCode(API)
    expect(code).toContain('export const apiRoutes')
    expect(code).toContain('export default apiRoutes')
  })
})
