/**
 * Cloudflare Pages adapter.
 *
 * Transforms the cer-app `dist/` output into the files needed to deploy on
 * Cloudflare Pages with an edge-side SSR worker.
 *
 * SSR mode:
 *   - Reads dist/client/index.html and inlines it as a string constant in the
 *     generated `_worker.js` (Cloudflare Pages Advanced Mode convention).
 *     The worker sets globalThis.__CER_CLIENT_TEMPLATE__ before dynamically
 *     importing the server bundle, bypassing the node:fs call in server.js.
 *   - Bundles the server graph into _worker.js and removes server intermediates.
 *   - Copies public files to dist/; the worker forwards asset requests to ASSETS.
 *   - Writes `wrangler.toml` with nodejs_compat for AsyncLocalStorage + streams.
 *
 * SPA/SSG mode:
 *   - Copies static files to dist/ (already in correct layout after build).
 *   - Writes wrangler.toml pointing at dist/ with no function.
 *
 * Cloudflare Pages Advanced Mode (_worker.js) reference:
 *   https://developers.cloudflare.com/pages/functions/advanced-mode/
 *
 * nodejs_compat compatibility flag reference:
 *   https://developers.cloudflare.com/workers/runtime-apis/nodejs/
 */

import { join } from 'pathe'
import { requiresServer, prerenderedPaths, prerenderedFallback } from './deployment-mode.js'
import { WEB_BRIDGE } from './web-bridge.js'
import { build } from 'vite'
import { gzipSync } from 'node:zlib'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'

// ─── Worker bridge template ───────────────────────────────────────────────────

/**
 * Generates the _worker.js content with the client HTML inlined.
 *
 * Key design points:
 * - Sets globalThis.__CER_CLIENT_TEMPLATE__ BEFORE dynamically importing the
 *   server bundle so the bundle's module-init code sees the value instead of
 *   trying readFileSync (which throws in Workers without node:fs).
 * - Uses top-level await (supported in Cloudflare Workers ES modules).
 * - Mirrors the Netlify bridge's Web Request → Node.js mock → Response pattern;
 *   Cloudflare Workers with nodejs_compat support node:stream + AsyncLocalStorage.
 * - Responses are streamed via the Web Streams TransformStream API — chunks written
 *   by the SSR handler are forwarded to the client as they arrive rather than being
 *   buffered until the full page is rendered.
 * - Exports `{ fetch }` — the Cloudflare Pages _worker.js module format.
 */
function generateWorkerBridge(clientHtml: string, paths: string[], fallback?: boolean): string {
  // Escape the HTML for embedding in a JS template literal.
  const escaped = clientHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

  return `\
// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
// Cloudflare Pages _worker.js — Advanced Mode SSR bridge.
// Requires compatibility_flags = ["nodejs_compat"] in wrangler.toml.
import { Readable } from 'node:stream'
import { EventEmitter } from 'node:events'

// Inline the client HTML template so the server bundle does not need node:fs.
// Must be set before the dynamic import below resolves.
globalThis.__CER_CLIENT_TEMPLATE__ = \`${escaped}\`

const app = await import('./server/server.js')
${WEB_BRIDGE}
const paths = ${JSON.stringify(paths)}
const dispatchers = new WeakMap()
async function readDocument(path, req, assets) {
  let url = new URL(path, 'https://' + req.headers.host)
  for (let redirects = 0; redirects < 5; redirects++) {
    const response = await assets.fetch(new Request(url))
    const location = response.headers.get('location')
    if (response.status >= 300 && response.status < 400 && location) {
      await response.body?.cancel()
      const next = new URL(location, url)
      if (next.origin !== url.origin) return null
      url = next
      continue
    }
    if (response.status !== 200) { await response.body?.cancel(); return null }
    return response.text()
  }
  return null
}
function dispatcher(assets) {
  if (!assets || !app.createDispatchRequest) return app.dispatchRequest
  if (!dispatchers.has(assets)) dispatchers.set(assets, app.createDispatchRequest({ prerendered: {
    paths, fallback: ${JSON.stringify(fallback)},
    read: (path, req) => readDocument(path === '/' ? '/index.html' : path.split('/').map(encodeURIComponent).join('/') + '/index.html', req, assets),
    notFound: (req) => readDocument('/404.html', req, assets),
  } }))
  return dispatchers.get(assets)
}

export default {
  async fetch(request, env, _ctx) {
    let path
    try { path = decodeURIComponent(new URL(request.url).pathname) }
    catch { return new Response('Bad Request', { status: 400 }) }
    if (['server', 'client', '.vite'].includes(path.split('/')[1]) || ['/ssg-manifest.json', '/cer-client-manifest.json', '/cer-startup-manifest.json'].includes(path)) {
      return new Response('Not Found', { status: 404 })
    }
    // Advanced-mode workers own all requests, including static assets.
    if (env?.ASSETS && (request.method === 'GET' || request.method === 'HEAD') && !path.startsWith('/api/')) {
      const asset = await env.ASSETS.fetch(request)
      if (asset.status < 400 && !asset.headers.get('content-type')?.includes('text/html')) return asset
      await asset.body?.cancel()
    }
    return handleRequest(request, dispatcher(env?.ASSETS))
  },
}
`
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runCloudflareAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const isSSR = requiresServer(distDir)

  if (isSSR) {
    await _buildSSR(root, distDir)
  } else {
    _buildStatic(root, distDir)
  }

  console.log('[cer-app] Cloudflare adapter complete.')
  if (isSSR) {
    console.log('  Worker:  dist/_worker.js')
    console.log('  Static:  dist/')
    console.log('  Deploy with: wrangler pages deploy dist')
  } else {
    console.log('  Deploy with: wrangler pages deploy dist')
  }
}

// ─── SSR output ───────────────────────────────────────────────────────────────

async function _buildSSR(root: string, distDir: string): Promise<void> {
  const clientHtmlPath = join(distDir, 'client/index.html')
  const clientHtml = existsSync(clientHtmlPath)
    ? readFileSync(clientHtmlPath, 'utf-8')
    : ''

  // Write the worker bridge with inlined client HTML.
  const workerPath = join(distDir, '_worker.js')
  writeFileSync(workerPath, generateWorkerBridge(clientHtml, prerenderedPaths(distDir), prerenderedFallback(distDir)))

  // Bundle everything into the platform-reserved worker file. Leaving server/
  // in the public asset tree could expose source when the platform fails open.
  const result = await build({
    root, configFile: false, logLevel: 'error', ssr: { noExternal: true },
    build: { ssr: workerPath, write: false, target: 'es2022', minify: false,
      rollupOptions: { output: { inlineDynamicImports: true, entryFileNames: '_worker.js' } },
    },
  })
  const output = (Array.isArray(result) ? result[0] : result) as { output: Array<{ type: string; code?: string }> }
  const worker = output.output.find((item) => item.type === 'chunk')?.code
  if (!worker) throw new Error('[cer-app] Cloudflare bundling produced no worker')
  writeFileSync(workerPath, worker)
  const compressed = gzipSync(worker).byteLength
  console.log(`[cer-app] Cloudflare worker: ${Buffer.byteLength(worker)} bytes raw / ${compressed} bytes gzip`)
  // This is a framework advisory, not a claim about mutable platform plan limits.
  if (compressed > 1024 * 1024) console.warn('[cer-app] Cloudflare worker exceeds the 1 MiB gzip advisory budget; verify current platform size, startup and CPU limits before deployment.')

  // Copy assets from dist/client/ into dist/ (at the same URL paths).
  // Advanced-mode owns all requests and forwards public assets through ASSETS.
  // We deliberately skip index.html so HTML requests hit the SSR worker.
  _copyClientAssets(join(distDir, 'client'), distDir)
  for (const name of ['server', 'client', '.vite', 'ssg-manifest.json', 'cer-client-manifest.json', 'cer-startup-manifest.json']) rmSync(join(distDir, name), { recursive: true, force: true })
  writeFileSync(join(distDir, '_routes.json'), JSON.stringify({ version: 1, include: ['/*'], exclude: [] }, null, 2))

  // wrangler.toml: nodejs_compat for AsyncLocalStorage + node:stream support.
  _writeWranglerToml(root, true)
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(root: string, distDir: string): void {
  const clientDir = join(distDir, 'client')

  if (existsSync(clientDir)) {
    // SSG: pre-rendered HTML lives in dist/; assets in dist/client/.
    // Move assets alongside the HTML so Cloudflare Pages serves them correctly.
    _copyClientAssets(clientDir, distDir)
  }
  // Static deployment has no worker to protect build-only files.
  for (const name of ['server', 'client', '.vite', 'ssg-manifest.json', 'cer-client-manifest.json', 'cer-startup-manifest.json']) {
    rmSync(join(distDir, name), { recursive: true, force: true })
  }
  // SPA: everything is already in dist/ — nothing to reorganise.

  _writeWranglerToml(root, false)
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function _writeWranglerToml(root: string, ssrMode: boolean): void {
  const lines = [
    '# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.',
    'name = "cer-app"',
    // node:fs imports and a full process implementation are used by CER's
    // server graph even though document/content reads use embedded snapshots.
    'compatibility_date = "2025-09-15"',
  ]

  if (ssrMode) {
    lines.push('compatibility_flags = ["nodejs_compat"]')
  }

  lines.push('')
  lines.push('pages_build_output_dir = "dist"')
  lines.push('')

  writeFileSync(join(root, 'wrangler.toml'), lines.join('\n'))
}

/**
 * Copies Vite-hashed assets and other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html — served by the SSR worker or SSG pre-rendering.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })
  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html' || entry === '.vite') continue
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
