/**
 * Cloudflare Pages adapter.
 *
 * Transforms the cer-app `dist/` output into the files needed to deploy on
 * Cloudflare Pages with an edge-side SSR worker.
 *
 * SSR mode:
 *   - Reads dist/client/index.html and inlines it as a string constant in the
 *     generated `_worker.js` (Cloudflare Pages Advanced Mode convention).
 *     The worker sets globalThis.__CER_CLIENT_TEMPLATE__ before dynamically
 *     importing the server bundle, bypassing the node:fs call in server.js.
 *   - Copies content-hashed assets and other public files to dist/ alongside
 *     _worker.js — Cloudflare Pages serves them from the CDN before the worker.
 *   - Writes `wrangler.toml` with nodejs_compat for AsyncLocalStorage + streams.
 *
 * SPA/SSG mode:
 *   - Copies static files to dist/ (already in correct layout after build).
 *   - Writes wrangler.toml pointing at dist/ with no function.
 *
 * Cloudflare Pages Advanced Mode (_worker.js) reference:
 *   https://developers.cloudflare.com/pages/functions/advanced-mode/
 *
 * nodejs_compat compatibility flag reference:
 *   https://developers.cloudflare.com/workers/runtime-apis/nodejs/
 */

import { join } from 'pathe'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
} from 'node:fs'

// ─── Worker bridge template ───────────────────────────────────────────────────

/**
 * Generates the _worker.js content with the client HTML inlined.
 *
 * Key design points:
 * - Sets globalThis.__CER_CLIENT_TEMPLATE__ BEFORE dynamically importing the
 *   server bundle so the bundle's module-init code sees the value instead of
 *   trying readFileSync (which throws in Workers without node:fs).
 * - Uses top-level await (supported in Cloudflare Workers ES modules).
 * - Mirrors the Netlify bridge's Web Request → Node.js mock → Response pattern;
 *   Cloudflare Workers with nodejs_compat support node:stream + AsyncLocalStorage.
 * - Responses are streamed via the Web Streams TransformStream API — chunks written
 *   by the SSR handler are forwarded to the client as they arrive rather than being
 *   buffered until the full page is rendered.
 * - Exports `{ fetch }` — the Cloudflare Pages _worker.js module format.
 */
function generateWorkerBridge(clientHtml: string): string {
  // Escape the HTML for embedding in a JS template literal.
  const escaped = clientHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

  return `\
// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
// Cloudflare Pages _worker.js — Advanced Mode SSR bridge.
// Requires compatibility_flags = ["nodejs_compat"] in wrangler.toml.
import { Readable } from 'node:stream'

// Inline the client HTML template so the server bundle does not need node:fs.
// Must be set before the dynamic import below resolves.
globalThis.__CER_CLIENT_TEMPLATE__ = \`${escaped}\`

const { isrHandler, apiRoutes, runServerMiddleware, runWithRequestContext } = await import('./server/server.js')

function matchApiPattern(pattern, urlPath) {
  const pp = pattern.split('/')
  const up = urlPath.split('/')
  if (pp.length !== up.length) return null
  const params = {}
  for (let i = 0; i < pp.length; i++) {
    if (pp[i].startsWith(':')) params[pp[i].slice(1)] = decodeURIComponent(up[i])
    else if (pp[i] !== up[i]) return null
  }
  return params
}

function parseQuery(search) {
  if (!search) return {}
  const qs = search.startsWith('?') ? search.slice(1) : search
  const result = {}
  for (const part of qs.split('&')) {
    if (!part) continue
    const eqIdx = part.indexOf('=')
    if (eqIdx === -1) result[decodeURIComponent(part)] = ''
    else result[decodeURIComponent(part.slice(0, eqIdx))] = decodeURIComponent(part.slice(eqIdx + 1))
  }
  return result
}

async function toNodeRequest(webReq) {
  const url = new URL(webReq.url)
  const hasBody = webReq.body !== null
    && webReq.method !== 'GET'
    && webReq.method !== 'HEAD'
  const body = hasBody ? Buffer.from(await webReq.arrayBuffer()) : null
  const req = Object.assign(
    body ? Readable.from([body]) : Readable.from([]),
    {
      url: url.pathname + url.search,
      method: webReq.method,
      headers: Object.fromEntries(webReq.headers.entries()),
    },
  )
  req.query = parseQuery(url.search)
  if (body !== null) {
    const ct = webReq.headers.get('content-type') ?? ''
    if (ct.includes('application/json')) {
      try { req.body = JSON.parse(body.toString('utf-8')) } catch { req.body = undefined }
    } else {
      req.body = body
    }
  }
  return req
}

function createNodeResponse() {
  const { readable, writable } = new TransformStream()
  const writer = writable.getWriter()
  const encoder = new TextEncoder()
  const headers = {}
  let _resolve
  let _ended = false
  const promise = new Promise((res) => { _resolve = res })
  const res = {
    statusCode: 200,
    setHeader(name, value) { headers[name.toLowerCase()] = String(value) },
    getHeader(name) { return headers[name.toLowerCase()] },
    removeHeader(name) { delete headers[name.toLowerCase()] },
    write(chunk) {
      if (_ended) return
      void writer.write(typeof chunk === 'string' ? encoder.encode(chunk) : chunk).catch(() => {})
    },
    end(chunk) {
      if (_ended) return
      _ended = true
      if (chunk) void writer.write(typeof chunk === 'string' ? encoder.encode(chunk) : chunk).catch(() => {})
      void writer.close().catch(() => {})
      _resolve(new Response(readable, { status: res.statusCode, headers }))
    },
    json(data) {
      this.setHeader('Content-Type', 'application/json; charset=utf-8')
      this.end(JSON.stringify(data))
    },
    status(code) { this.statusCode = code; return this },
    get writableEnded() { return _ended },
  }
  return { res, promise }
}

async function handleRequest(webReq) {
  const url = new URL(webReq.url)
  const urlPath = url.pathname
  const method = webReq.method ?? 'GET'

  const nodeReq = await toNodeRequest(webReq)
  const { res, promise } = createNodeResponse()

  // Run server middleware chain (auth, logging, CORS, etc.).
  if (!(await runServerMiddleware(nodeReq, res))) return promise

  // Route /api/* requests to the API handlers exported by the server bundle.
  if (urlPath.startsWith('/api/')) {
    for (const route of (apiRoutes ?? [])) {
      const params = matchApiPattern(route.path, urlPath)
      if (params !== null) {
        nodeReq.params = params
        const fn = route.handlers[method.toLowerCase()]
          ?? route.handlers[method.toUpperCase()]
          ?? route.handlers['default']
        if (typeof fn === 'function') {
          // Wrap in request context so useCookie / useSession work in API handlers.
          runWithRequestContext(nodeReq, res, () => Promise.resolve(fn(nodeReq, res))).catch(() => {
            if (!res.writableEnded) {
              res.statusCode = 500
              res.end(JSON.stringify({ error: 'Internal Server Error' }))
            }
          })
          return promise
        }
      }
    }
    return new Response('Not Found', { status: 404 })
  }

  // All other requests: SSR (with ISR for routes that declare meta.ssg.revalidate).
  isrHandler(nodeReq, res).catch(() => {
    if (!res.writableEnded) {
      res.statusCode = 500
      res.end('Internal Server Error')
    }
  })
  return promise
}

export default {
  async fetch(request, _env, _ctx) {
    return handleRequest(request)
  },
}
`
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runCloudflareAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const serverBundle = join(distDir, 'server/server.js')
  const ssgManifest = join(distDir, 'ssg-manifest.json')
  const isSSR = existsSync(serverBundle) && !existsSync(ssgManifest)

  if (isSSR) {
    _buildSSR(root, distDir)
  } else {
    _buildStatic(root, distDir)
  }

  console.log('[cer-app] Cloudflare adapter complete.')
  if (isSSR) {
    console.log('  Worker:  dist/_worker.js')
    console.log('  Static:  dist/')
    console.log('  Deploy with: wrangler pages deploy dist')
  } else {
    console.log('  Deploy with: wrangler pages deploy dist')
  }
}

// ─── SSR output ───────────────────────────────────────────────────────────────

function _buildSSR(root: string, distDir: string): void {
  const clientHtmlPath = join(distDir, 'client/index.html')
  const clientHtml = existsSync(clientHtmlPath)
    ? readFileSync(clientHtmlPath, 'utf-8')
    : ''

  // Write the worker bridge with inlined client HTML.
  const workerPath = join(distDir, '_worker.js')
  writeFileSync(workerPath, generateWorkerBridge(clientHtml))

  // P1-4: Warn when the worker file approaches or exceeds Cloudflare's size limits.
  // Free plan: 1 MB compressed; Paid plan: 10 MB compressed. Check uncompressed as
  // a conservative proxy — the compressed size will always be smaller.
  const workerSizeBytes = statSync(workerPath).size
  const WARN_LIMIT = 900_000   // 900 KB — approaching Free plan limit
  const ERROR_LIMIT = 9_000_000  // 9 MB — approaching Paid plan limit
  if (workerSizeBytes > ERROR_LIMIT) {
    console.error(
      `[cer-app] Cloudflare _worker.js is ${(workerSizeBytes / 1e6).toFixed(1)} MB — ` +
      `exceeds the ${(ERROR_LIMIT / 1e6).toFixed(0)} MB limit. Deployment will likely fail.`,
    )
    process.exit(1)
  } else if (workerSizeBytes > WARN_LIMIT) {
    console.warn(
      `[cer-app] Cloudflare _worker.js is ${(workerSizeBytes / 1e3).toFixed(0)} KB — ` +
      `approaching the Cloudflare Free plan 1 MB limit. Consider the Paid plan or reducing bundle size.`,
    )
  }

  // Copy assets from dist/client/ into dist/ (at the same URL paths).
  // Cloudflare Pages CDN serves files in the deploy directory as static first;
  // requests that don't match a static file fall through to _worker.js.
  // We deliberately skip index.html so HTML requests hit the SSR worker.
  _copyClientAssets(join(distDir, 'client'), distDir)

  // wrangler.toml: nodejs_compat for AsyncLocalStorage + node:stream support.
  _writeWranglerToml(root, true)
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(root: string, distDir: string): void {
  const clientDir = join(distDir, 'client')

  if (existsSync(clientDir)) {
    // SSG: pre-rendered HTML lives in dist/; assets in dist/client/.
    // Move assets alongside the HTML so Cloudflare Pages serves them correctly.
    _copyClientAssets(clientDir, distDir)
  }
  // SPA: everything is already in dist/ — nothing to reorganise.

  _writeWranglerToml(root, false)
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function _writeWranglerToml(root: string, ssrMode: boolean): void {
  const lines = [
    '# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.',
    'name = "cer-app"',
    'compatibility_date = "2024-09-23"',
  ]

  if (ssrMode) {
    lines.push('compatibility_flags = ["nodejs_compat"]')
  }

  lines.push('')
  lines.push('[pages_build_output_dir]')
  lines.push('dir = "dist"')
  lines.push('')

  writeFileSync(join(root, 'wrangler.toml'), lines.join('\n'))
}

/**
 * Copies Vite-hashed assets and other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html — served by the SSR worker or SSG pre-rendering.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })
  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html') continue
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
