/**
 * Netlify adapter.
 *
 * Transforms the cer-app `dist/` output into the files needed to deploy on
 * Netlify.
 *
 * SSR mode:
 *   - Writes a `netlify/functions/ssr.mjs` bridge that converts Netlify
 *     Functions v2 Web API (Request/Response) to the Node.js-style handler
 *     used by the cer-app server bundle.  Handles /api/* routing inline.
 *   - Creates `.netlify/publish/` with content-hashed assets only (no HTML),
 *     so Netlify's CDN serves static files and everything else falls through
 *     to the SSR function.
 *   - Writes `netlify.toml` with the publish directory and catch-all redirect.
 *
 * SPA/SSG mode:
 *   - Writes `netlify.toml` that points to the correct publish directory and
 *     adds a SPA fallback redirect (/* → /index.html).
 *
 * Responses are streamed via the Web Streams TransformStream API — chunks written
 * by the SSR handler are forwarded to the client as they arrive rather than being
 * buffered until the full page is rendered.
 * All other behaviour (cookies, headers, API routes, ISR) is fully supported.
 */

import { join } from 'pathe'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'

// ─── SSR function bridge template ────────────────────────────────────────────

/**
 * Netlify Functions v2 bridge.
 *
 * The function:
 * 1. Converts the incoming Web API Request to a mock Node.js IncomingMessage.
 * 2. Creates a streaming mock ServerResponse backed by a TransformStream.
 *    Chunks written via res.write() are enqueued into the stream immediately;
 *    res.end() closes the stream and resolves the Promise with a streaming
 *    Web API Response. The platform receives the Response body as a ReadableStream
 *    so bytes flow to the client as they are written — no full-page buffering.
 * 3. Routes /api/* to the API handlers, everything else to the SSR handler.
 *
 * The server bundle is imported using a path relative to the function file
 * location: netlify/functions/ssr.mjs → ../../dist/server/server.js.
 */
const NETLIFY_SSR_BRIDGE = `\
// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
import { Readable } from 'node:stream'
import { isrHandler, apiRoutes, runServerMiddleware, runWithRequestContext } from '../../dist/server/server.js'

function matchApiPattern(pattern, urlPath) {
  const pp = pattern.split('/')
  const up = urlPath.split('/')
  if (pp.length !== up.length) return null
  const params = {}
  for (let i = 0; i < pp.length; i++) {
    if (pp[i].startsWith(':')) params[pp[i].slice(1)] = decodeURIComponent(up[i])
    else if (pp[i] !== up[i]) return null
  }
  return params
}

function parseQuery(search) {
  if (!search) return {}
  const qs = search.startsWith('?') ? search.slice(1) : search
  const result = {}
  for (const part of qs.split('&')) {
    if (!part) continue
    const eqIdx = part.indexOf('=')
    if (eqIdx === -1) result[decodeURIComponent(part)] = ''
    else result[decodeURIComponent(part.slice(0, eqIdx))] = decodeURIComponent(part.slice(eqIdx + 1))
  }
  return result
}

async function toNodeRequest(webReq) {
  const url = new URL(webReq.url)
  const hasBody = webReq.body !== null
    && webReq.method !== 'GET'
    && webReq.method !== 'HEAD'
  const body = hasBody ? Buffer.from(await webReq.arrayBuffer()) : null
  const req = Object.assign(
    body ? Readable.from([body]) : Readable.from([]),
    {
      url: url.pathname + url.search,
      method: webReq.method,
      headers: Object.fromEntries(webReq.headers.entries()),
    },
  )
  req.query = parseQuery(url.search)
  if (body !== null) {
    const ct = webReq.headers.get('content-type') ?? ''
    if (ct.includes('application/json')) {
      try { req.body = JSON.parse(body.toString('utf-8')) } catch { req.body = undefined }
    } else {
      req.body = body
    }
  }
  return req
}

function createNodeResponse() {
  const { readable, writable } = new TransformStream()
  const writer = writable.getWriter()
  const encoder = new TextEncoder()
  const headers = {}
  let _resolve
  let _ended = false
  const promise = new Promise((res) => { _resolve = res })
  const res = {
    statusCode: 200,
    setHeader(name, value) { headers[name.toLowerCase()] = String(value) },
    getHeader(name) { return headers[name.toLowerCase()] },
    removeHeader(name) { delete headers[name.toLowerCase()] },
    write(chunk) {
      if (_ended) return
      void writer.write(typeof chunk === 'string' ? encoder.encode(chunk) : chunk).catch(() => {})
    },
    end(chunk) {
      if (_ended) return
      _ended = true
      if (chunk) void writer.write(typeof chunk === 'string' ? encoder.encode(chunk) : chunk).catch(() => {})
      void writer.close().catch(() => {})
      _resolve(new Response(readable, { status: res.statusCode, headers }))
    },
    // Helpers expected by API route handlers.
    json(data) {
      this.setHeader('Content-Type', 'application/json; charset=utf-8')
      this.end(JSON.stringify(data))
    },
    status(code) { this.statusCode = code; return this },
    get writableEnded() { return _ended },
  }
  return { res, promise }
}

export default async (webReq) => {
  const url = new URL(webReq.url)
  const urlPath = url.pathname
  const method = webReq.method ?? 'GET'

  // Convert to Node.js-style req/res upfront so server middleware can run.
  const nodeReq = await toNodeRequest(webReq)
  const { res, promise } = createNodeResponse()

  // Run server middleware chain (auth, logging, CORS, etc.).
  if (!(await runServerMiddleware(nodeReq, res))) return promise

  // Route /api/* requests to the API handlers exported by the server bundle.
  if (urlPath.startsWith('/api/')) {
    for (const route of (apiRoutes ?? [])) {
      const params = matchApiPattern(route.path, urlPath)
      if (params !== null) {
        nodeReq.params = params
        const fn = route.handlers[method.toLowerCase()]
          ?? route.handlers[method.toUpperCase()]
          ?? route.handlers['default']
        if (typeof fn === 'function') {
          // Wrap in request context so useCookie / useSession work in API handlers.
          runWithRequestContext(nodeReq, res, () => Promise.resolve(fn(nodeReq, res))).catch(() => {
            if (!res.writableEnded) {
              res.statusCode = 500
              res.end(JSON.stringify({ error: 'Internal Server Error' }))
            }
          })
          return promise
        }
      }
    }
    return new Response('Not Found', { status: 404 })
  }

  // All other requests: SSR (with ISR for routes that declare meta.ssg.revalidate).
  isrHandler(nodeReq, res).catch(() => {
    if (!res.writableEnded) {
      res.statusCode = 500
      res.end('Internal Server Error')
    }
  })
  return promise
}
`

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runNetlifyAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const serverBundle = join(distDir, 'server/server.js')
  const ssgManifest = join(distDir, 'ssg-manifest.json')
  const isSSR = existsSync(serverBundle) && !existsSync(ssgManifest)

  if (isSSR) {
    _buildSSR(root, distDir)
  } else {
    _buildStatic(root, distDir)
  }

  console.log('[cer-app] Netlify adapter complete.')
  if (isSSR) {
    console.log('  Function: netlify/functions/ssr.mjs')
    console.log('  Static:   .netlify/publish/')
    console.log('  Deploy with: netlify deploy')
  } else {
    console.log('  Deploy with: netlify deploy')
  }
}

// ─── SSR output ───────────────────────────────────────────────────────────────

function _buildSSR(root: string, distDir: string): void {
  // Write the SSR bridge function.
  const functionsDir = join(root, 'netlify/functions')
  mkdirSync(functionsDir, { recursive: true })
  writeFileSync(join(functionsDir, 'ssr.mjs'), NETLIFY_SSR_BRIDGE)

  // Build the static publish directory with assets only (no HTML).
  // Netlify serves files in the publish directory as static responses first.
  // By omitting index.html we ensure all HTML routes fall through to the
  // SSR function instead of being served as stale static files.
  const publishDir = join(root, '.netlify/publish')
  if (existsSync(publishDir)) {
    rmSync(publishDir, { recursive: true, force: true })
  }
  _copyClientAssets(join(distDir, 'client'), publishDir)

  // netlify.toml: publish directory + cache headers + catch-all to SSR function.
  writeFileSync(
    join(root, 'netlify.toml'),
    `# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
[build]
  publish = ".netlify/publish"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
`,
  )
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(root: string, distDir: string): void {
  const clientDir = join(distDir, 'client')
  let publishDir: string

  if (existsSync(clientDir)) {
    // SSG: HTML in dist/, assets in dist/client/. Merge into .netlify/publish/.
    publishDir = join(root, '.netlify/publish')
    if (existsSync(publishDir)) {
      rmSync(publishDir, { recursive: true, force: true })
    }
    // Copy pre-rendered HTML from dist/ (skip client/ sub-dir and manifest).
    cpSync(distDir, publishDir, {
      recursive: true,
      filter: (src) =>
        src !== clientDir && !src.endsWith('ssg-manifest.json'),
    })
    // Copy assets from dist/client/ into the publish root.
    _copyClientAssets(clientDir, publishDir)
  } else {
    // SPA: everything is in dist/ at correct URL paths already.
    publishDir = 'dist'
  }

  // netlify.toml: SPA fallback redirect.
  writeFileSync(
    join(root, 'netlify.toml'),
    `# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
[build]
  publish = "${publishDir.startsWith(root) ? publishDir.slice(root.length + 1) : publishDir}"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`,
  )
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Copies content-hashed assets and other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html so it is never served as a static file in SSR mode.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })
  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html') continue
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
