/**
 * Netlify adapter.
 *
 * Transforms the cer-app `dist/` output into the files needed to deploy on
 * Netlify.
 *
 * SSR mode:
 *   - Writes a `netlify/functions/ssr.mjs` bridge that converts Netlify
 *     Functions v2 Web API (Request/Response) to the Node.js-style handler
 *     used by the cer-app server bundle. Delegates routing to dispatchRequest.
 *   - Creates `.netlify/publish/` with public assets and generated metadata
 *     (including form registration HTML, but excluding routed documents),
 *     so Netlify's CDN serves static files and everything else falls through
 *     to the SSR function.
 *   - Writes `netlify.toml` with the publish directory and catch-all redirect.
 *
 * SPA/SSG mode:
 *   - Writes `netlify.toml` with a filtered SSG publish directory and 404
 *     fallback, or a SPA publish directory and app-shell fallback.
 *
 * Responses are streamed via the Web Streams TransformStream API — chunks written
 * by the SSR handler are forwarded to the client as they arrive rather than being
 * buffered until the full page is rendered.
 * All other behaviour (cookies, headers, API routes, ISR) is fully supported.
 */

import { join } from 'pathe'
import { requiresServer, isPublicBuildFile, nodeDispatcherSource, copyGeneratedPublicFiles } from './deployment-mode.js'
import { WEB_BRIDGE } from './web-bridge.js'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'

// ─── SSR function bridge template ────────────────────────────────────────────

/**
 * Netlify Functions v2 bridge.
 *
 * The function:
 * 1. Converts the incoming Web API Request to a mock Node.js IncomingMessage.
 * 2. Creates a streaming mock ServerResponse backed by a TransformStream.
 *    Chunks written via res.write() are enqueued into the stream immediately;
 *    The first header/body write resolves the streaming Web API Response;
 *    res.end() closes its body. The platform receives a ReadableStream
 *    so bytes flow to the client as they are written — no full-page buffering.
 * 3. Calls the shared dispatcher for middleware, API, SPA and SSR/ISR routing.
 *
 * The server bundle is imported using a path relative to the function file
 * location: netlify/functions/ssr.mjs → ../../dist/server/server.js.
 */
function netlifyBridge(distDir: string): string {
  return `// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
import { Readable } from 'node:stream'
import { EventEmitter } from 'node:events'
import { readFileSync } from 'node:fs'
import * as app from '../../dist/server/server.js'
${nodeDispatcherSource(distDir, '../../dist/')}
${WEB_BRIDGE}
export default async (webReq) => handleRequest(webReq, dispatchRequest)
`
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runNetlifyAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const isSSR = requiresServer(distDir)

  if (isSSR) {
    _buildSSR(root, distDir)
  } else {
    _buildStatic(root, distDir)
  }

  console.log('[cer-app] Netlify adapter complete.')
  if (isSSR) {
    console.log('  Function: netlify/functions/ssr.mjs')
    console.log('  Static:   .netlify/publish/')
    console.log('  Deploy with: netlify deploy')
  } else {
    console.log('  Deploy with: netlify deploy')
  }
}

// ─── SSR output ───────────────────────────────────────────────────────────────

function _buildSSR(root: string, distDir: string): void {
  // Write the SSR bridge function.
  const functionsDir = join(root, 'netlify/functions')
  mkdirSync(functionsDir, { recursive: true })
  writeFileSync(join(functionsDir, 'ssr.mjs'), netlifyBridge(distDir))

  // Build the static publish directory with assets only (no HTML).
  // Netlify serves files in the publish directory as static responses first.
  // By omitting index.html we ensure all HTML routes fall through to the
  // SSR function instead of being served as stale static files.
  const publishDir = join(root, '.netlify/publish')
  if (existsSync(publishDir)) {
    rmSync(publishDir, { recursive: true, force: true })
  }
  _copyClientAssets(join(distDir, 'client'), publishDir)
  copyGeneratedPublicFiles(distDir, publishDir)

  // netlify.toml: publish directory + cache headers + catch-all to SSR function.
  writeFileSync(
    join(root, 'netlify.toml'),
    `# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
[build]
  publish = ".netlify/publish"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
`,
  )
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(root: string, distDir: string): void {
  const clientDir = join(distDir, 'client')
  const isSsg = existsSync(join(distDir, 'ssg-manifest.json'))
  let publishDir: string

  if (existsSync(clientDir) || isSsg) {
    // SSG: HTML in dist/, assets in dist/client/. Merge into .netlify/publish/.
    publishDir = join(root, '.netlify/publish')
    if (existsSync(publishDir)) {
      rmSync(publishDir, { recursive: true, force: true })
    }
    // Copy pre-rendered HTML from dist/ (skip client/ sub-dir and manifest).
    cpSync(distDir, publishDir, {
      recursive: true,
      filter: (src) => isPublicBuildFile(distDir, src),
    })
    // Copy assets from dist/client/ into the publish root.
    _copyClientAssets(clientDir, publishDir)
  } else {
    // SPA: everything is in dist/ at correct URL paths already.
    publishDir = 'dist'
  }

  // Serve the app shell for unmatched paths. SSG misses retain a real 404
  // status so custom client-side not-found pages are not soft 404s.
  writeFileSync(
    join(root, 'netlify.toml'),
    `# Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
[build]
  publish = "${publishDir.startsWith(root) ? publishDir.slice(root.length + 1) : publishDir}"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "${isSsg ? "/404.html" : "/index.html"}"
  status = ${isSsg ? 404 : 200}
`,
  )
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Copies content-hashed assets and other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html so it is never served as a static file in SSR mode.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })
  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html' || entry === '.vite') continue
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
