/**
 * Vercel Build Output API v3 adapter.
 *
 * Transforms the cer-app `dist/` output into a `.vercel/output/` directory
 * that can be deployed with `vercel deploy --prebuilt`.
 *
 * SSR mode:
 *   - Copies dist/server/server.js into a Vercel Serverless Function
 *   - Copies dist/client/index.html alongside the server bundle so the
 *     `../client/index.html` relative path in the bundle resolves correctly
 *   - Copies content-hashed assets to .vercel/output/static/ for CDN delivery
 *   - Writes a launcher (index.js) that routes /api/* to the API handlers and
 *     forwards all other requests to the SSR handler
 *
 * SPA/SSG mode:
 *   - Copies all static files to .vercel/output/static/
 *   - Writes a config.json with SPA fallback (serve index.html for unknown paths)
 */

import { join } from 'pathe'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'

// ─── Launcher template ────────────────────────────────────────────────────────

/**
 * Vercel serverless function entry point.
 * Handles /api/* routing and falls through to the SSR handler for all other
 * requests. Imported by Vercel's Node.js launcher via the handler export.
 *
 * The server bundle lives at ./server/server.js so its own ../client/index.html
 * reference resolves to ./client/index.html — both files are copied into the
 * function directory by the adapter.
 */
const VERCEL_LAUNCHER = `\
// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
import { handler, apiRoutes, runServerMiddleware, runWithRequestContext } from './server/server.js'

function matchApiPattern(pattern, urlPath) {
  const pp = pattern.split('/')
  const up = urlPath.split('/')
  if (pp.length !== up.length) return null
  const params = {}
  for (let i = 0; i < pp.length; i++) {
    if (pp[i].startsWith(':')) params[pp[i].slice(1)] = decodeURIComponent(up[i])
    else if (pp[i] !== up[i]) return null
  }
  return params
}

function parseQuery(url) {
  const qIndex = url.indexOf('?')
  if (qIndex === -1) return {}
  const qs = url.slice(qIndex + 1)
  const result = {}
  for (const part of qs.split('&')) {
    if (!part) continue
    const eqIdx = part.indexOf('=')
    if (eqIdx === -1) result[decodeURIComponent(part)] = ''
    else result[decodeURIComponent(part.slice(0, eqIdx))] = decodeURIComponent(part.slice(eqIdx + 1))
  }
  return result
}

async function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = []
    req.on('data', chunk => chunks.push(Buffer.from(chunk)))
    req.on('end', () => resolve(Buffer.concat(chunks)))
    req.on('error', reject)
  })
}

async function parseBody(req) {
  const contentType = req.headers['content-type'] ?? ''
  const method = req.method?.toUpperCase() ?? 'GET'
  if (!['POST', 'PUT', 'PATCH'].includes(method)) return undefined
  const buf = await readBody(req)
  if (contentType.includes('application/json')) {
    try { return JSON.parse(buf.toString('utf-8')) } catch { return undefined }
  }
  return buf
}

export default async function cerAppHandler(req, res) {
  // Run server middleware chain (auth, logging, CORS, etc.).
  if (!(await runServerMiddleware(req, res))) return

  const urlPath = (req.url ?? '/').split('?')[0]
  const method = req.method ?? 'GET'

  // Route /api/* to API handlers exported by the server bundle.
  if (urlPath.startsWith('/api/')) {
    for (const route of (apiRoutes ?? [])) {
      const params = matchApiPattern(route.path, urlPath)
      if (params !== null) {
        req.params = params
        req.query = parseQuery(req.url ?? '/')
        req.body = await parseBody(req)
        res.json = function (data) {
          this.setHeader('Content-Type', 'application/json; charset=utf-8')
          this.end(JSON.stringify(data))
        }
        res.status = function (code) { this.statusCode = code; return this }
        const fn = route.handlers[method.toLowerCase()]
          ?? route.handlers[method.toUpperCase()]
          ?? route.handlers['default']
        if (typeof fn === 'function') {
          try {
            await runWithRequestContext(req, res, () => Promise.resolve(fn(req, res)))
          } catch {
            if (!res.writableEnded) {
              res.statusCode = 500
              res.setHeader('Content-Type', 'application/json')
              res.end(JSON.stringify({ error: 'Internal Server Error' }))
            }
          }
          return
        }
      }
    }
    res.statusCode = 404
    res.end('Not Found')
    return
  }

  // All other requests: SSR.
  await handler(req, res)
}
`

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runVercelAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const serverBundle = join(distDir, 'server/server.js')
  const ssgManifest = join(distDir, 'ssg-manifest.json')
  const isSSR = existsSync(serverBundle) && !existsSync(ssgManifest)

  const outDir = join(root, '.vercel/output')

  // Clean existing Vercel output to avoid stale files.
  if (existsSync(outDir)) {
    rmSync(outDir, { recursive: true, force: true })
  }
  mkdirSync(outDir, { recursive: true })

  if (isSSR) {
    _buildSSR(distDir, outDir)
  } else {
    _buildStatic(distDir, outDir)
  }

  console.log('[cer-app] Vercel adapter complete — output written to .vercel/output/')
  console.log('  Deploy with: vercel deploy --prebuilt')
}

// ─── SSR output ───────────────────────────────────────────────────────────────

function _buildSSR(distDir: string, outDir: string): void {
  const funcDir = join(outDir, 'functions/index.func')

  // Maintain the server/ → ../client/ relative layout so the server bundle's
  // built-in `../client/index.html` reference resolves correctly.
  mkdirSync(join(funcDir, 'server'), { recursive: true })
  mkdirSync(join(funcDir, 'client'), { recursive: true })

  // Server bundle.
  copyFileSync(join(distDir, 'server/server.js'), join(funcDir, 'server/server.js'))

  // Client HTML template (referenced as ../client/index.html from server.js).
  const clientHtml = join(distDir, 'client/index.html')
  if (existsSync(clientHtml)) {
    copyFileSync(clientHtml, join(funcDir, 'client/index.html'))
  }

  // Launcher: routes API requests + forwards the rest to the SSR handler.
  writeFileSync(join(funcDir, 'index.js'), VERCEL_LAUNCHER)

  // package.json: mark the function directory as ESM so Node.js treats .js
  // files as ES modules (the server bundle uses import.meta.url, etc.).
  writeFileSync(join(funcDir, 'package.json'), '{"type":"module"}\n')

  // Vercel function config.
  writeFileSync(
    join(funcDir, '.vc-config.json'),
    JSON.stringify(
      {
        runtime: 'nodejs20.x',
        handler: 'index.js',
        launcherType: 'Nodejs',
      },
      null,
      2,
    ) + '\n',
  )

  // Static assets: content-hashed files served by the Vercel CDN.
  const staticDir = join(outDir, 'static')
  _copyClientAssets(join(distDir, 'client'), staticDir)

  // Vercel output routes config.
  writeFileSync(
    join(outDir, 'config.json'),
    JSON.stringify(
      {
        version: 3,
        routes: [
          // Apply immutable cache headers to content-hashed assets then continue
          // (so the filesystem handler can still serve them as static files).
          {
            src: '/assets/(.*)',
            headers: { 'cache-control': 'public, max-age=31536000, immutable' },
            continue: true,
          },
          // Serve matched static files from .vercel/output/static/.
          { handle: 'filesystem' },
          // Fall through to the SSR function for all other paths.
          { src: '/(.*)', dest: '/index' },
        ],
      },
      null,
      2,
    ) + '\n',
  )
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(distDir: string, outDir: string): void {
  const staticDir = join(outDir, 'static')
  mkdirSync(staticDir, { recursive: true })

  const clientDir = join(distDir, 'client')

  if (existsSync(clientDir)) {
    // SSG: pre-rendered HTML lives in dist/, assets in dist/client/.
    // Copy HTML (and any other root-level files) from dist/ — skip client/ dir
    // and ssg-manifest.json which are build artifacts, not deployable content.
    cpSync(distDir, staticDir, {
      recursive: true,
      filter: (src) =>
        src !== clientDir && !src.endsWith('ssg-manifest.json'),
    })
    // Copy assets and other non-HTML files from dist/client/ into static root
    // so URLs like /assets/main.abc123.js resolve correctly.
    _copyClientAssets(clientDir, staticDir)
  } else {
    // SPA: everything is in dist/ at the correct paths already.
    cpSync(distDir, staticDir, { recursive: true })
  }

  // Vercel output config: serve static files, fall back to index.html (SPA).
  writeFileSync(
    join(outDir, 'config.json'),
    JSON.stringify(
      {
        version: 3,
        routes: [
          {
            src: '/assets/(.*)',
            headers: { 'cache-control': 'public, max-age=31536000, immutable' },
            continue: true,
          },
          { handle: 'filesystem' },
          // SPA fallback: serve index.html for any unmatched path.
          { src: '/(.*)', dest: '/index.html' },
        ],
      },
      null,
      2,
    ) + '\n',
  )
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Copies Vite-hashed assets and any other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html — that is handled by the SSR function or SSG pre-rendering.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })

  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html') continue // served by function / SSG HTML
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
