/**
 * Vercel Build Output API v3 adapter.
 *
 * Transforms the cer-app `dist/` output into a `.vercel/output/` directory
 * that can be deployed with `vercel deploy --prebuilt`.
 *
 * SSR mode:
 *   - Bundles the server graph into a Vercel Serverless Function
 *   - Copies dist/client/index.html alongside the server bundle so the
 *     `../client/index.html` relative path in the bundle resolves correctly
 *   - Copies content-hashed assets to .vercel/output/static/ for CDN delivery
 *   - Writes a launcher (index.js) that exports the shared server dispatcher
 *
 * SPA/SSG mode:
 *   - Copies all static files to .vercel/output/static/
 *   - Writes a config.json with SPA fallback (serve index.html for unknown paths)
 */

import { join } from 'pathe'
import { build } from 'vite'
import { requiresServer, isPublicBuildFile, nodeDispatcherSource, copyPrerenderedDocuments, copyGeneratedPublicFiles } from './deployment-mode.js'
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  copyFileSync,
  cpSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'

// ─── Launcher template ────────────────────────────────────────────────────────

/**
 * Vercel serverless function entry point.
 * Handles /api/* routing and falls through to the SSR handler for all other
 * requests. Imported by Vercel's Node.js launcher via the handler export.
 *
 * The server bundle lives at ./server/server.js so its own ../client/index.html
 * reference resolves to ./client/index.html — both files are copied into the
 * function directory by the adapter.
 */
function vercelLauncher(distDir: string): string {
  return `// Auto-generated by @jasonshimmy/vite-plugin-cer-app — do not edit.
import { readFileSync } from 'node:fs'
import * as app from './server/server.js'
${nodeDispatcherSource(distDir, './prerendered/')}
export default dispatchRequest
`
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runVercelAdapter(root: string): Promise<void> {
  const distDir = join(root, 'dist')
  if (!existsSync(distDir)) {
    throw new Error(
      `[cer-app] No dist/ directory found at ${distDir}. Run 'cer-app build' first.`,
    )
  }

  const isSSR = requiresServer(distDir)

  const outDir = join(root, '.vercel/output')

  // Clean existing Vercel output to avoid stale files.
  if (existsSync(outDir)) {
    rmSync(outDir, { recursive: true, force: true })
  }
  mkdirSync(outDir, { recursive: true })

  if (isSSR) {
    await _buildSSR(distDir, outDir)
  } else {
    _buildStatic(distDir, outDir)
  }

  console.log('[cer-app] Vercel adapter complete — output written to .vercel/output/')
  console.log('  Deploy with: vercel deploy --prebuilt')
}

// ─── SSR output ───────────────────────────────────────────────────────────────

async function _buildSSR(distDir: string, outDir: string): Promise<void> {
  const funcDir = join(outDir, 'functions/index.func')

  // Maintain the server/ → ../client/ relative layout so the server bundle's
  // built-in `../client/index.html` reference resolves correctly.
  mkdirSync(join(funcDir, 'server'), { recursive: true })
  mkdirSync(join(funcDir, 'client'), { recursive: true })

  // Vercel's prebuilt output does not install dependencies or trace chunks.
  // Bundle the complete server graph (including external CER libraries) once
  // so the function is portable and all registrations share one runtime.
  await build({
    root: join(distDir, '..'), configFile: false, logLevel: 'error',
    ssr: { noExternal: true },
    build: {
      ssr: join(distDir, 'server/server.js'), outDir: join(funcDir, 'server'),
      target: 'node24', minify: false,
      rollupOptions: { output: { entryFileNames: 'server.js' } },
    },
  })

  // Client HTML template (referenced as ../client/index.html from server.js).
  const clientHtml = join(distDir, 'client/index.html')
  if (existsSync(clientHtml)) {
    copyFileSync(clientHtml, join(funcDir, 'client/index.html'))
  }

  // Launcher: routes API requests + forwards the rest to the SSR handler.
  copyPrerenderedDocuments(distDir, join(funcDir, 'prerendered'))
  writeFileSync(join(funcDir, 'index.js'), vercelLauncher(distDir))

  // package.json: mark the function directory as ESM so Node.js treats .js
  // files as ES modules (the server bundle uses import.meta.url, etc.).
  writeFileSync(join(funcDir, 'package.json'), '{"type":"module"}\n')

  // Vercel function config.
  writeFileSync(
    join(funcDir, '.vc-config.json'),
    JSON.stringify(
      {
        runtime: 'nodejs24.x',
        handler: 'index.js',
        launcherType: 'Nodejs',
      },
      null,
      2,
    ) + '\n',
  )

  // Static assets: content-hashed files served by the Vercel CDN.
  const staticDir = join(outDir, 'static')
  _copyClientAssets(join(distDir, 'client'), staticDir)
  copyGeneratedPublicFiles(distDir, staticDir)

  // Vercel output routes config.
  writeFileSync(
    join(outDir, 'config.json'),
    JSON.stringify(
      {
        version: 3,
        routes: [
          // Apply immutable cache headers to content-hashed assets then continue
          // (so the filesystem handler can still serve them as static files).
          {
            src: '/assets/(.*)',
            headers: { 'cache-control': 'public, max-age=31536000, immutable' },
            continue: true,
          },
          // Serve matched static files from .vercel/output/static/.
          { handle: 'filesystem' },
          // Fall through to the SSR function for all other paths.
          { src: '/(.*)', dest: '/index' },
        ],
      },
      null,
      2,
    ) + '\n',
  )
}

// ─── Static (SPA / SSG) output ────────────────────────────────────────────────

function _buildStatic(distDir: string, outDir: string): void {
  const staticDir = join(outDir, 'static')
  mkdirSync(staticDir, { recursive: true })

  const clientDir = join(distDir, 'client')

  if (existsSync(clientDir)) {
    // SSG: pre-rendered HTML lives in dist/, assets in dist/client/.
    // Copy HTML (and any other root-level files) from dist/ — skip client/ dir
    // and ssg-manifest.json which are build artifacts, not deployable content.
    cpSync(distDir, staticDir, {
      recursive: true,
      filter: (src) => isPublicBuildFile(distDir, src),
    })
    // Copy assets and other non-HTML files from dist/client/ into static root
    // so URLs like /assets/main.abc123.js resolve correctly.
    _copyClientAssets(clientDir, staticDir)
  } else {
    // SPA: everything is in dist/ at the correct paths already.
    cpSync(distDir, staticDir, { recursive: true, filter: (src) => isPublicBuildFile(distDir, src) })
  }

  // Vercel output config: serve static files, fall back to index.html (SPA).
  writeFileSync(
    join(outDir, 'config.json'),
    JSON.stringify(
      {
        version: 3,
        routes: [
          {
            src: '/assets/(.*)',
            headers: { 'cache-control': 'public, max-age=31536000, immutable' },
            continue: true,
          },
          { handle: 'filesystem' },
          // SPA fallback: serve index.html for any unmatched path.
          existsSync(join(distDir, 'ssg-manifest.json'))
            ? { src: '/(.*)', dest: '/404.html', status: 404 }
            : { src: '/(.*)', dest: '/index.html' },
        ],
      },
      null,
      2,
    ) + '\n',
  )
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Copies Vite-hashed assets and any other public files (favicon, robots.txt, …)
 * from the client dist directory into `destDir`.
 * Skips index.html — that is handled by the SSR function or SSG pre-rendering.
 */
function _copyClientAssets(clientDir: string, destDir: string): void {
  if (!existsSync(clientDir)) return
  mkdirSync(destDir, { recursive: true })

  for (const entry of readdirSync(clientDir)) {
    if (entry === 'index.html' || entry === '.vite') continue // served by function / SSG HTML
    const src = join(clientDir, entry)
    const dest = join(destDir, entry)
    if (statSync(src).isDirectory()) {
      cpSync(src, dest, { recursive: true })
    } else {
      copyFileSync(src, dest)
    }
  }
}
