// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app
// Do not edit — regenerated automatically on dev server start and build.

declare module 'virtual:cer-routes' {
  import type { Route } from '@jasonshimmy/custom-elements-runtime/router'
  const routes: Route[]
  export default routes
}

declare module 'virtual:cer-layouts' {}
declare module 'virtual:cer-components' {}

declare module 'virtual:cer-plugins' {
  import type { AppPlugin } from '@jasonshimmy/vite-plugin-cer-app/types'
  const plugins: AppPlugin[]
  export default plugins
}

declare module 'virtual:cer-composables' {
  export { useKsCounter } from './app/composables/useKsCounter'
}

declare module 'virtual:cer-middleware' {
  const middleware: Record<string, Function>
  export { middleware }
}

declare module 'virtual:cer-loading' {
  export const hasLoading: boolean
  export const loadingTag: string | null
}

declare module 'virtual:cer-error' {
  export const hasError: boolean
  export const errorTag: string | null
}
