// AUTO-GENERATED by @jasonshimmy/vite-plugin-cer-app
// Do not edit — regenerated automatically on dev server start and build.

export {}

declare global {
  const component: typeof import('@jasonshimmy/custom-elements-runtime')['component']
  const html: typeof import('@jasonshimmy/custom-elements-runtime')['html']
  const css: typeof import('@jasonshimmy/custom-elements-runtime')['css']
  const ref: typeof import('@jasonshimmy/custom-elements-runtime')['ref']
  const computed: typeof import('@jasonshimmy/custom-elements-runtime')['computed']
  const watch: typeof import('@jasonshimmy/custom-elements-runtime')['watch']
  const watchEffect: typeof import('@jasonshimmy/custom-elements-runtime')['watchEffect']
  const useProps: typeof import('@jasonshimmy/custom-elements-runtime')['useProps']
  const useEmit: typeof import('@jasonshimmy/custom-elements-runtime')['useEmit']
  const useOnConnected: typeof import('@jasonshimmy/custom-elements-runtime')['useOnConnected']
  const useOnDisconnected: typeof import('@jasonshimmy/custom-elements-runtime')['useOnDisconnected']
  const useOnAttributeChanged: typeof import('@jasonshimmy/custom-elements-runtime')['useOnAttributeChanged']
  const useOnError: typeof import('@jasonshimmy/custom-elements-runtime')['useOnError']
  const useStyle: typeof import('@jasonshimmy/custom-elements-runtime')['useStyle']
  const useDesignTokens: typeof import('@jasonshimmy/custom-elements-runtime')['useDesignTokens']
  const useGlobalStyle: typeof import('@jasonshimmy/custom-elements-runtime')['useGlobalStyle']
  const useExpose: typeof import('@jasonshimmy/custom-elements-runtime')['useExpose']
  const useSlots: typeof import('@jasonshimmy/custom-elements-runtime')['useSlots']
  const provide: typeof import('@jasonshimmy/custom-elements-runtime')['provide']
  const inject: typeof import('@jasonshimmy/custom-elements-runtime')['inject']
  const createComposable: typeof import('@jasonshimmy/custom-elements-runtime')['createComposable']
  const nextTick: typeof import('@jasonshimmy/custom-elements-runtime')['nextTick']
  const defineModel: typeof import('@jasonshimmy/custom-elements-runtime')['defineModel']
  const getCurrentComponentContext: typeof import('@jasonshimmy/custom-elements-runtime')['getCurrentComponentContext']
  const isReactiveState: typeof import('@jasonshimmy/custom-elements-runtime')['isReactiveState']
  const unsafeHTML: typeof import('@jasonshimmy/custom-elements-runtime')['unsafeHTML']
  const decodeEntities: typeof import('@jasonshimmy/custom-elements-runtime')['decodeEntities']
  const useTeleport: typeof import('@jasonshimmy/custom-elements-runtime')['useTeleport']

  const when: typeof import('@jasonshimmy/custom-elements-runtime/directives')['when']
  const each: typeof import('@jasonshimmy/custom-elements-runtime/directives')['each']
  const match: typeof import('@jasonshimmy/custom-elements-runtime/directives')['match']
  const anchorBlock: typeof import('@jasonshimmy/custom-elements-runtime/directives')['anchorBlock']

  const useHead: typeof import('@jasonshimmy/vite-plugin-cer-app/composables')['useHead']
  const usePageData: typeof import('@jasonshimmy/vite-plugin-cer-app/composables')['usePageData']

  const useKsCounter: typeof import('./app/composables/useKsCounter')['useKsCounter']

  // SSR loader data injected as window.__CER_DATA__ by the server.
  // Consumed once by usePageData() during client hydration.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  var __CER_DATA__: any
}
